/* =====================================================================
   PINE PRACTICES . the growth plan library for high schoolers (GWG BLD 739)
   Built for grades 9 to 12.

   Same shapes as Sequoia's practices.js (and Oak's inline library), so an
   app built from Sequoia's app.js swaps SEQUOIA_PRACTICES for these:
     DOMAIN_DEFS  six parts: key, name, color, group, prompt, restore
                  [[name, line]], strength_msg, growth_steps
     GUIDES       "part|Name": {why, today, build, hard, vary?, adapt?}
                  for the restore practices
     G            the same, for the NEW practices
     META         part: {Name: [discipline, time, evidence, source url or '']}
     NEW          part: [[name, line]], appended to restore by the app
     EV, DISC     the same codes as Oak
     SRC          source urls used in META
     SHELF        part: [[title, url or '', line]] (Resource shelf)
     FLAGS        "part|Name": {strand: 'move' | 'rest' | 'nourish' (Leaves),
                  levels: ['gentle','moderate','athletic'], seated (has a
                  seated or low-energy way, in adapt), safety, faith (has a
                  Plain version in PLAIN)}
     SOURCES      "part|Name": source ids (shared/gg-sources.js) or
                  {label, href, adapted}, for PX 'pine:<practice>'
   Extra for Pine (Faith or Plain wording, decided by Chris, BLD 739):
     PLAIN        "part|Name": {n, d, g} for every practice flagged faith.
                  n is the name shown in Plain wording (the stored key stays
                  "part|Name", so a teen who switches keeps their practices),
                  d the one line, g the guide (vary is '' in Plain).
     PLAIN_PARTS  part: {prompt, strength_msg, growth_steps} where the Plain
                  wording differs (Roots only).
     PLAIN_SHELF  part: shelf list for Plain wording (Roots only).
   Kids' faith rules apply in the Faith wording: invite, don't assume; God is
   one door among several; never a judge; experience, never belief.
   adapt (in a guide) is the seated or low-energy way of a movement practice.
   Edit words in the table below. No dashes; Title Case for practice names.
   No guides are linked yet (Pine's guides come next build).
   ===================================================================== */
(function () {
  if (window.PINE_PRACTICES) return;

  const EV = { W: 'Well studied', S: 'Some evidence', E: 'Early research', T: 'Rooted in tradition' };
  const DISC = { C: 'Contemplative and prayer', B: 'Body and breath', R: 'Relationships', W: 'Writing and creativity', S: 'Service and generosity', L: 'Study and learning', N: 'Nature', Z: 'Rest and sabbath' };
  const SRC = {
    cp: 'https://www.contemplativeoutreach.org/centering-prayer-method/',
    lectio: 'https://www.contemplativeoutreach.org/lectio-divina-contemplation/',
    examen: 'https://www.jesuits.org/spirituality/the-ignatian-examen/',
    awe: 'https://ggia.berkeley.edu/practice/awe_walk',
    gl: 'https://ggia.berkeley.edu/practice/gratitude_letter',
    froh09: 'https://greatergood.berkeley.edu/images/uploads/Who_benefits_the_most_from_a_gratitude_intervention_in_children_and_adolescents.pdf',
    sc: 'https://self-compassion.org/',
    selfcomp: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6061226/',
    yeager19: 'https://www.nature.com/articles/s41586-019-1466-y',
    schleider: 'https://www.nature.com/articles/s41562-021-01235-0',
    bronk: 'https://www.semanticscholar.org/paper/Claremont-Purpose-Scale:-A-Measure-that-Assesses-of-Bronk-Riches/9287143c5c62b59944347762f757b4147f2dfa09',
    schreier: 'https://jamanetwork.com/journals/jamapediatrics/fullarticle/1655500',
    wyman: 'https://ojp.gov/ncjrs/virtual-library/abstracts/outcome-evaluation-sources-strength-suicide-prevention-program',
    monahan: 'https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1467-8624.2010.01543.x',
    sgsocial: 'https://www.hhs.gov/sites/default/files/sg-youth-mental-health-social-media-advisory.pdf',
    stanley: 'https://www.rcpsych.ac.uk/docs/default-source/improving-care/nccmh/suicide-prevention/monthly-clinic/comparison-of-safety-planning_stanley_2018.pdf',
    mtf24: 'https://nida.nih.gov/news-events/news-releases/2024/12/reported-use-of-most-drugs-among-adolescents-remained-low-in-2024',
    recchia: 'https://jamanetwork.com/journals/jamapediatrics/fullarticle/2799811',
    cdcpa: 'https://www.cdc.gov/physical-activity-education/guidelines/index.html',
    aasmteen: 'https://aasm.org/resources/pdf/pediatricsleepdurationconsensus.pdf',
    aapstart: 'https://publications.aap.org/pediatrics/article/134/3/642/74175/School-Start-Times-for-Adolescents',
    nat: 'https://www.nature.com/articles/s41598-019-44097-3',
    cbti: 'https://doi.org/10.7326/M14-2841',
    brenner: 'https://publications.aap.org/pediatrics/article-pdf/138/3/e20162148/1344770/peds_20162148.pdf',
    drivers: 'https://cdc.gov/teen-drivers/risk-factors/index.html',
    worry: 'https://doi.org/10.1016/0005-7967(83)90206-1',
    names: 'https://doi.org/10.1111/j.1467-9280.2007.01916.x',
    expressive: 'https://doi.org/10.1037/0021-843X.95.3.274',
    goals: 'https://doi.org/10.1177/0146167201277003',
    hope: 'https://doi.org/10.1207/S15327965PLI1304_01',
    soul: 'https://youthandreligion.nd.edu/announcements/book-announcements/paperback-publication-of-soul-searching/',
    lk: 'https://doi.org/10.1037/a0013262',
    tgt: 'https://doi.org/10.1037/0003-066X.60.5.410'
  };

  // Standing safety lines for Pine movement and food (Pine research, Section 3).
  const SAFE = "Rest if you're hurt, and tell a coach or doctor about pain that won't go away. After a hit to the head, stop and get checked.";
  const FOODSAFE = "If food, weight, or exercise starts to feel like rules you can't break, tell someone you trust.";
  const CBTI = { label: 'Cognitive behavioral therapy for insomnia (CBT-I)', href: SRC.cbti, adapted: true };
  const POMO = { label: 'Francesco Cirillo, the Pomodoro Technique', href: '', adapted: true };
  const CRISIS = "If you're thinking about not wanting to be alive, call or text 988 now, or text HOME to 741741. In danger right now, call 911.";

  // One row per practice.
  // p part, n name, d one line, b true = in the restore list (the rest go to NEW),
  // m [discipline, time, evidence, source url], g {why, today, build, hard, vary, adapt},
  // f flags, s sources, plain {n, d, g} for Plain wording (faith practices only).
  const ROWS = [

  // ---------------- ROOTS (What grounds you) ----------------
  { p: 'roots', b: 1, n: 'Prayer', d: "If prayer is part of your life, talk with God, or whatever you hold sacred, in your own words. Short and honest is enough.",
    m: ['C', '5 min', 'T', ''], f: { faith: 1 },
    g: { why: "Prayer is honest conversation. For many people it's where they set down what they're carrying and remember they're not alone. You don't need special words.",
      today: "Find two quiet minutes. Say or write three things: what you're thankful for, what you're carrying, and what you need. That's a whole prayer.",
      build: "Pick one anchor in your day, like the bus ride, the walk to class, or getting into bed, and pray there for two weeks.",
      hard: "If words won't come, one word is a prayer, and so is silence. If you're not sure who you're talking to right now, say that. Honest counts.",
      vary: "If prayer isn't part of your life, take two quiet minutes to name what you're thankful for and what you hope for." },
    plain: { n: 'Honest Words', d: "Take two quiet minutes to say, or write, what's true for you today.",
      g: { why: "Putting what you're carrying into words, even just to yourself, helps you set it down. You don't need the right words, just true ones.",
        today: "Find two quiet minutes. Say or write three things: what you're thankful for, what you're carrying, and what you need.",
        build: "Pick one anchor in your day, like the bus ride or getting into bed, and do this there for two weeks.",
        hard: "If nothing comes, one word is enough. \"Tired\" is honest. So is \"okay.\"", vary: '' } } },
  { p: 'roots', b: 1, n: 'Quiet Time', d: "Five minutes with no phone, no music, and nothing to get done.",
    m: ['Z', '5 min', 'E', ''],
    g: { why: "Most days are full of input. A few minutes with nothing coming in lets your thoughts settle and gives you room to hear yourself.",
      today: "Put your phone in another room. Sit somewhere comfortable for five minutes. Let thoughts come and go. You're not trying to get anywhere.",
      build: "Pick a time that's already quiet, like right after school or before bed, and keep it most days for two weeks.",
      hard: "Quiet isn't for everyone, and that's okay. If sitting still feels bad, walk slowly instead. Eyes open is fine, and you can stop anytime." } },
  { p: 'roots', b: 1, n: 'Examen', d: "At the end of the day, look back for where you felt most alive and where you felt drained, and where God may have been in it.",
    m: ['C', '10 min', 'T', SRC.examen], f: { faith: 1 }, s: ['examen'],
    g: { why: "Looking back on your day, slowly, shows you what gives you life and what drains it. Over time, you start choosing more of the good. The Examen is an old prayer practice from the Jesuit tradition.",
      today: "Before bed, replay your day like a video. Ask: when did I feel most alive? When did I feel most drained? Where might God have been with me today? Say thank you for one thing.",
      build: "Do it for two weeks and look for patterns. Same people, same places, same times of day?",
      hard: "If the day was rough, stay with one small good moment. Notice, don't grade yourself.",
      vary: "If God isn't part of how you see things, skip that question and keep the other two." },
    plain: { n: 'Look Back on Your Day', d: "At the end of the day, look back for where you felt most alive and where you felt drained.",
      g: { why: "Looking back on your day, slowly, shows you what gives you life and what drains it. Over time, you start choosing more of the good.",
        today: "Before bed, replay your day like a video. Ask: when did I feel most alive? When did I feel most drained? Name one thing you're glad about.",
        build: "Do it for two weeks and look for patterns. Same people, same places, same times of day?",
        hard: "If the day was rough, stay with one small good moment. Notice, don't grade yourself.", vary: '' } } },
  { p: 'roots', b: 1, n: 'Awe Walk', d: "A slow walk with your phone away, looking for something big, beautiful, or surprising.",
    m: ['N', '15 min', 'S', SRC.awe], f: { seated: 1 },
    g: { why: "Awe, that wow feeling, makes your worries feel their real size and helps you feel part of something bigger. In one study, people who took weekly awe walks felt more joy over time.",
      today: "Walk for fifteen minutes with your phone in your pocket. Look for something vast or surprising: sky, trees, water, light, a tiny bug. When you find it, stop for three breaths.",
      build: "Make it weekly. Try a new route, or the same one in a different season.",
      hard: "Can't get outside? Look up at the sky from a window, or watch a video of a place that amazes you. Tell someone where you're going if you walk alone.",
      adapt: "Low energy: sit by a window or on a step and look for one wow thing for five minutes." } },
  { p: 'roots', b: 1, n: 'Worship', d: "If worship is part of your life, join it in a way that fits: with your family, a youth group, a service, or music at home.",
    m: ['C', 'Varies', 'T', ''], f: { faith: 1 },
    g: { why: "Worship turns your attention from your own worries to something larger. Doing it with other people can make you feel you belong somewhere.",
      today: "Put on one song or reading that stirs something sacred in you, and give it your full attention for ten minutes.",
      build: "Choose one way to join worship most weeks: with your family, a youth group, or a service. Sitting with a friend helps.",
      hard: "If a faith community has felt scary or made you feel not good enough, you can start small and private. Talk with someone you trust about what happened.",
      vary: "If worship isn't part of your life, spend time with music, art, or nature that fills you with gratitude." },
    plain: { n: 'Be Part of Something Bigger', d: "Join something that lifts your eyes past your own week: a choir, a band, a team, a service project.",
      g: { why: "Being part of something larger than yourself turns your attention from your own worries, and doing it with other people helps you feel you belong.",
        today: "Put on one song or watch one thing that fills you with wonder, and give it your full attention for ten minutes.",
        build: "Pick one group that lifts you, a choir, a team, a club, a service project, and show up most weeks.",
        hard: "Not sure where you fit? Try one thing once. You don't have to commit to know if it's yours.", vary: '' } } },
  { p: 'roots', b: 1, n: 'Scripture', d: "Read a short passage from your sacred text slowly, more than once, and notice what stays with you.",
    m: ['L', '10 min', 'T', SRC.lectio], f: { faith: 1 }, s: ['lectio'],
    g: { why: "Words people have leaned on for centuries can meet you where you are. Reading slowly, more than once, lets them land.",
      today: "Choose one short passage: a psalm, a verse, a few lines from your tradition. Read it three times slowly. Notice the word or line that catches you, and carry it through the day.",
      build: "Read a little each day from one book. Write down the lines that stay with you.",
      hard: "If a passage is confusing or hard, ask a parent, youth leader, or someone you trust what they think. Questions are welcome.",
      vary: "Any words of wisdom work: a poem, a song lyric, or a quote from someone you admire." },
    plain: { n: 'Words to Live By', d: "Read a short poem, lyric, or quote slowly, more than once, and notice what stays with you.",
      g: { why: "Words that have helped other people can meet you where you are. Reading slowly, more than once, lets them land.",
        today: "Choose a short poem, a lyric, or a quote. Read it three times slowly. Notice the line that catches you, and carry it through the day.",
        build: "Keep a running note of lines that stay with you. Read one when you need it.",
        hard: "Nothing grabs you? Ask someone you admire what words they live by.", vary: '' } } },
  { p: 'roots', n: 'Breath Prayer', d: "A short phrase prayed on the in-breath and the out-breath, anywhere.",
    m: ['C', '2 min', 'T', ''], f: { faith: 1 },
    g: { why: "Tying a short phrase to your breath gives a busy mind somewhere to rest, and it goes with you into class, the locker room, or the car.",
      today: "Choose a short phrase, like \"Be with me\" on the in-breath and \"I am not alone\" on the out-breath. Breathe it slowly ten times.",
      build: "Use it at the same moment each day, like before a test or a game, so it's ready when you need it.",
      hard: "If the words feel empty, breathe with them anyway. The body often settles before the mind does.",
      vary: "Any calming phrase works: \"Here,\" then \"Now.\"" },
    plain: { n: 'Breath Phrase', d: "A short phrase on the in-breath and the out-breath, anywhere.",
      g: { why: "Tying a short phrase to your breath gives a busy mind somewhere to rest, and it goes with you into class, the locker room, or the car.",
        today: "Choose a short phrase, like \"I am here\" on the in-breath and \"I can do this\" on the out-breath. Breathe it slowly ten times.",
        build: "Use it at the same moment each day, like before a test or a game, so it's ready when you need it.",
        hard: "If the words feel silly, breathe with them anyway. The body often settles before the mind does.", vary: '' } } },
  { p: 'roots', n: 'Sit Spot', d: "Go back to the same spot outside, or the same window, and notice what changes.",
    m: ['N', '10 min', 'E', ''], f: { seated: 1 },
    g: { why: "Returning to the same spot teaches you to notice slow changes, and gives you one small piece of the world that feels like yours.",
      today: "Pick a spot you can reach easily: a step, a bench, a tree in the yard. Leave your phone inside. Sit for five minutes and notice sounds, light, and weather.",
      build: "Come back a few times a week. Notice what's different since last time.",
      hard: "Restless? Two minutes counts. No good spot outside? A window works." } },
  { p: 'roots', n: 'Carry Your Questions', d: "Write down one big question about faith or meaning, and let it stay open.",
    m: ['W', '10 min', 'S', SRC.soul], f: { faith: 1 }, s: ['smithdenton'],
    g: { why: "A large national study of teenagers found that many find faith hard to put into words. Questions and doubts are a normal part of growing up, not a sign you're doing it wrong.",
      today: "Write down one question you carry about God, faith, or what life means. Don't answer it yet. Just let it be on the page.",
      build: "Bring your question to someone you trust: a parent, a youth leader, a chaplain, a friend who thinks deeply. Ask what they've wondered too.",
      hard: "If questions bring up worry or guilt, you're not in trouble for asking. Faith traditions are full of people who asked hard questions.",
      vary: "Your question doesn't have to be about God. What matters most, and why am I here, are real questions too." },
    plain: { n: 'Carry Your Big Questions', d: "Write down one big question about what matters or what life means, and let it stay open.",
      g: { why: "Big questions are a normal part of growing up. Writing one down lets you live with it instead of pushing it away.",
        today: "Write down one question you carry about what matters, or what your life is for. Don't answer it yet.",
        build: "Bring it to someone you trust who thinks deeply, and ask what they've wondered too.",
        hard: "If a question brings up worry, talk with someone you trust. Questions are a sign of a thinking mind.", vary: '' } } },
  { p: 'roots', n: 'Lament', d: "Tell God, or whatever you hold sacred, honestly what hurts, anger included.",
    m: ['C', '10 min', 'T', ''], f: { faith: 1 },
    g: { why: "Many faith traditions have prayers of lament, like the Psalms, where people say exactly what hurts. Saying it honestly keeps pain from hardening inside you.",
      today: "Name what hurts, as plainly as you can. Write it or say it out loud. Say what you wish were different. End with one honest line, like \"I'm still here.\"",
      build: "When something hard happens, come back to this. Read one psalm of lament and notice how honest it is.",
      hard: "If it feels wrong to be angry at God or at life, many traditions make room for exactly this. If the hurt is too heavy to carry alone, tell someone you trust. " + CRISIS,
      vary: "If prayer isn't part of your life, write a letter to no one about what hurts." },
    plain: { n: 'Say What Hurts', d: "Write or say honestly what hurts, anger included.",
      g: { why: "Saying exactly what hurts, plainly, keeps pain from hardening inside you. It also makes it easier to ask for help.",
        today: "Name what hurts, as plainly as you can. Write it or say it out loud. Say what you wish were different. End with one honest line, like \"I'm still here.\"",
        build: "When something hard happens, come back to this. Then show it to someone you trust, if you want to.",
        hard: "If the hurt is too heavy to carry alone, tell someone you trust. " + CRISIS, vary: '' } } },
  { p: 'roots', n: 'Sacred Music', d: "Sing or listen to worship songs, hymns, or chants that lift you.",
    m: ['C', '10 min', 'T', ''], f: { faith: 1 },
    g: { why: "Music can carry what words can't. Songs from your faith or your family can bring comfort and a sense of the sacred at the same time.",
      today: "Play one worship song, hymn, or chant that lifts you, and give it your full attention. Sing along if you want.",
      build: "Make a short playlist for hard days and another for good ones.",
      hard: "If songs from your past bring up hurt, choose new ones. You decide what goes on your list.",
      vary: "Any music that steadies you and lifts your eyes counts." },
    plain: { n: 'Music That Grounds You', d: "Listen to, or play, songs that steady you and lift your eyes.",
      g: { why: "Music can carry what words can't. Songs that steady you can calm your body and remind you what matters.",
        today: "Play one song that steadies you, and give it your full attention. No scrolling while it plays.",
        build: "Make a short playlist for hard days and another for good ones.",
        hard: "If a song pulls you down, skip it. You decide what goes on your list.", vary: '' } } },
  { p: 'roots', n: 'Sabbath Hour', d: "One hour a week of rest, with nothing to do, fix, or post. Many traditions call this sabbath.",
    m: ['Z', '60 min', 'T', ''], f: { faith: 1 },
    g: { why: "Many faith traditions set aside time to rest on purpose. Rest isn't lazy. It's how you come back to yourself, and a week without it wears you down.",
      today: "Pick one hour this week. Phone off or in another room. Do something restful that isn't a screen: a walk, a nap, a book, time with family.",
      build: "Keep the same hour each week, so it becomes something you look forward to.",
      hard: "Busy week? Start with twenty minutes. If your family keeps a sabbath day, this can be part of it.",
      vary: "If sabbath isn't part of your life, think of it as an unplugged hour." },
    plain: { n: 'Unplugged Hour', d: "One hour a week of rest, with nothing to do, fix, or post.",
      g: { why: "Rest isn't lazy. It's how you come back to yourself, and a week without it wears you down.",
        today: "Pick one hour this week. Phone off or in another room. Do something restful that isn't a screen: a walk, a nap, a book, time with family.",
        build: "Keep the same hour each week, so it becomes something you look forward to.",
        hard: "Busy week? Start with twenty minutes.", vary: '' } } },
  { p: 'roots', n: 'Mealtime Blessing', d: "Pause before you eat to give thanks, in a prayer or a quiet moment.",
    m: ['C', '1 min', 'T', ''], f: { faith: 1 },
    g: { why: "A short pause before eating turns an ordinary meal into a moment of thanks, and slows you down enough to enjoy it.",
      today: "Before one meal today, pause. Say a blessing you know, or a simple thank you, out loud or silently.",
      build: "Offer to say it at a family meal once a week, in your own words.",
      hard: "Eating with friends who don't pause? A silent breath of thanks works anywhere.",
      vary: "If blessings aren't part of your life, name one thing you're thankful for before you eat." },
    plain: { n: 'Mealtime Thanks', d: "Pause before you eat to name one thing you're thankful for.",
      g: { why: "A short pause before eating turns an ordinary meal into a moment of thanks, and slows you down enough to enjoy it.",
        today: "Before one meal today, pause and name one thing you're thankful for, out loud or silently.",
        build: "Try it at a family meal once a week. Ask everyone for one thing.",
        hard: "Eating with friends? A silent breath of thanks works anywhere.", vary: '' } } },
  { p: 'roots', n: 'Hold Someone in Light', d: "Hold one person in your heart or prayer for a minute: someone you love, someone struggling, someone you'll never meet.",
    m: ['C', '2 min', 'T', ''], f: { faith: 1 }, s: ['quaker'],
    g: { why: "Holding someone in mind with love widens your heart and connects you to them, even from far away. Quakers call this holding someone in the Light.",
      today: "Bring one person to mind. Picture them surrounded by light, or held by God. Pray for them, or wish them peace, for one minute.",
      build: "Over the week, include someone you love, someone who's struggling, and someone you don't get along with.",
      hard: "Mind goes blank? Start with the first person who comes to mind.",
      vary: "If prayer isn't part of your life, simply wish them well for one minute." },
    plain: { n: 'Keep Someone in Mind', d: "Think of one person for a minute and wish them well: someone you love, someone struggling, someone you'll never meet.",
      g: { why: "Wishing someone well on purpose widens your heart and connects you to them, even from far away.",
        today: "Bring one person to mind. Silently wish them peace, health, and an easier day, for one minute.",
        build: "Over the week, include someone you love, someone who's struggling, and someone you don't get along with.",
        hard: "Mind goes blank? Start with the first person who comes to mind.", vary: '' } } },
  { p: 'roots', n: 'Talk With a Faith Mentor', d: "Talk with a youth leader, pastor, chaplain, or elder in your faith about where you are right now.",
    m: ['R', '30 min', 'T', ''], f: { faith: 1 },
    g: { why: "Faith can be hard to sort out alone. A mentor who listens without pushing can help you think about your own questions in your own way.",
      today: "Name one person in your faith you trust. Write down one thing you'd like to talk about.",
      build: "Ask to meet once a month, at church, a coffee shop, or after youth group. Bring your questions, not just answers.",
      hard: "If a leader ever makes you feel unsafe or asks you to keep secrets, that's not okay. Tell a parent or another adult you trust.",
      vary: "If faith isn't part of your life, talk with someone wise you trust about what matters most to you." },
    plain: { n: 'Talk With Someone Wise', d: "Talk with someone older you trust about what matters most to you right now.",
      g: { why: "Big questions can be hard to sort out alone. Someone who listens without pushing can help you think in your own way.",
        today: "Name one person you trust: a coach, teacher, relative, or mentor. Write down one thing you'd like to talk about.",
        build: "Ask to talk once a month. Bring your questions, not just answers.",
        hard: "If an adult ever makes you feel unsafe or asks you to keep secrets, that's not okay. Tell a parent or another adult you trust.", vary: '' } } },
  { p: 'roots', n: 'What Holds Me Up', d: "List the people, places, and practices that steady you, and keep the list where you'll see it.",
    m: ['W', '10 min', 'E', ''],
    g: { why: "When things get hard, it's easy to forget what helps. A list made on a good day is a map for a hard one.",
      today: "Write three short lists: people who steady me, places that calm me, and things I do that help. Faith, family traditions, music, and nature all count.",
      build: "Keep it in your phone notes or on your wall. Add to it when you notice something new.",
      hard: "Short list? One name, one place, one thing is a real start." } },

  // ---------------- TRUNK (Purpose) ----------------
  { p: 'trunk', b: 1, n: 'Values Sort', d: "Pick the handful of values that matter most to you, and one way to live one this week.",
    m: ['W', '15 min', 'S', ''], s: ['act'],
    g: { why: "Values are what you want to stand for, not rules someone hands you. Knowing yours makes choices easier, from friends to plans after high school.",
      today: "Write down ten words that matter to you, like honesty, faith, family, courage, fun, fairness, or creativity. Circle the three that matter most.",
      build: "Pick one of the three and do one small thing this week that lives it out.",
      hard: "Not sure what you value? Think of someone you admire. What do they stand for?" } },
  { p: 'trunk', b: 1, n: 'Purpose Reflection', d: "Write what you care about, what you're working toward, and who it helps.",
    m: ['W', '15 min', 'S', SRC.bronk], s: ['bronk18', 'damon03'],
    g: { why: "Researchers who study purpose in young people describe it in three parts: something you care about, something you're working toward, and a way it reaches beyond you. Purpose often starts taking shape in the high school years.",
      today: "Answer three questions in a few lines each: What do I care about? What am I working toward? Who could it help?",
      build: "Add your answers to Next Steps, and come back to them each season.",
      hard: "Purpose doesn't have to be big or final. Caring for a sibling, practicing a craft, or showing up for your team counts." } },
  { p: 'trunk', b: 1, n: 'Volunteer', d: "Give an hour where you're needed: tutoring, a food shelf, a younger team, your faith community.",
    m: ['S', '60 min', 'W', SRC.schreier], s: ['schreier13'],
    g: { why: "Helping others gives your days purpose. In one study, high schoolers who volunteered weekly with younger kids had better heart-health markers afterward than students on a waitlist.",
      today: "Name one place that could use you: a younger sibling's team, a food shelf, a reading program, a neighbor.",
      build: "Pick a regular time, even once a month. Ask a friend to come with you.",
      hard: "Need service hours? Choose something you'd want to do anyway. It counts more when it fits you." } },
  { p: 'trunk', b: 1, n: 'My Brain Grows', d: "Write about a skill that got better with practice, or a note to a younger student about it.",
    m: ['W', '15 min', 'W', SRC.yeager19], s: ['yeager19'],
    g: { why: "Your brain gets stronger when you work at hard things, like a muscle. In a national study of ninth graders, a short lesson on this idea helped students who were struggling raise their grades.",
      today: "Write about one thing you couldn't do before and can do now: a skill, a sport, a class, a song. What helped you get better?",
      build: "Write a short note to a younger student about something that felt hard at first and got easier with practice.",
      hard: "Feeling stuck in a class? Add \"yet\" to the end: I don't get this yet." } },
  { p: 'trunk', b: 1, n: 'Create Something', d: "Make something with your hands or your head: art, music, code, a meal, a video, a fixed bike.",
    m: ['W', '30 min', 'E', ''],
    g: { why: "Making something helps you work through what you feel, and finishing it gives you a quiet kind of pride. No audience required.",
      today: "Spend thirty minutes making something, anything. Sketch, write, build, cook, record, or fix.",
      build: "Choose one project you can work on each week, and finish it.",
      hard: "Don't think you're creative? Making a really good grilled cheese counts." } },
  { p: 'trunk', b: 1, n: 'Mentor Someone', d: "Help someone younger with what you know: a sport, a class, a game, how to survive freshman year.",
    m: ['S', '30 min', 'S', ''],
    g: { why: "Teaching someone else deepens what you know and shows you how far you've come. You also become someone a younger kid can look up to.",
      today: "Think of one thing you know that a younger student would want to learn. Write how you'd explain it.",
      build: "Offer to help: a younger sibling, a team, a tutoring program, a youth group. Show up regularly rather than perfectly.",
      hard: "You don't need to be an expert. Being one step ahead is enough to help." } },
  { p: 'trunk', n: 'Name Your Gifts', d: "Name three things you're good at that aren't grades or titles, and how they help people.",
    m: ['W', '10 min', 'E', ''],
    g: { why: "Your gifts are things like noticing who's left out, making people laugh, fixing things, or staying calm. Naming them helps you see where you fit.",
      today: "Write down three of your gifts. Next to each, write one person it has helped.",
      build: "Ask two people who know you well what they'd add. Use one gift on purpose this week.",
      hard: "Stuck? Ask a friend what they come to you for. That's a gift." } },
  { p: 'trunk', n: 'Journal', d: "Write a few lines most days: what happened, how it felt, what you're thinking about.",
    m: ['W', '10 min', 'E', ''],
    g: { why: "Writing helps you sort out what you think and feel, and over months it shows you how much you've grown.",
      today: "Write for five minutes about anything: today, a worry, a win, a question. Spelling doesn't matter.",
      build: "Keep it in the same place, a notebook or your Pine journal, and write at the same time most days.",
      hard: "Worried someone will read it? Your Pine journal stays on your device and opens only with your passcode. Or write and throw it away. The writing still helps." } },
  { p: 'trunk', n: 'Study Sprints', d: "Study in short, focused blocks with real breaks in between.",
    m: ['L', '30 min', 'S', ''], s: [POMO],
    g: { why: "Short, focused blocks with real breaks make it easier to start and to stay focused than one long, distracted stretch.",
      today: "Set a timer for 25 minutes. Phone in another room. Work on one thing only. When it rings, take a 5 minute break away from the screen. Do it twice.",
      build: "Plan your sprints for the week, and use breaks to stand, stretch, get water, or step outside.",
      hard: "Can't focus for 25? Start with 10. If focus has been hard for a long time, talk with a parent, counselor, or doctor." } },
  { p: 'trunk', n: 'First Job Balance', d: "Keep a job, school, and rest in balance, and speak up early when it tips.",
    m: ['L', '15 min', 'S', SRC.monahan], s: ['monahan'],
    g: { why: "A job can build skills, money, and confidence. Research on high schoolers found that working 20 hours a week or less had little effect on school, while more than 20 hours went with lower school engagement and more problems.",
      today: "Write your week: school, work, practice, homework, sleep. Count your work hours.",
      build: "If you're over 20 hours, or sleep is getting squeezed, talk with your manager about your hours before it piles up. Ask a parent to help if needed.",
      hard: "Stressed at work? Name the hardest part, and one person you could ask about it. If anyone at work makes you feel unsafe, tell a parent or trusted adult right away." } },
  { p: 'trunk', n: 'One Thing That Matters', d: "Plan one small thing today that matters to you, and do it.",
    m: ['S', '15 min', 'W', SRC.schleider], s: ['schleider22'],
    g: { why: "When you feel low, doing one thing that matters to you can lift your mood before you feel like it. A single online session teaching this helped teens feel less depressed and less hopeless.",
      today: "Name one thing that matters to you: a person, a skill, a place, a value. Plan one small action for today, with a time. Then do it.",
      build: "Do one each day for a week, and notice how your mood changes after each.",
      hard: "Low energy? Make it tiny: one text, five minutes of practice, one step outside. " + CRISIS } },
  { p: 'trunk', n: 'Expressive Writing', d: "Write about something hard for 15 minutes, for a few days in a row.",
    m: ['W', '15 min', 'W', SRC.expressive], s: ['pennebaker'],
    g: { why: "Writing your deepest thoughts and feelings about something hard, for a few days in a row, helped many people feel better over time in studies by James Pennebaker.",
      today: "Write for fifteen minutes about something that's been on your mind. Write what happened and how it made you feel. Don't stop to fix anything.",
      build: "Do it three or four days in a row, on the same topic or different ones.",
      hard: "If it brings up too much, stop and talk with someone you trust. You can write about something smaller first." } },
  { p: 'trunk', n: 'Ask Someone About Their Path', d: "Ask someone with a job or path you're curious about three questions.",
    m: ['R', '20 min', 'E', ''],
    g: { why: "Hearing how real people found their way makes the future feel less like a test and more like a road with many turns.",
      today: "Name one person whose work or path interests you: college, a trade, the military, service, a gap year, staying close to home.",
      build: "Ask them: How did you get here? What do you wish you'd known at my age? What would you try if you were me? Write what you learn in Next Steps.",
      hard: "Nervous to ask? Most people love this question. A parent or counselor can help you reach out." } },
  { p: 'trunk', n: 'Life Skill of the Month', d: "Learn one real-world skill each month: cook a meal, do laundry, budget, change a tire.",
    m: ['L', 'Varies', 'E', ''],
    g: { why: "Everyday skills build confidence and get you ready for whatever comes after high school.",
      today: "Pick one skill you want to learn this month. Ask who could teach you.",
      build: "Practice it at least three times this month, then teach it to someone else.",
      hard: "No idea where to start? Ask a parent, grandparent, or neighbor what they wish they'd learned earlier." } },
  { p: 'trunk', n: 'What I Stand For', d: "Write a few lines about what you stand for, and keep it in your phone.",
    m: ['W', '15 min', 'E', ''],
    g: { why: "Pressure is easier to handle when you've already decided who you want to be. A few lines in your own words can steady you in the moment.",
      today: "Finish these sentences: I stand for... I won't... I want people to know me as someone who...",
      build: "Read it before something hard: a party, a tough conversation, a big choice. Update it as you grow.",
      hard: "Not sure yet? Write what you're leaning toward. You're allowed to change it." } },
  { p: 'trunk', n: 'Next Steps Page', d: "Open Next Steps and add one goal, one value, or one plan for after high school.",
    m: ['W', '10 min', 'E', ''],
    g: { why: "Plans grow a little at a time. Adding one thing at a time keeps the future from feeling too big to think about.",
      today: "Open Next Steps and add one thing: a goal, a value, an idea for work, college, service, the military, a gap year, or staying close to home.",
      build: "Come back once a month. Cross off what no longer fits and add what's new.",
      hard: "Have no idea what's next? That's normal. Write one thing you're curious about." } },

  // ---------------- BARK (Mind and feelings) ----------------
  { p: 'bark', b: 1, n: 'Name It', d: "Put a feeling into one word. Naming it helps it settle.",
    m: ['W', '1 min', 'S', SRC.names], s: ['lieberman', 'siegel'],
    g: { why: "Putting a feeling into words calms the brain's alarm system. Daniel Siegel calls this \"name it to tame it.\"",
      today: "When a strong feeling shows up, pause and name it in one word: angry, nervous, embarrassed, sad, jealous, tired.",
      build: "Get more exact over time. \"Bad\" might really be disappointed, left out, or overwhelmed.",
      hard: "Can't find the word? Notice where it sits in your body, and name that: tight chest, hot face." } },
  { p: 'bark', b: 1, n: 'Slow Exhale', d: "Breathe out a little longer than you breathe in, a few times. Works anywhere.",
    m: ['B', '2 min', 'S', ''], f: { seated: 1 },
    g: { why: "A longer breath out tells your body it's safe to calm down. It works in class, on the bench, or before you say something you'll regret.",
      today: "Breathe in through your nose for a count of four. Breathe out slowly for a count of six. Do it five times.",
      build: "Practice once a day when you're already calm, so it's ready when you're not.",
      hard: "If you feel lightheaded, breathe normally for a bit. Shorter counts are fine." } },
  { p: 'bark', b: 1, n: 'Self-Compassion Break', d: "Name the pain, remember you're not alone, and talk to yourself like you'd talk to a friend.",
    m: ['C', '3 min', 'W', SRC.selfcomp], s: ['bluth16', 'selfcompteen'],
    g: { why: "Being kind to yourself when things go wrong isn't letting yourself off the hook. Teens who are kinder to themselves have less stress and low mood, and a self-compassion program for teens helped too.",
      today: "When something goes wrong, say three things: This is hard. Other people feel this too. What would I say to a friend right now? Then say that to yourself.",
      build: "Notice your inner voice for a week. When it's harsh, ask: would I say this to a friend?",
      hard: "Feels fake? Start with \"This is hard.\" Just that is a kindness." } },
  { p: 'bark', b: 1, n: 'Worry Window', d: "Give worries a set 15 minutes a day, and save them for that window.",
    m: ['W', '15 min', 'W', SRC.worry], s: ['borkovec'],
    g: { why: "Setting a worry time helps keep worry from taking over the whole day. Researchers studying worry found this simple step helps many people.",
      today: "Pick 15 minutes, not right before bed. When a worry pops up earlier, jot it down and tell yourself: later. At your time, go through the list.",
      build: "During your window, sort each worry: can I do something about this? If yes, write one next step. If no, let it go for today.",
      hard: "If worry is taking over your days or sleep for weeks, talk with a parent, counselor, or doctor. Help works." } },
  { p: 'bark', b: 1, n: 'Music', d: "Use music on purpose: calm songs to settle, upbeat songs to lift, honest songs to feel.",
    m: ['B', '10 min', 'E', ''], f: { seated: 1 },
    g: { why: "Music changes how your body feels fast. Choosing it on purpose turns it into a tool, not just background.",
      today: "Pick what you need right now: calm, energy, or a good cry. Play two songs for that, and do nothing else while they play.",
      build: "Make three short playlists: Calm, Lift, and Feel.",
      hard: "If a song keeps pulling you lower, switch it. Notice which songs leave you better than they found you." } },
  { p: 'bark', b: 1, n: 'Five Senses Pause', d: "Notice five things you see, four you feel, three you hear, two you smell, one you taste.",
    m: ['B', '2 min', 'S', ''], f: { seated: 1 },
    g: { why: "When your mind is racing, your senses bring you back to right now, where you're okay.",
      today: "Look around and name five things you see, four you can touch, three you hear, two you smell, and one you taste.",
      build: "Use it when you notice your heart racing, before a test, or after a hard text.",
      hard: "Too many steps? Just name five things you see." } },
  { p: 'bark', n: 'Before the Big Moment', d: "A short routine before a test, a game, a performance, or an interview.",
    m: ['B', '3 min', 'E', ''], f: { seated: 1 },
    g: { why: "Nerves before something big are normal. They mean it matters to you. A short routine you've practiced gives your body and mind something steady to do.",
      today: "Before your next big moment: two slow exhales, one cue word (steady, ready, go), and picture your first step going well.",
      build: "Practice the same routine before small moments, like a quiz or a practice, so it's automatic for the big ones.",
      hard: "If nerves keep you from doing things you care about, or you feel sick with worry for weeks, talk with a counselor or doctor. That's common and help works." } },
  { p: 'bark', n: 'Kind Voice Letter', d: "Write to yourself about a struggle the way a good friend would.",
    m: ['W', '15 min', 'S', SRC.sc], s: ['neff'],
    g: { why: "Most of us are harder on ourselves than on anyone else. Writing in a kind voice helps you see your situation more fairly.",
      today: "Think of something you're beating yourself up about. Write a short letter to yourself from a friend who knows you well and is on your side.",
      build: "Read it again tomorrow. Keep it for the next hard day.",
      hard: "Can't find the kind voice? Imagine a coach, grandparent, or friend who has always believed in you." } },
  { p: 'bark', n: 'Leaves on a Stream', d: "Picture each thought on a leaf floating by, and let it go.",
    m: ['C', '5 min', 'S', ''], f: { seated: 1 },
    g: { why: "You don't have to believe or fight every thought. Watching thoughts float by helps you step back from the loud ones.",
      today: "Close your eyes or look down. Picture a stream with leaves floating on it. Put each thought on a leaf and watch it drift away. Five minutes.",
      build: "Use it at night when your brain won't stop.",
      hard: "Same thought keeps coming back? That's normal. Put it on a new leaf." } },
  { p: 'bark', n: 'Body Scan', d: "Move your attention slowly from head to toe, noticing without changing anything.",
    m: ['B', '10 min', 'S', ''], f: { seated: 1 },
    g: { why: "Stress often shows up in your body before you notice it in your mind. A body scan helps you notice and let go.",
      today: "Lie down or sit back. Notice your head, face, jaw, shoulders, arms, chest, stomach, legs, and feet, one at a time. Let each part soften if it can.",
      build: "Try it in bed for a week to help you fall asleep.",
      hard: "If focusing on your body feels uncomfortable, keep your eyes open and just notice your hands and feet." } },
  { p: 'bark', n: 'Phone Check', d: "Turn off most notifications, move one app off your home screen, and set an off time.",
    m: ['B', '10 min', 'S', SRC.sgsocial], s: ['sgsocial23', 'odgers'],
    g: { why: "Your phone can connect you and drain you. The US Surgeon General found that teens who spend more than three hours a day on social media face double the risk of poor mental health, though it affects each person differently.",
      today: "Turn off every notification you don't need. Move one app you overuse off your home screen. Pick an off time for tonight.",
      build: "Check your screen time once a week. Notice which apps leave you feeling better and which leave you worse.",
      hard: "If something online is threatening or scaring you, you're not in trouble. Tell a trusted adult. For a picture someone is threatening to share, go to takeitdown.ncmec.org." } },
  { p: 'bark', n: 'My Safety Plan', d: "Write your own plan for a really hard moment: warning signs, what helps, who to call.",
    m: ['W', '20 min', 'W', SRC.stanley], f: { safety: 1 }, s: ['stanley'],
    g: { why: "A plan made on an okay day is there for you on a hard one. Safety planning with follow-up lowered suicidal behavior by about 45 percent in one large study.",
      today: "Write six short lists: my warning signs; things I can do on my own to feel a little better; people and places that help me feel better; adults I can ask for help; help lines; and how to make my space safer.",
      build: "Share it with one trusted adult. Keep a copy in your Pine journal or on paper where you can find it.",
      hard: "Help lines: call or text 988, or chat at 988lifeline.org. Text HOME to 741741. In Minnesota, call **CRISIS (274747) from a cell phone. In danger right now, call 911. If there are guns or a lot of medicine at home, ask a grown-up to lock them up or keep them somewhere else for now." } },
  { p: 'bark', n: 'Bounce Back From a Setback', d: "After a bad grade, a loss, or a cut, name what happened, what you control, and one next step.",
    m: ['W', '10 min', 'E', ''],
    g: { why: "Setbacks are part of growing at anything. Sorting what you control from what you don't keeps one bad day from becoming a story about who you are.",
      today: "Write three lines: What happened. What part I can control. One next step I'll take this week.",
      build: "Look back at old setbacks. What did each one teach you?",
      hard: "Still really down after a few days? Talk with someone you trust. A setback can feel huge, and you don't have to carry it alone." } },
  { p: 'bark', n: 'Mindfulness', d: "Give one ordinary thing your full attention: a shower, a walk to class, a meal.",
    m: ['C', '5 min', 'S', ''], f: { seated: 1 },
    g: { why: "Your mind spends a lot of time in the past or the future. Paying full attention to one ordinary thing gives it a short break.",
      today: "Pick one everyday thing, like brushing your teeth or walking to class. Do it slowly and notice everything: sounds, smells, how it feels.",
      build: "Add one mindful moment a day for two weeks.",
      hard: "Mind wanders? That's what minds do. Notice, and come back. It's optional, and you can try a different practice if this one doesn't fit." } },
  { p: 'bark', n: 'Speak Up About Your Mood', d: "If low mood or worry has lasted two weeks or more, tell a parent, counselor, or doctor.",
    m: ['R', '10 min', 'W', ''],
    g: { why: "Feeling down or worried for weeks is common in high school, and it gets better with help. Saying it out loud is the first step.",
      today: "Write one or two sentences about how your mood has been lately. Pick one adult you could show them to.",
      build: "Tell them, in person or by text. Ask your doctor about it at your next visit. A school counselor can help too.",
      hard: "Not sure how to start? Try: \"I haven't felt like myself for a while.\" " + CRISIS } },
  { p: 'bark', n: 'Playing', d: "Play for the fun of it: a game, a pickup game, cards, a puzzle, something silly.",
    m: ['R', '30 min', 'E', ''],
    g: { why: "Play isn't only for kids. It lowers stress, sparks laughter, and reminds you that not everything is a test.",
      today: "Play something for fun with no score that matters: a board game, cards, a pickup game, a video game with a friend.",
      build: "Put a game night or open gym on the calendar with friends or family.",
      hard: "Gaming eats your night? Set a stop time before you start." } },

  // ---------------- BRANCHES (Relationships) ----------------
  { p: 'branches', b: 1, n: 'Family', d: "Spend a little real time with someone in your family, even when you disagree on things.",
    m: ['R', '20 min', 'S', ''], s: ['holt'],
    g: { why: "Feeling close to even one person at home steadies you, and strong relationships are one of the best predictors of health across life.",
      today: "Spend twenty minutes with someone in your family doing something easy: a drive, a meal, a show, a walk.",
      build: "Pick one standing thing each week: Sunday breakfast, a game, a walk with the dog.",
      hard: "If home is tense, find one person to connect with. If someone at home is hurting you, that's not okay. Call or text Childhelp at 1-800-422-4453, or tell a trusted adult at school." } },
  { p: 'branches', b: 1, n: 'Friends', d: "Make time for friends who have your back, in person when you can.",
    m: ['R', 'Varies', 'W', ''], s: ['murthy'],
    g: { why: "Friends who have your back make every hard thing lighter. Time in person counts for a lot.",
      today: "Make a plan with one friend this week, in person: food, a walk, a game, studying together.",
      build: "Notice which friends leave you feeling more like yourself. Spend more time with them.",
      hard: "Between friend groups or feeling left out? That's common, and it changes. Try one club, team, or group where you can meet people who like what you like." } },
  { p: 'branches', b: 1, n: 'Name Your Trusted Adult', d: "Name one adult besides your parents you could go to, and reach out to them this week.",
    m: ['R', '10 min', 'S', SRC.wyman], s: ['wyman10'],
    g: { why: "Having trusted adults makes it easier to ask for help when things get hard. A peer leader program in high schools, Sources of Strength, helped more students see adults as people they could go to.",
      today: "Write down one or two adults you trust: a coach, teacher, counselor, relative, youth leader, boss, or neighbor.",
      build: "Reach out this week, even about something small: a question, a thank you, a quick hello. That makes it easier to go to them when something's big.",
      hard: "Can't think of anyone? Start with your school counselor. Talking with them is part of their job." } },
  { p: 'branches', b: 1, n: 'Gratitude Letter', d: "Write to someone you've never properly thanked, and read it to them.",
    m: ['W', '30 min', 'W', SRC.gl], s: ['froh09'],
    g: { why: "Writing and delivering a thank-you letter lifts your mood and theirs. In a study with young people, it helped most for those who had been feeling low on good feelings, and the lift lasted two months.",
      today: "Think of someone who helped you and never heard a real thank you. Write them a letter: what they did, and how it changed things for you.",
      build: "Read it to them in person, or by video. If that's too much, give it to them.",
      hard: "Feeling awkward is normal. It's usually one of the best moments of their week." } },
  { p: 'branches', b: 1, n: 'Active Listening', d: "Listen to understand, not to fix, and say back what you heard.",
    m: ['R', '10 min', 'S', ''],
    g: { why: "People feel close to someone who really listens. It's one of the most useful skills you'll ever learn, in friendships, family, and work.",
      today: "In your next real conversation, put your phone away. When they finish, say back what you heard: \"So you're saying...\" Then ask one question.",
      build: "Practice with one person each day for a week.",
      hard: "Want to give advice? Ask first: \"Do you want ideas, or do you want me to listen?\"" } },
  { p: 'branches', b: 1, n: 'Friendship Repair', d: "After a fight or a falling out, own your part and try to make it right.",
    m: ['R', '20 min', 'S', ''],
    g: { why: "Every friendship has breaks. Owning your part, without excuses, often brings people closer than before.",
      today: "Think of one friendship that needs a repair. Write what happened, and what part was yours.",
      build: "Reach out: \"I've been thinking about what happened. I'm sorry for my part.\" Skip the \"but.\" Ask what would help, and listen.",
      hard: "If they're not ready, give it time. If someone keeps hurting you, protecting yourself comes first. Repair is for safe friendships." } },
  { p: 'branches', n: 'Clubs', d: "Join a team, club, band, or group built around something you like.",
    m: ['R', 'Weekly', 'S', ''],
    g: { why: "A group built around something you enjoy gives you people to belong with and something to look forward to.",
      today: "Look at your school's list of clubs and teams, or a community or faith group. Pick one to try.",
      build: "Go three times before you decide. Most groups feel awkward the first time.",
      hard: "Shy? Bring a friend, or talk to one person each time." } },
  { p: 'branches', n: 'Faith', d: "If you have a faith community, let it be a place where you belong: youth group, service, choir, or a mentor.",
    m: ['R', 'Weekly', 'S', ''], f: { faith: 1 }, s: ['vanderweele'],
    g: { why: "For many teens, a faith community is a place to belong, serve, and find adults who care. Belonging to a community is linked with better health and well-being.",
      today: "Think of one way to connect with your faith community this week: youth group, a service project, helping with younger kids, or sitting with a friend.",
      build: "Find one adult there you trust, and one friend. Show up regularly.",
      hard: "If a faith community has hurt you or made you feel unsafe or not good enough, tell someone you trust. You can find other places to belong.",
      vary: "If faith isn't part of your life, choose another group that lifts you." },
    plain: { n: 'A Group That Lifts You', d: "Find a group where you belong: a team, a choir, a service group, a club.",
      g: { why: "Belonging to a community is linked with better health and well-being. A group that lifts you gives you people to show up for, and who show up for you.",
        today: "Think of one group that lifts you, or one you'd like to try. Plan to show up this week.",
        build: "Find one adult there you trust, and one friend. Show up regularly.",
        hard: "If a group has made you feel unsafe or not good enough, tell someone you trust. You can find other places to belong.", vary: '' } } },
  { p: 'branches', n: 'Ask for Help', d: "Ask one person for one specific kind of help.",
    m: ['R', '5 min', 'S', ''],
    g: { why: "Asking for help is a strength. Most people are glad to help, and asking makes the relationship stronger.",
      today: "Name one thing you need help with: a class, a ride, a decision, a hard feeling. Ask one person for that one thing.",
      build: "Notice who you can go to for what. Different people help with different things.",
      hard: "Feel like a burden? Think about how you feel when a friend asks you. Most people feel trusted." } },
  { p: 'branches', n: 'One Reach-Out a Day', d: "A short call, voice memo, or message to someone you care about.",
    m: ['R', '2 min', 'S', ''],
    g: { why: "Small, steady contact keeps people close. It takes two minutes, and it often makes someone's day.",
      today: "Send one message that's just for them: \"Thought of you today,\" or a memory, or a song you think they'd like.",
      build: "Do it once a day for a week. Try a voice memo or a call sometimes.",
      hard: "Someone not answering? Keep it light. You can't control replies, only that you reached out." } },
  { p: 'branches', n: 'Shared Meal', d: "Eat one meal a week with family or friends, phones away.",
    m: ['R', '30 min', 'S', ''],
    g: { why: "Eating together is one of the easiest ways to stay close. Phones away makes it count.",
      today: "Pick one meal this week to eat with someone. Phones away for the meal.",
      build: "Ask one real question at the table: \"What was the best part of your week?\"",
      hard: "Busy schedules? A snack after practice or breakfast on the weekend counts." } },
  { p: 'branches', n: 'Loving-Kindness', d: "Silently wish well to yourself, someone you love, someone neutral, and someone hard.",
    m: ['C', '5 min', 'W', SRC.lk], s: ['fredrickson'],
    g: { why: "Wishing people well on purpose can grow warmth toward others and yourself. In one study, people who practiced it felt more positive emotions over time.",
      today: "Silently say: May I be safe. May I be happy. May I be at peace. Then say it for someone you love, someone you barely know, and someone who's hard for you.",
      build: "Try it for two minutes a day for two weeks.",
      hard: "Hard to wish yourself well? Start with someone else, and come back to you." } },
  { p: 'branches', n: 'Respect Check', d: "Notice whether a close relationship feels respectful, and what to do if it doesn't.",
    m: ['R', '10 min', 'E', ''], f: { safety: 1 },
    g: { why: "Healthy relationships feel respectful and safe. Knowing what that looks like helps you notice early when something is off.",
      today: "Think of a close friend or someone you're dating. Ask: Can I be myself? Can I say no? Do they respect my time with other people, my phone, and my body?",
      build: "If something feels off, talk with a friend or adult you trust about it.",
      hard: "If someone checks your phone, controls who you see, pressures you, or hurts you, it's not your fault. Love Is Respect: call 1-866-331-9474, or text LOVEIS to 22522. In Minnesota, Day One: 1-866-223-1111. In danger, call 911." } },
  { p: 'branches', n: 'Easy Ways Out', d: "Practice what you'll say to turn down a ride, a vape, a drink, or a party, before you need it.",
    m: ['R', '10 min', 'E', SRC.mtf24], s: ['mtf24', 'unknown'],
    g: { why: "Most high schoolers aren't using. A 2024 national survey found record numbers of 12th graders staying away from alcohol, vaping, and drugs. Deciding ahead of time makes no easier in the moment.",
      today: "Write two lines you'd actually say, like \"I'm good, I've got practice\" or \"My parents check.\" Pick a code word to text a parent or trusted adult who will come get you, no questions that night.",
      build: "Practice saying your lines out loud once. Agree on the code word with your adult.",
      hard: "Worried about a friend? You can tell a trusted adult without naming anyone. If someone is in danger, call 911." } },
  { p: 'branches', n: 'Look Out for a Friend', d: "If a friend seems really low, check in, listen, and bring in a trusted adult.",
    m: ['R', '10 min', 'S', ''], f: { safety: 1 }, s: ['dazzi', 'gould05'],
    g: { why: "Friends are often the first to notice when someone is struggling. You don't have to fix it. Your job is to care, listen, and get help.",
      today: "If a friend seems off, ask: \"You've seemed down lately. Are you okay?\" Then listen.",
      build: "If they talk about not wanting to live, take it seriously. Ask them plainly if they're thinking about suicide. Asking doesn't put the idea in their head. Stay with them and tell a trusted adult right away, even if they ask you not to.",
      hard: "Call or text 988 together, or text HOME to 741741. In danger right now, call 911. Look after yourself afterward and talk with someone too." } },
  { p: 'branches', n: 'Ask an Elder', d: "Ask a grandparent or older relative about their life when they were your age.",
    m: ['R', '20 min', 'E', ''],
    g: { why: "Older relatives carry stories you won't hear anywhere else, and asking makes both of you feel closer.",
      today: "Call or visit a grandparent or older relative. Ask: What was your life like at my age? What were you worried about? What helped?",
      build: "Record or write down one story. Ask a new question each time you talk.",
      hard: "No grandparent nearby? An older neighbor, a mentor, or someone at your faith community works too." } },

  // ---------------- LEAVES (Body: Move, Rest, Nourish) ----------------
  { p: 'leaves', b: 1, n: 'Movement', d: "Move most days in a way you enjoy: a sport, a walk, lifting, dance, biking.",
    m: ['B', '60 min', 'W', SRC.recchia], f: { strand: 'move', levels: ['gentle', 'moderate', 'athletic'], seated: 1, safety: 1 }, s: ['recchia23', 'cdcpa'],
    g: { why: "Teens do best with about 60 minutes of movement a day. Being active also eases low mood: in a large review, physical activity reduced depression symptoms in young people, more so at 13 and older.",
      today: "Move for twenty minutes today in a way you enjoy: walk, shoot hoops, dance, lift, bike, swim.",
      build: "Build toward 60 minutes a day, in pieces if that's easier. Add something that makes you breathe hard on three days a week.",
      hard: SAFE + " " + FOODSAFE,
      adapt: "Low energy or seated: march in place, roll your shoulders, lift your arms overhead, and stretch for ten minutes. Hurt? Ask your coach or trainer what you can do while you heal." } },
  { p: 'leaves', b: 1, n: 'Sleep', d: "Aim for 8 to 10 hours with a steady bedtime and the phone charging outside your room.",
    m: ['Z', 'Nightly', 'W', SRC.aasmteen], f: { strand: 'rest', safety: 1 }, s: ['aasm16', 'aapsleep14'],
    g: { why: "Teens need 8 to 10 hours of sleep. Your body clock shifts later in the teen years, which is why pediatricians call for later school start times. Good sleep helps mood, focus, sports, and driving.",
      today: "Count back 8 to 10 hours from your wake time. That's your bedtime tonight.",
      build: "Keep your bedtime and wake time within an hour or so on weekends too. Charge your phone outside your bedroom.",
      hard: "If you snore loudly, or you're always sleepy even after a full night, tell a doctor." } },
  { p: 'leaves', b: 1, n: 'Food', d: "Eat regular meals, starting with breakfast, and enough to fuel your day.",
    m: ['B', 'Daily', 'S', ''], f: { strand: 'nourish', safety: 1 },
    g: { why: "Your body is still growing and doing a lot. Regular meals keep your energy, focus, and mood steadier than skipping and grazing.",
      today: "Eat breakfast, even something small: toast with peanut butter, yogurt, fruit, eggs.",
      build: "Aim for three meals and a snack or two, with some protein, fruit or vegetables, and whole grains in most.",
      hard: FOODSAFE + " Food short at home? Ask a school counselor about meal programs. It's more common than you think." } },
  { p: 'leaves', b: 1, n: 'Breathe', d: "Practice slow, easy breathing each day. It calms the body anywhere.",
    m: ['B', '2 min', 'S', ''], f: { strand: 'rest', seated: 1 },
    g: { why: "Slow, easy breathing is one of the quickest ways to calm your body, before a test, a game, or a hard conversation.",
      today: "Sit comfortably. Breathe in gently through your nose and out slowly, a little longer than the breath in. Five times.",
      build: "Pair it with something you do daily: before class, before practice, at bedtime.",
      hard: "If you feel dizzy, breathe normally for a while. With asthma, keep it easy and never force a breath." } },
  { p: 'leaves', b: 1, n: 'Two Hours Outdoors', d: "About two hours a week outside, in one stretch or many short ones.",
    m: ['N', 'Weekly', 'S', SRC.nat], f: { strand: 'move', levels: ['gentle', 'moderate', 'athletic'], seated: 1, safety: 1 }, s: ['white'],
    g: { why: "People who spent about two hours a week in nature reported better health and well-being than those who spent none.",
      today: "Spend 20 minutes outside: a park, your yard, a trail, the walk home.",
      build: "Add it up to two hours across the week. Practice outside counts.",
      hard: "Watch for weather and traffic, dress for the cold, and tell someone where you're going.",
      adapt: "Low energy: sit outside on a step, a bench, or a porch. That counts." } },
  { p: 'leaves', b: 1, n: 'Phone Outside the Bedroom', d: "Charge your phone outside your room at night.",
    m: ['Z', 'Nightly', 'S', SRC.sgsocial], f: { strand: 'rest' }, s: ['sgsocial23'],
    g: { why: "Phones at night cut into sleep, from late scrolling to buzzes in the middle of the night. The US Surgeon General's advisory names poor sleep as one of the ways social media can harm teens.",
      today: "Tonight, charge your phone in the kitchen or hallway. Use a cheap alarm clock if you need one.",
      build: "Make it a family thing. Everyone's phone charges in the same spot.",
      hard: "Worried about missing something? Tell friends your off time. Anything urgent can reach a parent's phone." } },
  { p: 'leaves', n: 'Walk or Jog', d: "A walk or jog at your own pace, outside or in.",
    m: ['B', '20+ min', 'W', SRC.recchia], f: { strand: 'move', levels: ['gentle', 'moderate', 'athletic'], seated: 1, safety: 1 }, s: ['recchia23'],
    g: { why: "Walking and running are some of the simplest ways to lift your mood and clear your head.",
      today: "Walk or jog for twenty minutes. Music or a friend makes it go faster.",
      build: "Add a few minutes each week. Try a new route. Ready for more? Add hills or short bursts.",
      hard: SAFE,
      adapt: "Low energy: a slow ten minute walk counts. Seated: march in place from a chair for five minutes." } },
  { p: 'leaves', n: 'Strength Training', d: "Bodyweight or weight training two or three days a week, with good form.",
    m: ['B', '20 min', 'W', SRC.cdcpa], f: { strand: 'move', levels: ['moderate', 'athletic'], seated: 1, safety: 1 }, s: ['cdcpa'],
    g: { why: "Muscle- and bone-strengthening activity three days a week is part of national guidelines for teens. It builds strength, confidence, and protects against injury.",
      today: "Do two rounds of ten squats, ten push-ups (from your knees is fine), and a 20 second plank.",
      build: "Train two or three days a week. Learn form from a coach, trainer, or PE teacher before adding weight.",
      hard: SAFE + " Never train through sharp pain.",
      adapt: "Low energy or seated: from a chair, do sit-to-stands, seated leg lifts, and wall push-ups." } },
  { p: 'leaves', n: 'Stretch Break', d: "Stand up and stretch for two minutes between classes, homework, or gaming.",
    m: ['B', '2 min', 'E', ''], f: { strand: 'move', levels: ['gentle'], seated: 1 },
    g: { why: "Sitting a long time stiffens your body and dulls your focus. A quick stretch wakes both up.",
      today: "After 30 minutes of sitting, stand and stretch: reach up, touch your toes, roll your shoulders, twist gently.",
      build: "Use your study sprint breaks for this.",
      hard: "Can't stand right now? Stretch in your seat.",
      adapt: "Seated: roll your neck and shoulders, stretch your arms overhead, and twist gently side to side." } },
  { p: 'leaves', n: 'Yoga', d: "A few simple poses to stretch, get stronger, and calm down.",
    m: ['B', '15 min', 'S', ''], f: { strand: 'move', levels: ['gentle', 'moderate'], seated: 1, safety: 1 },
    g: { why: "Yoga mixes stretching, strength, and slow breathing, so it helps your body and your mood at the same time.",
      today: "Follow a short beginner video, or try three poses: child's pose, downward dog, and a forward fold. Hold each for five slow breaths.",
      build: "Try it two or three times a week, after practice or before bed.",
      hard: "Move only as far as feels okay. " + SAFE,
      adapt: "Seated: try chair yoga, seated twists, and forward folds from a chair." } },
  { p: 'leaves', n: 'Steady Wake Time', d: "Get up at about the same time every day, weekends included.",
    m: ['Z', 'Daily', 'W', SRC.cbti], f: { strand: 'rest' }, s: [CBTI, 'trauer'],
    g: { why: "Getting up at about the same time every day sets your body's clock, so sleep comes more easily at night. It's a core step in cognitive behavioral therapy for insomnia.",
      today: "Pick a wake time you can keep all week, and set an alarm for it.",
      build: "On weekends, try to sleep in no more than an hour or two. Get daylight soon after you wake.",
      hard: "Out late? Keep the wake time, and take a short early nap if you need one." } },
  { p: 'leaves', n: 'Smart Nap', d: "Keep naps short and early, 20 minutes before about 4 p.m.",
    m: ['Z', '20 min', 'E', ''], f: { strand: 'rest' },
    g: { why: "A short nap can recharge you. Long or late naps can make it harder to fall asleep at night.",
      today: "If you need a nap, set an alarm for 20 minutes, and nap before about 4 p.m.",
      build: "If you need a nap every day, look at your bedtime. You may need more sleep at night.",
      hard: "If you're always exhausted no matter what, tell a doctor." } },
  { p: 'leaves', n: 'Morning Daylight', d: "Ten minutes of morning daylight to set your body clock.",
    m: ['N', '10 min', 'E', ''], f: { strand: 'rest', seated: 1 },
    g: { why: "Morning light helps set your body's clock, which helps you feel awake in the day and sleepy at night.",
      today: "Get ten minutes of daylight in the morning: walk to the bus, eat breakfast by a window, step outside.",
      build: "Make it part of your morning routine every day.",
      hard: "Dark winter mornings? The brightest window you have still helps.",
      adapt: "Sitting by a bright window counts." } },
  { p: 'leaves', n: 'Fuel Up', d: "Eat and drink enough before and after practice, work, or a long day.",
    m: ['B', 'Daily', 'E', ''], f: { strand: 'nourish', safety: 1 },
    g: { why: "Running on empty makes everything harder: practice, tests, and your mood. A snack and water at the right time keeps you going.",
      today: "Pack a snack and a water bottle for after school: fruit, a granola bar, cheese, a sandwich.",
      build: "Eat something one to two hours before practice or a game, and again within an hour after. Refill your water bottle through the day.",
      hard: FOODSAFE } },
  { p: 'leaves', n: 'Rest Day', d: "Take at least one full day a week off from hard training.",
    m: ['Z', 'Weekly', 'S', SRC.brenner], f: { strand: 'rest' }, s: ['brenner'],
    g: { why: "Bodies get stronger during rest, not during workouts. Pediatric sports doctors advise young athletes to take at least one or two days off a week to prevent overuse injuries and burnout.",
      today: "Look at your week and pick at least one rest day with no hard training.",
      build: "Use rest days for sleep, stretching, a walk, and time with friends. Take a longer break between seasons.",
      hard: "Feel guilty resting? Rest is part of training. " + SAFE } },
  { p: 'leaves', n: 'Driving Calm', d: "A calm routine before you drive: phone away, breathe, and leave a little early.",
    m: ['B', '2 min', 'S', SRC.drivers], f: { strand: '', safety: 1 }, s: ['cdcteendrivers'],
    g: { why: "Car crashes are the leading cause of death for teens, and drivers 16 to 19 have a fatal crash rate almost three times that of drivers 20 and older, per mile driven. A calm routine keeps your attention on the road.",
      today: "Before you start the car: phone on Do Not Disturb and out of reach, seat belt on, two slow breaths. Leave five minutes early so you're not rushing.",
      build: "Keep the same routine every time, and limit passengers while you're new to driving.",
      hard: "Too tired, upset, or offered a ride from someone who's been drinking or using? Don't drive, and don't get in. Call a parent or trusted adult for a ride." } },

  // ---------------- FRUIT (Hope) ----------------
  { p: 'fruit', b: 1, n: 'Three Good Things', d: "Each night, write three things that went well and why.",
    m: ['W', '5 min', 'W', SRC.tgt], f: {},
    g: { why: "Writing down good things trains your brain to notice them. Studies with young people found that counting good things lifted mood and gratitude.",
      today: "Before bed, write three things that went well today, big or small, and why each one happened.",
      build: "Do it every night for a week. Read back over them on a hard day.",
      hard: "Rough day? Small counts: a good song, a funny text, a warm hoodie." } },
  { p: 'fruit', b: 1, n: 'Something to Look Forward To', d: "Plan one small good thing for this week.",
    m: ['W', '5 min', 'S', ''],
    g: { why: "Having something to look forward to lifts your mood now, not just when it happens.",
      today: "Plan one small good thing for this week: a show, a meal, a game, time with a friend. Put it on your calendar.",
      build: "Keep one thing on the calendar every week.",
      hard: "Nothing sounds good? Pick something tiny and easy. Looking forward can come back slowly." } },
  { p: 'fruit', b: 1, n: 'Pay It Forward', d: "Do one small kind thing for someone, without being asked.",
    m: ['S', '5 min', 'S', ''],
    g: { why: "Kindness lifts the person who gives it as well as the one who gets it.",
      today: "Do one kind thing today: hold the door, help with a locker, compliment someone, sit with someone alone.",
      build: "Try one kind act a day for a week, and notice how you feel.",
      hard: "Feeling low? Kindness still helps, and small counts." } },
  { p: 'fruit', b: 1, n: 'Best Possible Self', d: "Write about your life a few years from now, going as well as it realistically could.",
    m: ['W', '20 min', 'W', SRC.goals], s: ['king'],
    g: { why: "Writing about your best possible future, in detail, can lift your mood and help you see what you're working toward.",
      today: "Picture yourself a few years from now, with things going as well as they realistically could. Write about it for 15 minutes: where you are, who's with you, what you're doing.",
      build: "Pick one thing from your writing and add a step toward it in Next Steps.",
      hard: "Can't picture it? Write about next month instead." } },
  { p: 'fruit', b: 1, n: 'Hope Map', d: "Map a goal, a few paths to it, the obstacles, and what you'll do about each.",
    m: ['W', '20 min', 'S', SRC.hope], s: ['snyder'],
    g: { why: "Hope is more than a feeling. It's a goal, ways to get there, and the belief that you can. Mapping it makes it real.",
      today: "Write one goal in the middle of a page. Draw three paths to it. On each, write one obstacle and one way around it.",
      build: "Pick one path and take the first step this week.",
      hard: "Feel stuck? Ask someone you trust to help you find one more path." } },
  { p: 'fruit', b: 1, n: 'Tiny Next Step', d: "Name the smallest step toward something you hope for, and do it today.",
    m: ['S', '5 min', 'S', ''],
    g: { why: "Big goals can feel impossible. One small step makes them feel real, and gives you a reason to take another.",
      today: "Name one thing you hope for. What's the smallest step you could take today? Do it.",
      build: "Do one tiny step every day for a week.",
      hard: "Too tired? Make the step even smaller. One email, one minute, one question." } },
  { p: 'fruit', n: 'Joy List', d: "A running list of small things that bring you joy.",
    m: ['W', '5 min', 'E', ''],
    g: { why: "Noticing what brings you joy helps you find more of it, and gives you ideas on days when you can't think of any.",
      today: "Start a list in your phone or notebook. Add ten small things that make you happy: a song, a food, a smell, a person, a place.",
      build: "Add one a day. On a hard day, pick one from the list and do it.",
      hard: "Nothing feels good right now? Write things that used to. They can come back." } },
  { p: 'fruit', n: 'Savoring Walk', d: "A slow walk where you soak up the good things you notice.",
    m: ['N', '15 min', 'S', ''], f: { seated: 1 },
    g: { why: "Slowing down to enjoy good moments helps them last longer and lifts your mood.",
      today: "Take a slow fifteen minute walk. Look for good things: sun, a dog, a good smell. Stop and enjoy each one for a breath.",
      build: "Take one savoring walk a week.",
      hard: "Can't get out? Savor something indoors: a hot drink, a song, a funny video.",
      adapt: "Low energy: sit by a window and savor what you see for five minutes." } },
  { p: 'fruit', n: 'Capture the Moment', d: "When something lifts you, take a photo or write a line to keep it.",
    m: ['W', '2 min', 'E', ''],
    g: { why: "Saving good moments gives you something to look back on when life gets hard.",
      today: "Next time something makes you smile, capture it: a photo, a note, a voice memo.",
      build: "Keep them in one album. Look back at the end of the month.",
      hard: "Not many good moments lately? Capture one small one. That's how the album starts." } },
  { p: 'fruit', n: 'Something Funny', d: "Look for one thing that makes you laugh each day, and share it.",
    m: ['R', '5 min', 'E', ''],
    g: { why: "Laughing eases stress and connects you with people.",
      today: "Find one thing that makes you laugh today and send it to someone who'll laugh too.",
      build: "Keep a list of things that always make you laugh.",
      hard: "Nothing seems funny? That's okay. Watch an old favorite, or ask a friend for theirs." } },
  { p: 'fruit', n: 'Hope Playlist', d: "Build a playlist of songs that remind you things can get better.",
    m: ['W', '15 min', 'E', ''],
    g: { why: "Music can carry hope when it's hard to feel on your own.",
      today: "Pick five songs that make you feel stronger or remind you things can get better. Put them in one playlist.",
      build: "Add a song whenever you find one. Share it with a friend who could use it.",
      hard: "Can't think of any? Ask friends for their songs that help." } },
  { p: 'fruit', n: 'Future Me Letter', d: "Write a letter to yourself to open at graduation or a year from now.",
    m: ['W', '20 min', 'E', ''],
    g: { why: "Writing to your future self helps you believe in a future, and reminds you later how far you've come.",
      today: "Write a letter to yourself to open a year from now, or at graduation. What are you hoping for? What do you want future you to remember?",
      build: "Seal it, or save it with a reminder date. Write a new one each year.",
      hard: "Hard to picture the future right now? Write about one thing you hope is true next month. " + CRISIS } },
  { p: 'fruit', n: 'Be Generous', d: "Give something: time, attention, a skill, or something you made.",
    m: ['S', 'Varies', 'S', ''],
    g: { why: "Giving builds hope. It reminds you that you have something to offer.",
      today: "Give one thing today: help a sibling with homework, teach a friend a trick, give away something you don't need.",
      build: "Pick one way to give each week.",
      hard: "Low on money or energy? Your attention is a gift. Really listen to someone today." } },
  { p: 'fruit', n: 'Watch Something Grow', d: "Plant seeds, keep a plant alive, or start a small project, and watch it change.",
    m: ['N', '5 min', 'E', ''], f: { seated: 1 },
    g: { why: "Tending something alive gives you a reason to check on it each day, and shows you that growth keeps happening.",
      today: "Plant a few seeds in a cup, or adopt a houseplant. Put it where you'll see it.",
      build: "Water it and check on it each day. Take a photo each week.",
      hard: "Plant didn't make it? Try a hardier one. Growing things takes practice." } },
  { p: 'fruit', n: 'Inspire Hope', d: "Tell a younger student how you got through something hard.",
    m: ['R', '15 min', 'E', ''],
    g: { why: "Your story of getting through something can give someone younger hope, and reminds you how strong you are.",
      today: "Think of something hard you got through: a move, a loss, a tough class, a cut from a team. Write what helped.",
      build: "Share it with a younger sibling, a younger teammate, or a mentee when they're going through something similar.",
      hard: "Still in the middle of it? That's okay. You can share what's helping so far." } },
  { p: 'fruit', n: 'Celebrate a Win', d: "Notice something you did well this week, and mark it.",
    m: ['W', '5 min', 'E', ''],
    g: { why: "Noticing your wins, big or small, builds confidence and the belief that effort pays off.",
      today: "Name one thing you did well this week: a grade, a play, a hard conversation, getting up when it was hard.",
      build: "Mark it: tell someone, write it down, treat yourself to something small.",
      hard: "Can't think of a win? Getting through the week counts." } }
  ];

  // ---------------- THE SIX PARTS ----------------
  // Same keys, colors, and groups as Oak; prompts, strength lines, and growth steps for high schoolers.
  const PARTS = [
    { key: 'roots', name: 'What grounds you', color: 'var(--p-roots)', group: 'root',
      prompt: "What steadies you when life gets loud? For some people that's God, prayer, or worship. For others it's family traditions, quiet, music, or time outside. Questions and doubts are welcome here.",
      strength_msg: "Strong roots mean you have something to hold on to when things get shaky. That's worth tending on purpose, even on good weeks.",
      growth_steps: [
        "Pick one practice that steadies you, a prayer, quiet time, or a walk outside, and do it three times this week.",
        "Write down one big question you carry, and talk about it with someone you trust.",
        "List the people, places, and practices that hold you up, and keep the list where you'll see it."
      ] },
    { key: 'bark', name: 'Mind and feelings', color: 'var(--p-bark)', group: 'root',
      prompt: "When stress, worry, or low mood show up, what helps you settle? Name the tools you really use, even the imperfect ones.",
      strength_msg: "Strong bark means you have real tools for hard feelings. That's a skill, and it will keep helping you long after high school.",
      growth_steps: [
        "Pick one calming practice and use it daily for two weeks, even on good days, so it's ready when you need it.",
        "If low mood or worry has lasted two weeks or more, tell a parent, counselor, or doctor. It's common, and help works.",
        "Write your own safety plan, and share it with one trusted adult."
      ] },
    { key: 'trunk', name: 'Purpose', color: 'var(--p-trunk)', group: 'root',
      prompt: "What do you care about, and what are you working toward? Purpose can live in school, a sport, a job, art, faith, family, or helping others.",
      strength_msg: "A strong sense of purpose gives your days direction. It helps you make choices that fit who you're becoming.",
      growth_steps: [
        "Write what you care about, what you're working toward, and who it helps.",
        "Give one hour this month where you're needed.",
        "Add one goal or plan to Next Steps."
      ] },
    { key: 'fruit', name: 'Hope', color: 'var(--p-fruit)', group: 'branch',
      prompt: "What are you looking forward to, this week and down the road? Hope can be small: a weekend plan, a goal, a person you'll see.",
      strength_msg: "Strong hope means you can see a way forward, even on hard days. Other people likely lean on that more than you know.",
      growth_steps: [
        "Plan one small good thing to look forward to this week.",
        "Write three good things each night for a week.",
        "Map one goal, a few paths to it, and the first step."
      ] },
    { key: 'leaves', name: 'Body', color: 'var(--p-leaves)', group: 'branch',
      prompt: "How are you sleeping, moving, and eating? Listening to your body counts more than being perfect.",
      strength_msg: "Strong leaves mean you're listening to your body and giving it what it needs. That makes every other part of you easier to tend.",
      growth_steps: [
        "Move most days in a way you enjoy, building toward 60 minutes.",
        "Charge your phone outside your room, and aim for 8 to 10 hours of sleep.",
        "Eat breakfast and pack a snack and water for after school."
      ] },
    { key: 'branches', name: 'Relationships', color: 'var(--p-branches)', group: 'branch',
      prompt: "Who has your back, and who do you show up for? Name the real people: family, friends, coaches, teachers, mentors, teammates, your faith community.",
      strength_msg: "Strong branches mean you're not carrying life alone. Friends and trusted adults are some of the most protective things you can have.",
      growth_steps: [
        "Name one trusted adult besides your parents, and reach out to them this week.",
        "Make an in-person plan with a friend.",
        "Write and read a gratitude letter to someone who helped you."
      ] }
  ];

  // Plain wording for the parts (only Roots changes).
  const PLAIN_PARTS = {
    roots: {
      prompt: "What steadies you when life gets loud? Family traditions, quiet, music, time outside, or the values you live by all count. Questions are welcome here.",
      strength_msg: "Strong roots mean you have something to hold on to when things get shaky. That's worth tending on purpose, even on good weeks.",
      growth_steps: [
        "Pick one practice that steadies you, quiet time, music, or a walk outside, and do it three times this week.",
        "Write down one big question you carry, and talk about it with someone you trust.",
        "List the people, places, and practices that hold you up, and keep the list where you'll see it."
      ] }
  };

  // ---------------- BUILD OAK'S SHAPES ----------------
  const DOMAIN_DEFS = [], GUIDES = {}, G = {}, META = {}, NEW = {}, FLAGS = {}, SOURCES = {}, PLAIN = {};
  PARTS.forEach(pt => {
    const rows = ROWS.filter(r => r.p === pt.key);
    DOMAIN_DEFS.push({
      key: pt.key, name: pt.name, color: pt.color, group: pt.group, prompt: pt.prompt,
      restore: rows.filter(r => r.b).map(r => [r.n, r.d]),
      strength_msg: pt.strength_msg, growth_steps: pt.growth_steps.slice()
    });
    NEW[pt.key] = rows.filter(r => !r.b).map(r => [r.n, r.d]);
    META[pt.key] = {};
    rows.forEach(r => {
      const id = pt.key + '|' + r.n;
      (r.b ? GUIDES : G)[id] = Object.assign({}, r.g);
      META[pt.key][r.n] = r.m.slice();
      if (r.f && Object.keys(r.f).length) FLAGS[id] = Object.assign({}, r.f);
      if (r.s && r.s.length) SOURCES[id] = r.s.slice();
      if (r.plain) PLAIN[id] = { n: r.plain.n, d: r.plain.d, g: Object.assign({}, r.g, r.plain.g, { vary: '' }) };
    });
  });

  // ---------------- RESOURCE SHELF ----------------
  const SHELF = {
    roots: [
      ['The Ignatian Examen', 'https://www.jesuits.org/spirituality/the-ignatian-examen/', 'The five steps of the daily examen.'],
      ['Contemplative Outreach', 'https://www.contemplativeoutreach.org/', 'Centering prayer and lectio divina, with guides.'],
      ['Awe Walk, Greater Good in Action', 'https://ggia.berkeley.edu/practice/awe_walk', 'A research-informed awe practice.'],
      ['A youth leader, chaplain, or faith mentor', '', 'Ask at your faith community, or ask a parent to help you find one.']
    ],
    trunk: [
      ['CareerOneStop', 'https://www.careeronestop.org/', 'Explore careers, training, and apprenticeships (US Department of Labor).'],
      ['Your school counselor', '', 'Help with classes, college, careers, the military, and plans after high school.'],
      ['Next Steps, in Pine', '', 'Your private notebook for goals, values, and plans after high school.']
    ],
    bark: [
      ['988 Suicide and Crisis Lifeline', 'https://988lifeline.org/', 'Call or text 988, or chat online, any time.'],
      ['Crisis Text Line', 'https://www.crisistextline.org/text-us/', 'Text HOME to 741741, any time. In Minnesota, text MN to 741741.'],
      ['Minnesota county crisis teams', 'https://www.mnmhaccess.com/Home/Crisis', 'Call **CRISIS (274747) from a cell phone, any time.'],
      ['Teen Line', 'https://didihirsch.org/teenline/hotline-support/', 'Teens answering teens. Call 800-852-8336, 8 p.m. to midnight Central, or text TEEN to 839863.'],
      ['Self-compassion practices', 'https://self-compassion.org/', 'Guided practices from Kristin Neff.']
    ],
    branches: [
      ['Love Is Respect', 'https://www.loveisrespect.org/get-relationship-help-24-7-365/', 'Dating relationships. Call 1-866-331-9474, or text LOVEIS to 22522, any time.'],
      ['Childhelp National Child Abuse Hotline', 'https://childhelphotline.org/', 'Call or text 1-800-422-4453, any time, if someone is hurting you.'],
      ['Day One (Minnesota)', 'https://dayoneservices.org/domestic-violence/help-now/', '1-866-223-1111, or text 612-399-9995, any time.'],
      ['Take It Down', 'https://takeitdown.ncmec.org', 'If someone has or is threatening to share a picture of you from under 18. You are not in trouble.']
    ],
    leaves: [
      ['Physical activity for teens, CDC', 'https://www.cdc.gov/physical-activity-education/guidelines/index.html', 'About 60 minutes a day, with strength on three days.'],
      ['How much sleep teens need, AASM', 'https://aasm.org/resources/pdf/pediatricsleepdurationconsensus.pdf', '8 to 10 hours for ages 13 to 18.'],
      ['ANAD Eating Disorders Helpline', 'https://anad.org/get-support/eating-disorders-helpline/', '1-888-375-7767, Monday to Friday, 9 a.m. to 9 p.m. Central.'],
      ['SAMHSA National Helpline', 'https://www.samhsa.gov/find-help/helplines/national-helpline', '1-800-662-4357, any time, for substance use questions.']
    ],
    fruit: [
      ['988 Suicide and Crisis Lifeline', 'https://988lifeline.org/', 'Call or text 988, or chat online, any time.'],
      ['Crisis Text Line', 'https://www.crisistextline.org/text-us/', 'Text HOME to 741741, any time.'],
      ['Gratitude Letter, Greater Good in Action', 'https://ggia.berkeley.edu/practice/gratitude_letter', 'A research-informed gratitude practice.']
    ]
  };
  const PLAIN_SHELF = {
    roots: [
      ['Awe Walk, Greater Good in Action', 'https://ggia.berkeley.edu/practice/awe_walk', 'A research-informed awe practice.'],
      ['A mentor you trust', '', 'A coach, teacher, relative, or counselor who listens well.']
    ]
  };

  window.PINE_PRACTICES = { DOMAIN_DEFS, GUIDES, G, META, NEW, EV, DISC, SRC, SHELF, FLAGS, SOURCES, PLAIN, PLAIN_PARTS, PLAIN_SHELF };
})();
