/* =====================================================================
   BEFORE THE VOWS: the questions (before-the-vows/questions.js)   GWG BLD 750, October 2026
   An original couple's check-in in 12 areas. Every question is written fresh in Grounded's voice.
   Nothing here comes from PREPARE/ENRICH, SYMBIS, FOCCUS, RELATE, or any licensed inventory.
   The areas follow the premarital education research: background, each person's habits, and how
   the two of them talk and repair (Larson and Holman 1994; Halford, Markman, Kline, and Stanley 2003).

   Shape (the BLD 750 contract):
   areas: {id, name, lead, faith?, src} (src: the source ids behind that area's why lines)
   questions: {id, area, text, plain? (Plain wording on faith items), rev? (reverse worded), talk, why}
   safety: private questions that stay with the one who answered and never go on the card.
   differ: answers 2 or more apart, or one agrees while the other disagrees, go on Talk About This.
   ===================================================================== */
window.BTV_Q = {
  version: 1,
  scale: [[1, "Strongly disagree"], [2, "Disagree"], [3, "Not sure"], [4, "Agree"], [5, "Strongly agree"]],
  differ: 2,
  sources: ["stanley06", "larson94", "halford03", "gottman98", "markman10", "dew12", "karney95", "mahoney10", "rcope", "stanley06sd"],

  areas: [
    { id: "talk", name: "Talking and Listening", lead: "How the two of you share what matters, big and small.", src: ["larson94", "markman10"] },
    { id: "repair", name: "Conflict and Repair", lead: "Every couple disagrees. What counts is how you come back together.", src: ["gottman98", "markman10"] },
    { id: "money", name: "Money", lead: "Spending, saving, and the feelings that come with both.", src: ["dew12"] },
    { id: "family", name: "Families and In-Laws", lead: "The families you come from and the family you are starting.", src: ["larson94"] },
    { id: "home", name: "Home and Roles", lead: "Who does what, and how it feels fair to both of you.", src: ["larson94"] },
    { id: "expect", name: "Hopes and Expectations", lead: "The pictures of married life you each carry, said out loud.", src: ["larson94", "halford03"] },
    { id: "close", name: "Affection and Closeness", lead: "Warmth, touch, and feeling close, day to day and over the years.", src: ["gottman98"] },
    { id: "kids", name: "Children and Parenting", lead: "Whether, when, and how you hope to raise a family.", src: ["larson94"] },
    { id: "faith", name: "Faith and Meaning", lead: "What gives your life meaning, and how you hope to share it.", faith: true, src: ["mahoney10", "rcope"] },
    { id: "fun", name: "Friends and Fun", lead: "Time together, time apart, and the people you love.", src: ["markman10"] },
    { id: "health", name: "Health and Stress", lead: "How you each handle hard days, habits, and well-being.", src: ["karney95"] },
    { id: "dreams", name: "Dreams and Commitment", lead: "Where you are headed together, and what keeps you steady.", src: ["stanley06", "stanley06sd", "markman10"] }
  ],

  questions: [
    // Talking and Listening
    { id: "talk1", area: "talk", text: "I can tell my partner what I really feel, even when it is hard to say.",
      talk: "Ask each other what makes some feelings harder to say. Pick one small thing that would make it easier, like a set time to talk or a gentler start.",
      why: "Feeling able to speak openly is one of the strongest early signs of a lasting marriage." },
    { id: "talk2", area: "talk", text: "When I talk, my partner listens without jumping in to fix it or argue.",
      talk: "Take turns sharing a small worry for two minutes while the other only listens and then says back what they heard. Talk about how that felt.",
      why: "Being heard before being answered keeps hard talks calm and helps both people feel respected." },
    { id: "talk3", area: "talk", text: "We often end up talking past each other.", rev: true,
      talk: "Think of a recent talk that went sideways. Each of you say what you were trying to get across, and what you heard instead.",
      why: "Noticing misunderstandings early keeps small gaps from turning into old hurts." },
    { id: "talk4", area: "talk", text: "I know how my partner likes to be comforted after a hard day.",
      talk: "Each of you name one thing that helps after a hard day, and one thing that does not. Write them down where you will see them.",
      why: "Knowing how to support each other turns ordinary days into a steady source of closeness." },
    { id: "talk5", area: "talk", text: "We make time to really talk, not only about schedules and errands.",
      talk: "Choose a simple habit for real talk, like a walk after dinner or ten minutes before bed, and try it for two weeks.",
      why: "Regular, unhurried conversation keeps a couple close as life fills up." },
    { id: "talk6", area: "talk", text: "Some topics feel off limits between us.", rev: true,
      talk: "Without going into the topic yet, each of you name whether there is one that feels hard to bring up. Agree on when and how you could start it gently.",
      why: "Topics that are never raised tend to grow heavier; naming them safely is a skill couples can learn." },
    { id: "talk7", area: "talk", text: "My partner understands me when I explain what I need.",
      talk: "Each of you say one need you have tried to explain lately. The other says it back in their own words until it feels right.",
      why: "Feeling understood is close to the heart of feeling loved." },

    // Conflict and Repair
    { id: "repair1", area: "repair", text: "When we disagree, we can stay respectful, even when we are upset.",
      talk: "Talk about what respect sounds like to each of you in an argument. Name one thing that crosses a line for you.",
      why: "Research on newlyweds finds that harshness and contempt during conflict predict later unhappiness, while warmth during conflict predicts a stronger marriage." },
    { id: "repair2", area: "repair", text: "After an argument, one of us usually reaches out to make things right.",
      talk: "Share what a good repair looks like to you: an apology, a hug, a joke, a walk. Decide who reaches out first when you both feel stuck.",
      why: "Couples who repair well after conflict tend to stay happier, even when they argue often." },
    { id: "repair3", area: "repair", text: "Our arguments tend to get louder and meaner the longer they go.", rev: true,
      talk: "Agree on a word either of you can say to pause a heated talk, and a time to come back to it within a day.",
      why: "Taking a short break and coming back is one of the most helpful skills couples learn in relationship education." },
    { id: "repair4", area: "repair", text: "My partner is open to my point of view, even when we disagree.",
      talk: "Pick a small disagreement. Each of you say the best part of the other's view before saying your own.",
      why: "Being willing to be influenced by each other is linked with lasting marriages in long-term studies." },
    { id: "repair5", area: "repair", text: "One of us tends to shut down or walk away when things get tense.", rev: true,
      talk: "Talk about what happens inside you when things get tense. Agree on how to take a break that the other can trust, with a time to return.",
      why: "Shutting down feels like protection to one partner and like rejection to the other; naming it helps both." },
    { id: "repair6", area: "repair", text: "We can solve problems together and both feel good about the plan.",
      talk: "Choose one small, real problem. Brainstorm ideas together without judging, then pick one to try for a week.",
      why: "Problem solving works best after both people feel heard, a step couples can practice." },
    { id: "repair7", area: "repair", text: "I can say I am sorry to my partner without it feeling like losing.",
      talk: "Talk about how apologies worked in the homes you grew up in, and what you want them to look like in yours.",
      why: "A sincere apology is one of the fastest ways back to each other." },
    { id: "repair8", area: "repair", text: "Old arguments keep coming back between us.", rev: true,
      talk: "Name one argument that keeps returning. Ask what deeper need sits under it for each of you, such as feeling respected, safe, or valued.",
      why: "Many recurring disagreements are about deeper needs; couples do well when they learn to talk about them kindly." },

    // Money
    { id: "money1", area: "money", text: "We have talked openly about how much each of us earns, owes, and saves.",
      talk: "Set a calm time to share the numbers: income, debts, savings, and credit. Agree that the goal is a clear picture, with no blame.",
      why: "In a large national study, disagreements about money predicted divorce more strongly than other kinds of disagreement, so clear talk early protects you both." },
    { id: "money2", area: "money", text: "We agree on how we will handle our money: joined, separate, or some of each.",
      talk: "Each of you describe what feels fair and safe to you. Try a plan for a few months and agree on a date to check how it is going.",
      why: "A shared plan for money lowers stress and helps both people feel like partners." },
    { id: "money3", area: "money", text: "My partner's spending habits worry me.", rev: true,
      talk: "Each of you name one spending habit you are proud of and one you would like to change. Talk about what money meant in the homes you grew up in.",
      why: "Money habits often carry family history; understanding it makes room for kindness." },
    { id: "money4", area: "money", text: "We agree on how much to save and how much to enjoy now.",
      talk: "Make two short lists together: what you want to save for, and what you want to enjoy now. Find one step toward each.",
      why: "Agreeing on goals turns money from a fight into a shared project." },
    { id: "money5", area: "money", text: "I would feel comfortable checking with my partner before a large purchase.",
      talk: "Agree on a dollar amount where you check with each other first. Talk about why that number feels right.",
      why: "Simple agreements about large purchases prevent many money arguments." },
    { id: "money6", area: "money", text: "Talking about money with my partner usually turns tense.", rev: true,
      talk: "Plan a short monthly money talk with a clear start and end. Begin with one thing that went well that month.",
      why: "How a couple talks about money matters as much as how much money they have." },
    { id: "money7", area: "money", text: "We have talked about giving, helping family, and debts we may share.",
      talk: "Talk about whether you hope to give to causes, help family members, or pay off debts together, and how much feels right.",
      why: "Unspoken expectations about giving and family help can surprise couples later." },

    // Families and In-Laws
    { id: "family1", area: "family", text: "I feel welcomed by my partner's family.",
      talk: "Share what makes you feel welcome or left out at family times. Ask your partner for one thing that would help.",
      why: "Good ties with each other's families support a marriage, and strain with them is a common source of stress." },
    { id: "family2", area: "family", text: "We agree on how much our families will be part of our decisions.",
      talk: "Talk about which choices are just for the two of you, and where family input is welcome.",
      why: "A new marriage does best when the couple decides together where family fits." },
    { id: "family3", area: "family", text: "I worry that my partner puts their family's wishes ahead of mine.", rev: true,
      talk: "Name one recent time this came up. Talk about how you can stand together, even when a parent or sibling disagrees.",
      why: "Feeling like a team in front of family builds trust between partners." },
    { id: "family4", area: "family", text: "We have talked about how we will spend holidays and special days.",
      talk: "List the holidays and traditions that matter most to each of you. Sketch a plan for the first year that honors both families.",
      why: "Holidays are a frequent source of family tension; a plan made together eases it." },
    { id: "family5", area: "family", text: "I understand how my partner's growing up shapes who they are today.",
      talk: "Each of you share one thing from your growing up you want to carry forward and one you want to do differently.",
      why: "Family background is one of three main areas research links with how a marriage goes." },
    { id: "family6", area: "family", text: "There are family conflicts we have not talked through yet.", rev: true,
      talk: "Name any family conflict that might affect your marriage. Talk about how each of you will handle it, and how you will back each other up.",
      why: "Talking through family tension before the wedding helps couples meet it as a team." },
    { id: "family7", area: "family", text: "We agree on how often we will visit or see our families.",
      talk: "Talk about what feels like too little, enough, and too much time with family, and find a middle you can both try.",
      why: "Clear, shared expectations about family time prevent quiet resentment." },

    // Home and Roles
    { id: "home1", area: "home", text: "We have talked about who will do which chores at home.",
      talk: "Write down the weekly chores together and divide them in a way that fits your schedules and strengths. Plan to look again in a month.",
      why: "When the work at home feels shared, both partners have more energy for each other." },
    { id: "home2", area: "home", text: "The way we split work at home feels fair to me.",
      talk: "Each of you say what fair looks like to you. Fair does not have to mean equal; talk about what feels right for both.",
      why: "A sense of fairness matters more to many couples than an exact split." },
    { id: "home3", area: "home", text: "I expect to do more than my share at home.", rev: true,
      talk: "Talk honestly about where this worry comes from. Agree on one change that would help balance things.",
      why: "Expecting to carry too much can quietly build resentment; naming it early helps." },
    { id: "home4", area: "home", text: "We agree on how we will make big decisions, like where to live or a job change.",
      talk: "Talk about a big decision you might face in the next few years. How would you decide it together?",
      why: "Deciding big things together helps both partners feel respected." },
    { id: "home5", area: "home", text: "We agree on how tidy or relaxed we want our home to be.",
      talk: "Each of you describe a home that feels restful. Find a few shared standards and leave room for each person's space.",
      why: "Small daily differences add up; a shared standard saves many little arguments." },
    { id: "home6", area: "home", text: "Our work schedules leave enough time for our life at home.",
      talk: "Map out a typical week for each of you. Look for two times each week that belong to the two of you.",
      why: "Work stress spills into home life; protecting shared time helps a marriage weather it." },
    { id: "home7", area: "home", text: "I sometimes feel my partner expects me to fill a role I did not choose.", rev: true,
      talk: "Talk about the roles you each saw growing up. Say which ones you want and which you would rather share or set aside.",
      why: "Unspoken expectations about roles are a common source of early marriage tension." },

    // Hopes and Expectations
    { id: "expect1", area: "expect", text: "I have a clear picture of what everyday married life will be like for us.",
      talk: "Each of you describe an ordinary Tuesday five years from now. Notice where your pictures match and where they differ.",
      why: "Talking through expectations is one of the core parts of strong relationship education." },
    { id: "expect2", area: "expect", text: "I expect marriage to fix some of the problems we have now.", rev: true,
      talk: "Name one thing you hope will change after the wedding. Talk about what you could start doing now to work on it together.",
      why: "Marriage brings joy and change, but the habits couples bring into it tend to continue." },
    { id: "expect3", area: "expect", text: "We have talked about where we hope to live in the years ahead.",
      talk: "Share your hopes about city or country, near family or far, renting or owning. Find what matters most to each of you.",
      why: "Where a couple lives shapes work, family ties, and daily life." },
    { id: "expect4", area: "expect", text: "I know what my partner expects of me in our marriage.",
      talk: "Each of you name three things you hope your partner will be for you. Talk about which feel easy and which feel like a stretch.",
      why: "Clear, spoken expectations help partners meet each other well." },
    { id: "expect5", area: "expect", text: "There are things about my partner I am hoping will change after we marry.", rev: true,
      talk: "Talk gently about one of these. Ask whether it is something your partner wants to change, or something you can accept.",
      why: "Accepting each other as you are, while growing together, makes room for real change." },
    { id: "expect6", area: "expect", text: "We have talked about how each of our careers fit into our future.",
      talk: "Share your work hopes for the next five years. Talk about how you would handle a move, a school program, or a job change.",
      why: "Career plans touch money, time, and where you live, so they belong in early conversations." },
    { id: "expect7", area: "expect", text: "We have talked about what we would do if our marriage hit a hard season.",
      talk: "Agree now on what you would do if things got hard: who you would talk to, and that you would reach out for help early.",
      why: "A plan made in calm times is easier to follow in hard ones." },

    // Affection and Closeness
    { id: "close1", area: "close", text: "I feel loved and wanted by my partner.",
      talk: "Each of you share the moments when you feel most loved. Ask for one more of those this week.",
      why: "Everyday warmth and fondness are among the strongest signs of a lasting marriage." },
    { id: "close2", area: "close", text: "We show each other affection in ways that feel good to both of us.",
      talk: "Talk about the ways each of you likes to show and receive affection: words, touch, time, help, or small gifts.",
      why: "Partners often show love the way they hope to receive it; learning each other's way builds closeness." },
    { id: "close3", area: "close", text: "I feel comfortable talking with my partner about our physical closeness.",
      talk: "Choose a calm, private time. Each of you share one hope and one worry about physical closeness in your marriage.",
      why: "Being able to talk about closeness openly helps couples grow together over the years." },
    { id: "close4", area: "close", text: "Our hopes about physical closeness may be quite different.", rev: true,
      talk: "Talk kindly about what closeness means to each of you and how often feels right. Look for ways to meet each other with respect.",
      why: "Different hopes are common; couples who talk about them with respect tend to feel closer." },
    { id: "close5", area: "close", text: "I feel emotionally close to my partner most days.",
      talk: "Share what helps you feel close, like a good morning text, a shared meal, or a few minutes of real talk.",
      why: "Small daily moments of turning toward each other build a strong bond." },
    { id: "close6", area: "close", text: "Sometimes I feel more like a roommate than a partner.", rev: true,
      talk: "Talk about when you last felt close and what was different then. Plan one evening together that brings some of that back.",
      why: "Noticing distance early makes it easier to turn back toward each other." },
    { id: "close7", area: "close", text: "My partner often notices and thanks me for the things I do.",
      talk: "Each of you name three things you appreciate about the other from this week, and say them out loud.",
      why: "Regular thanks and appreciation help couples stay warm through stressful seasons." },

    // Children and Parenting
    { id: "kids1", area: "kids", text: "We agree on whether we hope to have children.",
      talk: "Share your hopes honestly, including any uncertainty. Talk about how you would decide together if your hopes shift over time.",
      why: "Plans about children are among the most important things for a couple to talk through before marriage." },
    { id: "kids2", area: "kids", text: "We agree on how many children we hope for and when.",
      talk: "Each of you share a number and a timing that feels right, and why. Talk about what would happen if life did not go to plan.",
      why: "Timing touches money, work, and health, so shared plans help." },
    { id: "kids3", area: "kids", text: "We would handle discipline very differently.", rev: true,
      talk: "Talk about how you were guided and corrected growing up. Name what you want to keep and what you want to do differently.",
      why: "Parents who agree on their approach give children a steady home." },
    { id: "kids4", area: "kids", text: "We have talked about how we would cope if having children is harder than we hope.",
      talk: "Talk gently about adoption, fostering, or other paths, and how you would support each other through disappointment.",
      why: "Talking about hard possibilities ahead of time helps couples face them together." },
    { id: "kids5", area: "kids", text: "We have talked about the kind of parents we each hope to be.",
      talk: "Each of you describe a parent you admire and what you would borrow from them. If either of you already has children, talk about how your family will grow together.",
      why: "A shared picture of parenting helps a couple work as a team when the time comes." },
    { id: "kids6", area: "kids", text: "I worry that children would pull us apart.", rev: true,
      talk: "Talk about what keeps a couple close when children arrive, such as time alone and sharing the work.",
      why: "A new baby brings big changes; planning ahead helps a couple stay close through them." },
    { id: "kids7", area: "kids", text: "We have talked about how we would share the work of raising children.",
      talk: "Talk about nights, feeding, school, and time off work. Sketch a plan you could adjust as you go.",
      why: "Sharing the work of parenting helps both parents feel like partners." },

    // Faith and Meaning (Faith and Plain wording for every item)
    { id: "faith1", area: "faith", text: "My faith gives me strength, and I hope it can strengthen our marriage.",
      plain: "What gives my life meaning gives me strength, and I hope it can strengthen our marriage.",
      talk: "Share what has given you strength in hard times. Talk about how you can make room for it in your life together.",
      why: "For many couples, shared meaning and practice are a real source of strength, and research on faith and families finds this too." },
    { id: "faith2", area: "faith", text: "We agree on how faith practices like worship, prayer, or study will fit into our life.",
      plain: "We agree on how practices that matter to us, like quiet time, service, or traditions, will fit into our life.",
      talk: "Each of you describe what a good week looks like in this part of life. Find what you can share and what each of you keeps as your own.",
      why: "Shared practices give a couple a rhythm and a sense of purpose." },
    { id: "faith3", area: "faith", text: "Differences in how we practice our faith cause tension between us.",
      plain: "Differences in what we each find meaningful cause tension between us.", rev: true,
      talk: "Talk about where the tension shows up and what each of you needs to feel respected. Look for what you share underneath the differences.",
      why: "Faith or meaning can be a strength or a strain in a marriage; talking openly helps it stay a strength." },
    { id: "faith4", area: "faith", text: "I feel respected in my faith by my partner.",
      plain: "I feel respected by my partner in what matters most to me.",
      talk: "Each of you say what respect looks like in this part of life. Name one way your partner already shows it.",
      why: "Feeling respected in your deepest values helps a marriage feel safe." },
    { id: "faith5", area: "faith", text: "We have talked about how our faith will shape the way we raise any children.",
      plain: "We have talked about the values and traditions we hope to pass on to any children.",
      talk: "Share the traditions, values, and practices you hope children would grow up with. Talk about how to honor both of your backgrounds.",
      why: "Agreeing on what to pass on gives children a clear and steady home." },
    { id: "faith6", area: "faith", text: "I sometimes feel pressured by my partner or our families about faith.",
      plain: "I sometimes feel pressured by my partner or our families about what I should value.", rev: true,
      talk: "Talk about where the pressure comes from and what would help it ease. Agree on how you will answer family together.",
      why: "Pressure about faith or values can strain a marriage; a shared plan helps both feel respected and stand together." },
    { id: "faith7", area: "faith", text: "When life is hard, my faith helps me cope.",
      plain: "When life is hard, I have something deeper that helps me cope.",
      talk: "Share what has carried you through a hard season. Talk about how you can lean on it, and on each other, when hard times come.",
      why: "For many people, faith or meaning is a resource in hard times, and for some it can feel like a struggle; knowing which helps partners support each other." },
    { id: "faith8", area: "faith", text: "We have a faith community or place where we feel supported as a couple.",
      plain: "We have a community or group where we feel supported as a couple.",
      talk: "Talk about the people and places that support you. If you are looking, name one place to try together.",
      why: "Couples with a supportive community around them have more help to draw on." },

    // Friends and Fun
    { id: "fun1", area: "fun", text: "We enjoy spending time together and have fun as a couple.",
      talk: "Make a list of things you both enjoy and plan one for this week.",
      why: "Fun and friendship protect a marriage; couples who play together tend to stay close." },
    { id: "fun2", area: "fun", text: "We have regular time that is just for the two of us.",
      talk: "Pick a regular time for the two of you, even short, and protect it like any other appointment.",
      why: "Time set apart for each other keeps friendship strong in a busy life." },
    { id: "fun3", area: "fun", text: "I like my partner's friends and feel comfortable around them.",
      talk: "Share which friendships matter most to each of you. Talk about how to make room for them in your married life.",
      why: "Friends can be a strong support for a couple." },
    { id: "fun4", area: "fun", text: "I worry that my partner spends too much or too little time with friends.", rev: true,
      talk: "Talk about how much time with friends feels right to each of you. Agree on a balance you can try.",
      why: "Balance between time together and time with others helps both partners feel connected." },
    { id: "fun5", area: "fun", text: "We each have time for our own interests, and that feels good to both of us.",
      talk: "Each of you name an interest that refreshes you. Talk about how to make time for both.",
      why: "Having room to be yourself helps you bring your best to the marriage." },
    { id: "fun6", area: "fun", text: "Lately our time together is mostly errands and screens.", rev: true,
      talk: "Choose one evening each week without screens to talk, cook, walk, or play a game together.",
      why: "Shared time without distractions helps couples stay friends." },
    { id: "fun7", area: "fun", text: "We have friends who support our marriage.",
      talk: "Talk about the people who cheer you on as a couple. Think of one couple or friend you would like to spend more time with.",
      why: "Couples with supportive friends have more help through hard seasons." },

    // Health and Stress
    { id: "health1", area: "health", text: "We support each other well when one of us is stressed.",
      talk: "Each of you share what helps most when you are stressed. Agree on a simple signal for when you need extra support.",
      why: "Long-term research finds that how couples handle outside stress shapes how their marriage goes." },
    { id: "health2", area: "health", text: "I have concerns about my partner's use of alcohol, drugs, or gambling.", rev: true,
      talk: "Share your concerns calmly and with kindness. If either of you is worried, talk about who you could reach out to together.",
      why: "Alcohol, drugs, and gambling can strain trust and money; early, honest talk protects you both." },
    { id: "health3", area: "health", text: "We have talked openly about our health, including mental health.",
      talk: "Share any health needs the other should know about, and how the other can support you on hard days.",
      why: "Knowing each other's health needs helps partners support each other well." },
    { id: "health4", area: "health", text: "We have healthy ways to rest, unwind, and take a break.",
      talk: "Each of you name your favorite ways to rest. Look for one you can share and one you each keep.",
      why: "Rest and recovery help couples meet stress with patience." },
    { id: "health5", area: "health", text: "When I am stressed, I tend to take it out on my partner.", rev: true,
      talk: "Talk about how stress shows up in each of you. Agree on a gentle way to name it when it happens.",
      why: "Stress from outside often spills onto a partner; naming it helps protect the relationship." },
    { id: "health6", area: "health", text: "We agree on habits like sleep, food, and exercise that we want for our home.",
      talk: "Talk about one habit you would like to build together, like a shared walk or a regular bedtime.",
      why: "Healthy shared habits support both well-being and closeness." },
    { id: "health7", area: "health", text: "I know my partner would stand by me through a serious illness or loss.",
      talk: "Talk about what support would look like in a hard season like illness, grief, or job loss.",
      why: "Feeling secure in hard times is at the heart of commitment." },

    // Dreams and Commitment
    { id: "dreams1", area: "dreams", text: "I am sure I want to marry my partner.",
      talk: "If either of you feels unsure, that is worth a calm, honest talk. Share what feels certain and what still feels open.",
      why: "Choosing each other on purpose, rather than sliding into marriage, is linked with stronger commitment." },
    { id: "dreams2", area: "dreams", text: "We share dreams for the life we want to build.",
      talk: "Each of you share three dreams for the next ten years. Circle the ones you share and talk about how to honor the rest.",
      why: "Shared goals give a marriage direction and a sense of being a team." },
    { id: "dreams3", area: "dreams", text: "Sometimes I wonder if I am rushing into this marriage.", rev: true,
      talk: "Talk about what feels rushed and what would help you feel ready. It is fine to slow down a plan to get it right.",
      why: "Taking time to decide well is part of a strong start." },
    { id: "dreams4", area: "dreams", text: "I see our marriage as a lifelong commitment.",
      talk: "Talk about what commitment means to each of you, and what helps you keep choosing each other.",
      why: "A shared sense of a future together helps couples work through hard times." },
    { id: "dreams5", area: "dreams", text: "My partner supports my personal goals and dreams.",
      talk: "Each of you name one personal goal and one way your partner could help you reach it.",
      why: "Supporting each other's growth keeps both partners thriving." },
    { id: "dreams6", area: "dreams", text: "I can trust my partner to keep their word.",
      talk: "Talk about what builds trust for each of you. Name one promise you each want to keep this month.",
      why: "Trust grows from small promises kept day after day." },
    { id: "dreams7", area: "dreams", text: "I sometimes keep things from my partner that I think they should know.", rev: true,
      talk: "Talk about what makes sharing hard. Agree on how you will hear hard news from each other with calm and kindness.",
      why: "Honesty about important things is the ground trust stands on." },
    { id: "dreams8", area: "dreams", text: "We are ready to put real effort into our marriage, including learning new skills.",
      talk: "Talk about what you could learn together, from this check-in to a class or book, and plan one step.",
      why: "Couples who take part in premarital education report higher satisfaction and lower odds of divorce in a large national survey." }
  ],

  // Private questions: they stay with the one who answered and never go on the card.
  safety: {
    title: "Just for You",
    lead: "These few questions are only for you. Your answers stay on this device with you, and they never go on the card or to your partner. Answer only if you feel safe doing so right now.",
    items: [
      { id: "safe1", text: "At times I feel afraid of my partner." },
      { id: "safe2", text: "My partner pressures me into things I do not want to do, including sex or physical closeness." },
      { id: "safe3", text: "My partner checks up on my phone, money, friends, or where I go in ways that feel controlling." },
      { id: "safe4", text: "My partner puts me down, calls me names, or embarrasses me in front of others." },
      { id: "safe5", text: "My partner has pushed, grabbed, hit, or hurt me, or threatened to." },
      { id: "safe6", text: "There are times I do not feel able to say no to my partner." },
      { id: "safe7", text: "I feel pressured by my partner or my family to go through with this marriage." }
    ],
    yesLead: "Thank you for answering honestly. What you are feeling matters, and you deserve to feel safe and respected. You can talk with someone privately, any time, day or night. If you are in danger right now, call 911.",
    lines: [
      ["Love Is Respect", "Call 1-866-331-9474 or text LOVEIS to 22522"],
      ["National Domestic Violence Hotline", "Call 1-800-799-7233 or text START to 88788"],
      ["Day One (Minnesota)", "Call 1-866-223-1111"],
      ["988 Suicide and Crisis Lifeline", "Call or text 988"],
      ["Emergency", "Call 911"]
    ]
  }
};
