/* =====================================================================
   GROW WITH GROUNDED LEARN: lessons for the tree apps (shared/learn-lessons.js)
   Read by the Learn tab in Maple, Aspen, Oak, Willow, and The Grove (shared/gg-learn.js).
   Each app has tracks (series), each track has lessons, each lesson has scenes. Scene kinds and
   fields are listed at the top of gg-learn.js. A series of three or more lessons earns a
   Certificate of Completion when every lesson is finished (cert: false turns that off, cert: true
   turns it on for a shorter series). certTitle and certLine set the words on the certificate.
   Series grow deeper with the age and stage: short and simple in Maple, deepest in Willow.
   Started with one Start Here lesson per app (Learn build, October 2026); the full series plug in here.
   Willow Learn (October 2026): Support for Right Now (8 videos, kind: 'support'), For You (3), and
   For the People Who Love Them (6). From the Bedside scenes retell published Grounded stories (with a
   link) or unpublished ones with names and details changed (no link).
   Wording rules: no em dashes or en dashes, positive frames, Title Case for names of things.
   ===================================================================== */
window.GG_LEARN = {
  maple: {
    title: 'Learn Maple',
    intro: 'Short lessons to watch together, narrated aloud. Kids and grown-ups can watch side by side.',
    tracks: [
      { id: 'maple-start', title: 'Start Here', who: 'For kids and the grown-ups who help them', lessons: [
        { id: 'mp-welcome', n: 1, title: 'Welcome to Maple', mins: 2, scenes: [
          { k: 'title', hero: 'maple', eyebrow: 'Maple', h: 'Welcome to Maple', sub: 'Bright leaves, strong roots.', say: 'Welcome to Maple! Maple helps kids notice how they are growing, and helps the grown-ups who love them.' },
          { k: 'big', h: 'Every kid is growing like a tree.', sub: 'Six parts make a kid whole.', say: 'Every kid is growing like a tree. And a whole tree needs all six of its parts.' },
          { k: 'six', h: 'The six parts of your tree', words: ['Feeling safe, loved, and calm inside', 'What you love to do', 'Your feelings, and calming down', 'Friends and family', 'Moving, resting, eating well', 'Looking forward to good things'], say: 'Here are the six parts. Roots, what grounds you. Trunk, your purpose. Bark, your mind and feelings. Branches, the people in your life. Leaves, your body. And Fruit, your hope.' },
          { k: 'screen', app: 'maple', app_name: 'Maple', title: 'Check-in', rows: [['Roots', 'Sunny', '#C07A26'], ['Trunk', 'Sunny', '#C07A26'], ['Bark', 'Partly cloudy', '#7D6B57'], ['Branches', 'Sunny', '#C07A26'], ['Leaves', 'Rainy', '#3D5A73'], ['Fruit', 'Sunny', '#C07A26']], tap: 4, panel: { h: 'Rainy days add rings too.', sub: 'Weather comes and goes.', items: ['Pick a practice for Leaves', 'Try it today', 'Watch your tree grow'] }, say: 'In a check-in, you answer a few questions for each part. Then each part gets its weather. Sunny, partly cloudy, or rainy. Rainy days are okay. Weather comes and goes.' },
          { k: 'flow', h: 'How Maple works', steps: [['Check in', 'A few questions for each part'], ['See the weather', 'Sunny, cloudy, or rainy'], ['Practice a little', 'One small thing each day'], ['Watch it grow', 'Rings, leaves, and critters']], say: 'Here is how Maple works. Check in. See the weather. Practice a little each day. And watch your tree grow, with new rings, new leaves, and critters who come to visit.' },
          { k: 'points', h: 'For grown-ups', items: [['Grown-up Guide', 'Tips for every question, in the Grown-up Guide tab'], ['When Life Changes', 'Guides for hard talks, from a pet dying to scary news'], ['Private by design', 'No account. Answers stay on this device.']], say: 'For grown-ups: the Grown-up Guide has a tip for every question. When Life Changes has guides for hard talks. And everything stays private, right on this device.' },
          { k: 'quiz', q: 'What does Maple help kids notice?', opts: ['How fast they can run', 'The six parts that make them whole', 'Their spelling scores'], right: 1, why: 'Maple helps kids notice and tend all six parts of their tree.', say: 'Quick question. What does Maple help kids notice?' }
        ] }
      ] }
    ]
  },
  aspen: {
    title: 'Learn Aspen',
    intro: 'Short lessons, narrated aloud. Watch on your own or with a grown-up, in any order.',
    tracks: [
      { id: 'aspen-start', title: 'Start Here', who: 'For students in grades 6 to 8, and their grown-ups', lessons: [
        { id: 'as-welcome', n: 1, title: 'Welcome to Aspen', mins: 2, scenes: [
          { k: 'title', hero: 'aspen', eyebrow: 'Aspen', h: 'Welcome to Aspen', sub: 'Rooted together.', say: 'Welcome to Aspen. Aspen is your tree for grades six to eight.' },
          { k: 'big', h: 'Every middle schooler is like an aspen: growing fast and putting down roots.', say: 'Every middle schooler is like an aspen: growing fast and putting down roots.' },
          { k: 'six', h: 'Six parts make you whole', words: ['What keeps you steady', 'Goals and trying new things', 'Naming feelings, asking for help', 'Friends, family, belonging', 'Sleep, movement, real meals', "Hope for what's ahead"], say: 'Your tree has six parts. Roots, Trunk, Bark, Branches, Leaves, and Fruit. Being whole means noticing all six.' },
          { k: 'levels', say: 'After a check-in, each part shows a level. Strong. Steady. Or Growing Edge. A Growing Edge is a part to tend, not a grade.' },
          { k: 'flow', h: 'How Aspen works', steps: [['Check in', 'Questions written for your grade'], ['See your levels', 'Tap Why for any question'], ['Tend each day', 'Practices fitted to you'], ['Grow your tree', 'A ring and leaves each check-in']], say: 'Here is how it works. Check in with questions written for your grade. See your levels. Tend a little each day, right in Aspen. And every check-in adds a growth ring and leaves to your tree.' },
          { k: 'points', h: 'Yours to keep', items: [['Private by design', 'No account. Answers stay on this device.'], ['The Grove', 'Your tree can stand with your family, and you choose what shows'], ['When Life Changes', 'Guides for the hard stuff, any time']], say: 'Aspen is yours. Your answers stay on this device. Your tree can stand in The Grove with your family, and you choose what shows. And When Life Changes has guides for the hard stuff, any time.' },
          { k: 'quiz', q: 'What does a Growing Edge mean?', opts: ['You failed that part', 'A part to tend, not a grade', 'You need to start over'], right: 1, why: 'A Growing Edge is simply the part that needs some care right now.', say: 'Quick question. What does a Growing Edge mean?' }
        ] }
      ] }
    ]
  },
  oak: {
    title: 'Learn Oak',
    intro: 'Short animated lessons, narrated aloud. Watch them in any order, as often as you like.',
    tracks: [
      { id: 'oak-start', title: 'Start Here', who: 'For adults tending their own tree', lessons: [
        { id: 'ok-welcome', n: 1, title: 'Welcome to Oak', mins: 2, scenes: [
          { k: 'title', hero: 'oak', eyebrow: 'Oak', h: 'Welcome to Oak', sub: 'Shelter for others. Strength for you.', say: 'Welcome to Oak. Oak is a check-in for the whole person, from root to fruit.' },
          { k: 'parts', say: 'You are made of six parts. Roots, what grounds you. Trunk, your purpose. Bark, your mind and feelings. Branches, your relationships. Leaves, your body. And Fruit, your hope.' },
          { k: 'big', h: 'Being whole means noticing and tending all six.', sub: 'Strength in one part can carry another for a while.', say: 'Being whole means noticing and tending all six. Strength in one part can carry another for a while, and the part that needs care deserves your attention too.' },
          { k: 'levels', say: 'Each part shows a level after a check-in. Strong, Steady, or Growing Edge. A Growing Edge is a part to tend, not a grade.' },
          { k: 'flow', h: 'How Oak works', steps: [['Check in', 'Eight questions for each part'], ['See your levels', 'Part by part'], ['Make a growth plan', 'Practices for your Growing Edge'], ['Tend today', 'Small steps, every day']], say: 'Here is how Oak works. Check in. See your levels, part by part. Make a growth plan with practices for your Growing Edge. Then tend a little, every day, in the Today tab.' },
          { k: 'points', h: 'Always here', items: [['When Life Changes', "Guides for more than 50 of life's hardest seasons"], ['Private by design', 'No account. Answers stay on this device.'], ['Need to talk now?', 'Call or text 988, any time.']], say: "When Life Changes has guides for more than fifty of life's hardest seasons. Everything stays private on this device. And if you ever need to talk right now, call or text nine eight eight, any time." },
          { k: 'quiz', q: 'Where does your daily tending happen?', opts: ['Only at your yearly check-in', 'In the Today tab, a little each day', 'Only with a chaplain'], right: 1, why: 'Oak is built for small steps every day, in the Today tab.', say: 'Quick question. Where does your daily tending happen?' }
        ] }
      ] }
    ]
  },
  willow: {
    title: 'Learn Willow',
    intro: 'Gentle videos, narrated aloud. Watch alone or together, whenever there is time. Pause anytime.',
    supportFirst: true,
    support: { eyebrow: 'Support', title: 'Support for Right Now', intro: 'Short videos for the hard hours. Open one anytime, as often as you need. Nothing to finish.' },
    lessonsTitle: 'Learn Step by Step',
    tracks: [
      /* ---------- Support for Right Now: no quiz, no certificate, gentle closing ---------- */
      { id: 'willow-support', kind: 'support', title: 'For the Hard Hours', who: 'For anyone sitting with someone near the end of life, and for the person themselves', lessons: [

        { id: 'wl-s-breathe', n: 1, title: 'Breathe at the Bedside', mins: 3, blurb: 'A slow breathing practice you can do right where you are.', scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Support for Right Now', h: 'Breathe at the Bedside', sub: 'Right where you are.', say: "Let's take a few minutes to breathe together. You don't need to go anywhere. You can do this right where you are, even in the chair beside the bed." },
          { k: 'points', h: 'Get settled', items: [['Feet on the floor', 'Feel the ground holding you up'], ['Hands open', 'In your lap, or holding their hand'], ['Eyes soft', 'Closed, or resting on one spot']], say: 'Put your feet flat on the floor and feel the ground holding you up. Let your hands rest open, in your lap, or holding their hand. Let your eyes close, or rest them on one spot.' },
          { k: 'big', h: 'A longer breath out tells your body it is safe.', sub: 'In for four. Out for six.', say: 'Here is the one thing to know. When your breath out is longer than your breath in, your body starts to settle. So we will breathe in for four, and out for six.' },
          { k: 'breathe', h: 'Breathe with the circle', sub: 'In as it grows. Out as it softens.', hold: 34, say: 'Follow the circle. Breathe in as it grows, two, three, four. And out as it softens, slowly, all the way out. Keep going on your own for a few breaths.' },
          { k: 'big', h: 'If your mind wanders, that is okay.', sub: 'Come back to the next breath.', say: 'If your mind wanders to the worries, that is okay. Notice it, and come back to the next breath. There is nothing to do right.' },
          { k: 'breathe', h: 'A few more', sub: 'You can breathe for them too.', hold: 30, say: 'A few more breaths. If the person you love is breathing hard, you can breathe slow and steady beside them. Sometimes a calm body in the room helps everyone.' },
          { k: 'big', h: 'You can come back to this anytime.', sub: 'Day or night.', say: 'That is all it takes. Come back to this anytime, day or night. And if anything about their breathing worries you, call your hospice. They are there around the clock.' }
        ] },

        { id: 'wl-s-say', n: 2, title: "When You Don't Know What to Say", mins: 2, blurb: 'Simple words that are always enough.', scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Support for Right Now', h: "When You Don't Know What to Say", sub: 'Simple words are enough.', say: "If you are standing at the bedside and the words won't come, this is for you. Simple words are enough." },
          { k: 'big', h: 'Your being there says the most.', say: 'First, the most important thing. Your being there already says the most. Holding a hand says, I am here, without a single word.' },
          { k: 'words', h: 'Words that are always enough', items: ["I'm here.", 'I love you.', 'Thank you.', "You don't have to talk. I'll sit with you."], say: "If you want words, these are always enough. I'm here. I love you. Thank you. You don't have to talk. I'll just sit with you." },
          { k: 'words', h: 'Four things many people want to say', items: ['Please forgive me.', 'I forgive you.', 'Thank you.', 'I love you.'], sub: 'Then, when it feels right: goodbye.', say: 'Many hospice teams teach four things people often want to say before a goodbye. Please forgive me. I forgive you. Thank you. I love you. And then, when it feels right, goodbye. Say the ones that are true for you.' },
          { k: 'words', h: 'Words that open a door', items: ['Tell me about the day we met.', 'What are you proudest of?', 'What do you want us to remember?', 'Is there anything you want me to do?'], say: 'If they are able to talk, a question can open a door. Tell me about the day we met. What are you proudest of. What do you want us to remember. Is there anything you want me to do.' },
          { k: 'big', h: 'Keep talking, even when they are quiet.', sub: 'Hearing may be one of the last senses to go.', say: 'If they can no longer answer, keep talking anyway. Hearing may be one of the last senses to go. Tell them who is in the room. Tell them what you want them to know.' },
          { k: 'big', h: 'If it comes out wrong, love covers it.', say: 'And if your words come out clumsy, or you cry in the middle, that is okay. Love covers it. They know what you mean.' }
        ] },

        { id: 'wl-s-ground', n: 3, title: 'Ground Yourself Right Now', mins: 2, blurb: 'Five senses to bring you back when everything is too much.', scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Support for Right Now', h: 'Ground Yourself Right Now', sub: 'Five senses, one breath at a time.', say: 'When everything feels like too much, your senses can bring you back to this moment. This takes about two minutes.' },
          { k: 'story', title: 'Grounded in Coffee', lines: ['On the way to a visit, a reckless driver cut me off. My coffee flew across the seat, and my whole body shook.', 'I had a few minutes before I needed to walk into a family\u2019s home calm. So I pulled over by a quiet field and named what my senses could find.', 'Four out of five senses came back coffee. I laughed out loud, and I was ready.'], lesson: 'Your senses can bring you home to this moment.', note: 'From a Grounded story by Chris Joy', link: { href: 'https://chri5j0y.substack.com/p/grounded-in-coffee', label: 'Read the Full Story: Grounded in Coffee' }, say: "Chris, the chaplain behind Grow With Grounded, tells about a morning when a reckless driver cut him off and sent his coffee flying. He had only a few minutes before he needed to walk into a family's home calm. So he pulled over and named what his senses could find. Four out of five came back coffee. He laughed, and he was ready." },
          { k: 'points', h: 'Five, four, three, two, one', items: [['5 things you can see', 'Look slowly around the room'], ['4 things you can feel', 'The chair, your feet, your clothes, their hand'], ['3 things you can hear', 'Near and far'], ['2 things you can smell', 'Or two smells you like'], ['1 thing you can taste', 'Or one sip of water']], gap: 2.4, say: 'Let us do it together. Name five things you can see. Now four things you can feel. The chair under you. Your feet on the floor. Three things you can hear. Two things you can smell. And one thing you can taste.' },
          { k: 'breathe', h: 'One slow breath to finish', hold: 12, say: 'Now one slow breath. In for four. And out for six.' },
          { k: 'big', h: 'You are here. That is enough for right now.', say: 'You are here, in this moment. That is enough for right now. Come back to this whenever you need it.' }
        ] },

        { id: 'wl-s-before', n: 4, title: 'Grief Before the Goodbye', mins: 2, blurb: 'Why you may be grieving already, and what helps.', scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Support for Right Now', h: 'Grief Before the Goodbye', sub: 'It has a name.', say: 'If you are grieving someone who is still here, you are not alone, and you are not doing anything wrong. It has a name.' },
          { k: 'big', h: 'Anticipatory grief', sub: 'Grieving a loss as you watch it coming.', say: 'It is called anticipatory grief. It is the grief of watching a loss come, a little at a time. Many families feel it for weeks or months before a death.' },
          { k: 'points', h: 'It can look like', items: [['Sadness that comes in waves', 'Strong one hour, gone the next'], ['Tired all the way through', 'Even after sleep'], ['Feeling numb', 'Or far away from it all'], ['Wishing it were over', 'And feeling guilty for it']], say: 'It can look like sadness that comes in waves. Being tired all the way through. Feeling numb. And sometimes wishing it were over, then feeling guilty for wishing it. All of these are common. All of them come from love.' },
          { k: 'flow', h: 'Notice. Name. Express. Unpack.', steps: [['Notice it', 'Something is there'], ['Name it', 'Sad, scared, angry, tired'], ['Express it', 'Talk, write, cry'], ['Unpack it', 'Walk, stretch, breathe']], say: 'Here is a simple way to move through it. Notice it. Name it, as clearly as you can. Express it, by talking, writing, or crying. Then unpack it with your body. Walk, stretch, breathe.' },
          { k: 'big', h: 'You can grieve and still be fully present.', sub: 'Both are love.', say: 'Grieving now does not mean giving up. You can grieve and still be fully present. Both are love. And your hospice has people who can talk with you about it, now and after.' }
        ] },

        { id: 'wl-s-vigil', n: 5, title: 'The Vigil Hours', mins: 2, blurb: 'Sitting with someone in their last hours or days.', scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Support for Right Now', h: 'The Vigil Hours', sub: 'Keeping watch, with love.', say: 'When someone is in their last hours or days, families often keep watch at the bedside. This is called a vigil. Here is what can help.' },
          { k: 'points', h: 'Make the room theirs', items: [['Their music', 'Softly, the songs they love'], ['Their words', 'Prayers, readings, or poems from their life'], ['Soft light', 'A lamp instead of overhead lights'], ['Familiar things', 'A blanket, a photo, a smell from home']], say: 'Make the room theirs. Their music, played softly. Prayers, readings, or poems from their life. A lamp instead of bright overhead lights. Familiar things, like a favorite blanket or photo.' },
          { k: 'story', title: 'Drift Away', lines: ['Suzan had not spoken or opened her eyes in three days.', 'Then her family played a song she loved. Under the sheet, her toes began to move to the beat. She lifted her chin and smiled wider than I had ever seen a dying person smile.', 'She never woke again. She drifted away peacefully a short time later.'], lesson: 'Music can reach a person when words cannot.', note: 'From a Grounded story by Chris Joy', link: { href: 'https://chri5j0y.substack.com/p/drift-away', label: 'Read the Full Story: Drift Away' }, say: "Chris tells about Suzan, who had not spoken in three days. Then a song she loved came on, and under the sheet, her toes began to move to the beat. She lifted her chin and smiled. She drifted away peacefully a short time later. Music can reach a person when words cannot." },
          { k: 'points', h: 'Take turns', items: [['Shifts, not marathons', 'Two to four hours, then rest'], ['Eat and sleep', 'They would want that for you'], ['Write it down', 'What Helped Today, for the next person'], ['Call the hospice', 'For any change that worries you']], say: 'Take turns. Shifts work better than marathons. Eat, and sleep when you can. They would want that for you. Use What Helped Today in Willow, so the next person knows what brought comfort. And call your hospice for any change that worries you.' },
          { k: 'big', h: 'If they die while you stepped out, it is not your fault.', sub: 'Some people seem to wait until loved ones leave the room.', say: 'One more thing, and it matters. Some people die in the few minutes when everyone has stepped out. Bedside workers see it often. If that happens, it is not your fault. You were there for so much of it, and that is what they knew.' },
          { k: 'big', h: 'You are keeping watch with love.', say: 'You are keeping watch with love. That is a holy thing to do, whatever your faith. Take all the time you need.' }
        ] },

        { id: 'wl-s-after', n: 6, title: 'The First Hour After', mins: 2, blurb: 'There is no rush. What to do, and what can wait.', scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Support for Right Now', h: 'The First Hour After', sub: 'There is no rush.', say: 'If the person you love has just died, I am so sorry. Take a breath. There is no rush. Nothing has to happen right away.' },
          { k: 'points', h: 'What to do first', items: [['Call the hospice', 'Not 911. They will guide you.'], ['Take your time', 'Sit with them as long as you need'], ['Say goodbye', 'Hold their hand, speak to them'], ['Invite others in', 'Children too, if they want to come']], say: 'Call your hospice, not 911. The hospice will guide you, and a nurse will come to help with the next steps, including the funeral home. Then take your time. Sit with them. Hold their hand. Say goodbye. Invite others in, children too, if they want to come.' },
          { k: 'points', h: 'Your tradition matters now', items: [['Prayers or readings', 'From their faith, or their favorite words'], ['Rituals', 'Washing, anointing, chanting, keeping watch'], ['Their faith card', 'In Willow, on the Bedside tab'], ['Their clergy', 'Call them, if they would want that']], say: 'If they had a faith or tradition, this is the time for it. Prayers or readings. Rituals like washing, anointing, chanting, or keeping watch with the body. Their faith card in Willow can help. And you can call their clergy, if they would want that.' },
          { k: 'big', h: 'Whatever you feel is okay.', sub: 'Tears, numbness, relief, all of it.', say: 'Whatever you feel right now is okay. Tears. Numbness. Even relief, after a long road. All of it belongs.' },
          { k: 'big', h: 'Your hospice keeps walking with you.', sub: 'Most offer grief support for about a year after a death.', say: 'Your hospice keeps walking with you. Most offer grief support for about thirteen months after a death. Ask for it by name. Take all the time you need.' }
        ] },

        { id: 'wl-s-tonight', n: 7, title: 'Caring for Yourself Tonight', mins: 2, blurb: 'Small things that help a tired heart and body.', scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Support for Right Now', h: 'Caring for Yourself Tonight', sub: 'Small things count.', say: 'Caring for someone near the end of life is some of the hardest work there is. Tonight, here are a few small things for you.' },
          { k: 'points', h: 'Tonight, try one', items: [['Drink a glass of water', 'Right now, if you can'], ['Eat something warm', 'Even something small'], ['Step outside', 'Five minutes of air'], ['Text one person', 'Let someone know how you are']], say: 'Tonight, try just one of these. Drink a glass of water. Eat something warm, even something small. Step outside for five minutes of air. Or text one person and let them know how you are really doing.' },
          { k: 'words', h: 'Let people help', items: ['Can you bring dinner Thursday?', 'Can you sit with him for two hours?', 'Can you pick up the kids?'], sub: 'Specific asks are easier to say yes to.', say: 'When people say, let me know if you need anything, give them something specific. Can you bring dinner Thursday. Can you sit with him for two hours. Specific asks are easier to say yes to.' },
          { k: 'big', h: 'Rest is part of loving them well.', say: 'Rest is not leaving them. Rest is part of loving them well, for as long as this takes.' },
          { k: 'points', h: 'Your own tree', items: [['Helpers have a tree too', 'In Willow, with your own check-ins'], ['Your hospice line', 'For them, day or night'], ['988', 'Call or text, if you are struggling']], say: 'Willow gives helpers a tree of their own, because you are carrying this too. Your hospice line is there for your person, day or night. And if you are struggling yourself, you can call or text 988 anytime.' }
        ] },

        { id: 'wl-s-blessing', n: 8, title: 'A Blessing for the Room', mins: 2, blurb: 'A quiet moment of prayer or stillness, for any faith tradition.', scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Support for Right Now', h: 'A Blessing for the Room', sub: 'A quiet moment, together.', say: 'This is a quiet moment for the room. If they have a faith, you can make it a prayer. If not, let it be a moment of stillness. Both are welcome here.' },
          { k: 'breathe', h: 'First, one slow breath', hold: 10, say: 'First, one slow breath together. In. And out.' },
          { k: 'words', h: 'A prayer, for those who pray', items: ['God, you are here with us.', 'Hold this one we love, and give them peace.', 'Carry what we cannot carry.', 'Stay close to each of us. Amen.'], gap: 2, say: 'For those who pray. God, you are here with us. Hold this one we love, and give them peace. Carry what we cannot carry. Stay close to each of us. Amen.' },
          { k: 'words', h: 'A blessing, in plain words', items: ['May you feel how loved you are.', 'May your body be at ease.', 'May you rest in peace, and in good company.', 'We are here.'], gap: 2, say: 'Or, a blessing in plain words. May you feel how loved you are. May your body be at ease. May you rest in peace, and in good company. We are here.' },
          { k: 'big', h: 'Use their own words, too.', sub: 'Their prayers, scripture, or poems are on the Readings tab.', say: 'Their own words are best of all. A prayer from their tradition. A favorite psalm, sutra, or poem. Willow has readings for all faith traditions and everything in-between on the Readings tab.' }
        ] }
      ] },

      /* ---------- Start Here (unchanged from the Learn build) ---------- */
      { id: 'willow-start', title: 'Start Here', who: 'For the person in hospice, and the people who love them', lessons: [
        { id: 'wl-welcome', n: 1, title: 'Welcome to Willow', mins: 2, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'Willow', h: 'Welcome to Willow', sub: 'Held gently, all the way home.', say: 'Welcome to Willow. A tree for the last part of the path.' },
          { k: 'big', h: 'Built for two.', sub: 'The person in hospice, and the people who love them.', say: 'Willow is built for two. The person in hospice, and the people who love them.' },
          { k: 'six', h: 'Every part still matters', words: ['Faith, tradition, and peace', 'Meaning, legacy, a life story', 'Feelings, fears, and calm', 'The people who love them', 'Comfort, rest, and ease', 'Hope that changes shape'], say: 'At the end of life, every part of a person still matters. Faith and peace. Meaning and legacy. Feelings and calm. The people they love. Comfort in the body. And hope, which changes shape along the way.' },
          { k: 'points', h: 'Faith comes first', items: [['Asked with care', 'Willow asks about faith or tradition first'], ['Every tradition', 'All faith traditions and everything in-between'], ['Faith cards', 'Words and practices for 29 traditions']], say: 'Willow asks about faith or tradition first, with care. It is made for all faith traditions and everything in-between, with faith cards for twenty nine traditions.' },
          { k: 'points', h: 'What you will find', items: [['What Matters', 'A page for what matters most'], ['Cuttings', 'Stories and letters to leave behind'], ['Bedside', 'A log of what helped today'], ['Helpers', 'Their own passcode, and only what is shared']], say: 'You will find a page for what matters most. Cuttings, for the stories and letters they want to leave. A log of what helped today. And helpers open Willow with their own passcode, seeing only what the person chooses to share.' },
          { k: 'quiz', q: 'Who is Willow built for?', opts: ['Only the hospice team', 'The person in hospice, and the people who love them', 'Only the family'], right: 1, why: 'Willow is built for two: the person, and the people who love them.', say: 'One question. Who is Willow built for?' }
        ] }
      ] },

      /* ---------- For You: the person in hospice (three lessons, no certificate) ---------- */
      { id: 'willow-you', title: 'For You', who: 'For the person in hospice. Watch at your own pace, alone or with someone you love.', cert: false, lessons: [

        { id: 'wl-y-yours', n: 1, title: 'Your Tree, Your Way', mins: 2, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For You', h: 'Your Tree, Your Way', sub: 'Willow is yours.', say: 'This lesson is for you, the person this tree belongs to. Willow is yours. You decide how you use it, and how much.' },
          { k: 'big', h: 'You are still growing.', sub: 'Every part of you still matters.', say: 'Here is what Willow believes. You are still growing, right up to the end. Your faith, your story, your feelings, your people, your comfort, and your hope all still matter.' },
          { k: 'points', h: 'You decide', items: [['Answer, or skip', 'Every question is optional'], ['Go slow', 'A quick check-in is six questions'], ['Words, not scores', 'Your tree shows how each part feels'], ['Stop anytime', 'Come back whenever you like']], say: 'You decide. Answer a question, or skip it. Every question is optional. A quick check-in is only six questions. Your tree shows words, never scores. And you can stop anytime, and come back whenever you like.' },
          { k: 'points', h: 'Faith comes first, every time', items: [['Your faith, in your words', 'Or no faith at all. Every answer is welcome.'], ['Asked again each time', 'Because things can change near the end'], ['Words from your tradition', 'Prayers and readings that fit you']], say: 'Willow asks about your faith or tradition every time, because faith can grow or change near the end of life. Every answer is welcome, including none. Then Willow offers prayers and readings that fit you.' },
          { k: 'points', h: 'You choose what helpers see', items: [['Helpers have their own passcode', 'They see only what you share'], ['Faith and notes start private', 'You can share them, or keep them'], ['Change it anytime', 'In Settings']], say: 'If someone helps you with Willow, they open it with their own passcode, and see only what you choose to share. Your faith answers and notes start private. You can change what is shared anytime.' },
          { k: 'story', title: 'No Scared. New Body.', lines: ['A man near the end of his life laughed through most of my visit, his hands trembling in his lap.', 'I asked him gently if he knew he was dying. He smiled, patted his chest, and said four words in English: No scared. New body.', 'His family had asked for someone who would sit with him without trying to change what he believed.'], lesson: 'Your faith is yours. Willow is here to honor it.', note: 'Names and details changed', say: 'A man near the end of his life once laughed through most of a chaplain visit. When asked gently if he knew he was dying, he patted his chest and said, no scared, new body. His family wanted someone who would sit with him without trying to change what he believed. Your faith is yours, too. Willow is here to honor it.' },
          { k: 'quiz', q: 'Who decides what your helpers can see in Willow?', opts: ['The hospice team', 'You do', 'Your helpers decide'], right: 1, why: 'Willow is your tree. You choose what is shared, and you can change it anytime.', say: 'One question. Who decides what your helpers can see?' }
        ] },

        { id: 'wl-y-matters', n: 2, title: 'What Matters to You', mins: 2, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For You', h: 'What Matters to You', sub: 'Your words, kept safe.', say: 'This lesson is about what matters to you, and how to keep it, in your own words, for the people you love.' },
          { k: 'big', h: 'Writing it down is a gift.', sub: 'The people you love will not have to guess.', say: 'Writing down what matters is a gift to the people you love. When the time comes, they will not have to guess what you would want.' },
          { k: 'screen', app: 'willow', app_name: 'Willow', title: 'What Matters', rows: [['Who I am', 'In my own words'], ['What gives me peace', ''], ['Who I want close', ''], ['What I want people to know', ''], ['My wishes for my last days', ''], ['Vigil wishes', 'Music, words, light']], tap: 5, panel: { h: 'Vigil Wishes', sub: 'What you want around you.', items: ['Music I love', 'Prayers or readings', 'Who I want in the room'] }, say: 'The What Matters tab holds a few short pages. Who you are, in your own words. What gives you peace. Who you want close. And your vigil wishes: the music, the words, and the people you want around you at the end.' },
          { k: 'points', h: 'Cuttings: pieces of you to leave behind', items: [['Stories', 'The ones your family asks you to tell'], ['Letters', 'To someone you love, or someone not born yet'], ['Things I learned', 'Three things life taught you'], ['Recipes, blessings, and more', 'Whatever you want to pass on']], say: 'Cuttings are pieces of you to leave behind, like a cutting from a willow that grows into a new tree. Stories your family asks you to tell. Letters to someone you love, even someone not born yet. Things life taught you. Recipes, blessings, whatever you want to pass on.' },
          { k: 'story', title: 'Passing It On', lines: ['A man who had built a business from almost nothing told me, I can\u2019t die right now. It will fall apart without me.', 'Over a few days, we turned toward legacy. He recorded what he knew, told his best stories, and made a message for each person who worked for him.', 'Then he told his family: I release you. Run it, sell it, or close the doors. Don\u2019t let it own you.'], lesson: 'What you pass on keeps growing after you.', note: 'Names and details changed', say: 'A man who had built a business from almost nothing once told the chaplain, I cannot die right now, it will fall apart without me. Over a few days, he turned toward legacy. He recorded what he knew, told his best stories, and made a message for each person who worked for him. Then he told his family, I release you. In his last days, his worry softened into pride and peace. What you pass on keeps growing after you.' },
          { k: 'big', h: 'Start with one line.', sub: 'You can always add more.', say: 'You do not have to write it all at once. Start with one line. You can always add more, or ask someone to type while you talk.' },
          { k: 'quiz', q: 'What is a Cutting in Willow?', opts: ['A medical record', 'A story, letter, or piece of you to leave behind', 'A list of medicines'], right: 1, why: 'Like a willow cutting that grows a new tree, a Cutting is something of you that keeps growing in the people you love.', say: 'One question. What is a Cutting?' }
        ] },

        { id: 'wl-y-help', n: 3, title: 'Letting Others Help', mins: 2, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For You', h: 'Letting Others Help', sub: 'Receiving is a gift too.', say: 'This last lesson is about something many people find hard near the end of life: letting others help.' },
          { k: 'big', h: 'Many people worry about being a burden.', sub: 'If you feel that way, you are not alone.', say: 'Many people near the end of life worry about being a burden. If you feel that way, you are not alone. It is one of the most common worries there is.' },
          { k: 'big', h: 'Letting them help is a gift you give them.', sub: 'It lets them show their love.', say: 'Here is another way to see it. Letting the people you love help you is a gift you give them. It lets them show their love, in the time you have left together.' },
          { k: 'words', h: 'You can tell them what you need', items: ['I need some quiet today.', 'Will you sit with me?', 'Please read to me.', 'I want to talk about what is happening.'], say: 'You can tell them what you need. I need some quiet today. Will you sit with me. Please read to me. Or, I want to talk about what is happening. Many families wait for you to open that door.' },
          { k: 'points', h: 'Your hospice team is there for you', items: [['The 24/7 line', 'At the top of Today, day or night'], ['Your nurse', 'For comfort in your body'], ['Your chaplain', 'For faith, fears, and meaning'], ['Your social worker', 'For family, plans, and worries']], say: 'Your hospice team is there for you too. The twenty four hour line is at the top of Today. Your nurse helps with comfort. Your chaplain is there for faith, fears, and meaning. Your social worker helps with family, plans, and worries.' },
          { k: 'story', title: 'Total Bliss', lines: ['Jane had been a young widow, and never stopped loving her husband.', 'A few days before she died, she told me she could feel her death getting close.', 'She smiled and said she felt nothing but peace and joy. Almost bliss.'], lesson: 'Peace can be part of the path, too.', note: 'From a Grounded story by Chris Joy', link: { href: 'https://chri5j0y.substack.com/p/total-bliss', label: 'Read the Full Story: Total Bliss' }, say: 'Chris tells about Jane, who a few days before she died said she could feel her death getting close. And she smiled, and said she felt nothing but peace and joy. Almost bliss. Peace can be part of the path, too.' },
          { k: 'quiz', q: 'What is one way to see letting others help you?', opts: ['As a burden on them', 'As a gift that lets them show their love', 'As something to avoid'], right: 1, why: 'Letting people help lets them love you well, in the time you have together.', say: 'One question. What is one way to see letting others help you?' }
        ] }
      ] },

      /* ---------- For the People Who Love Them: helpers (six lessons, certificate) ---------- */
      { id: 'willow-helpers', title: 'For the People Who Love Them', who: 'For family, friends, and caregivers walking with someone in hospice', certTitle: 'Willow: For the People Who Love Them', certLine: 'For finishing every lesson in the Willow series for families and caregivers.', lessons: [

        { id: 'wl-h-present', n: 1, title: "You Don't Have to Know What to Say", mins: 2, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For the People Who Love Them', h: "You Don't Have to Know What to Say", sub: 'Presence comes first.', say: "Welcome. This series is for the people who love someone in hospice. A spouse, a daughter or son, a friend, a neighbor who keeps showing up. Let's start with the worry almost everyone carries into the room. I don't know what to say." },
          { k: 'big', h: 'Your being there is the gift.', sub: 'Words are optional.', say: 'Here is what years at the bedside teach. Your being there is the gift. Words are optional. Most people near the end of life do not need a speech. They need someone close.' },
          { k: 'story', title: "The Blanket That Didn't Need Smoothing", lines: ['A husband sat beside his wife in her final hours, his chair so close his knee touched the bed rail.', 'He told me about their life together. As he talked, he reached over and smoothed her blanket. It had not slipped.', 'He kept holding her hand, like it was the only job left for him to do.'], lesson: 'Sometimes love just needs somewhere to put its hands.', note: 'Names and details changed', say: 'A husband once sat beside his wife in her final hours, his chair so close his knee touched the bed rail. As he talked about their life, he reached over and smoothed her blanket. It had not slipped. Sometimes love just needs somewhere to put its hands.' },
          { k: 'points', h: 'Ways to be present', items: [['Sit close', 'Pull your chair near, at eye level'], ['Offer touch, if it is welcome', 'A hand to hold, a hand on the shoulder'], ['Let silence be', 'Quiet together is still company'], ['Do small things', 'A cool cloth, lip balm, a blanket smoothed']], say: 'Here are some ways to be present. Sit close, at eye level. Offer touch, if it is welcome. A hand to hold, or a hand on the shoulder. Let silence be. Quiet together is still company. And do small things, like a cool cloth or lip balm.' },
          { k: 'points', h: 'Let them lead', items: [['Follow their topic', 'The weather, the game, the old days'], ['Let feelings be', 'Tears and laughter both belong'], ['Listen more than fix', 'You do not need every answer'], ['Short is fine', 'A ten minute visit still counts']], say: 'Let them lead. Follow their topic, even if it is the weather or the game. Let feelings be. Tears and laughter both belong. Listen more than you fix. And short is fine. A ten minute visit still counts.' },
          { k: 'big', h: 'When they say something hard, you can stay with it.', sub: 'Tell me more. I am here.', say: 'Sometimes they will say something hard. I am scared. I am ready. Why is this happening. You do not have to fix it. You can say, tell me more. Or simply, I am here. If they ever talk about ending their own life, call your hospice right away, day or night.' },
          { k: 'screen', app: 'willow', app_name: 'Willow', title: 'Today', rows: [['Hospice 24/7 line', 'Call'], ['Their tree', 'Six parts'], ["Today's practice", 'Sit together'], ['What Helped Today', 'Add a note'], ['Bedside', 'Ideas for right now']], tap: 3, panel: { h: 'What Helped Today', sub: 'A short log for the next person.', items: ['Music helped her settle', 'He liked the window open', 'She smiled at the photos'] }, say: 'Willow can help here too. On Today, What Helped Today keeps a short log, so the next person to sit with them knows what brought comfort.' },
          { k: 'quiz', q: 'What matters most when you sit with someone near the end of life?', opts: ['Finding the perfect words', 'Being there with them', 'Keeping the conversation going'], right: 1, why: 'Your being there is the gift. Words are optional.', say: 'One question. What matters most when you sit with someone near the end of life?' }
        ] },

        { id: 'wl-h-together', n: 2, title: 'Using Willow Together', mins: 2, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For the People Who Love Them', h: 'Using Willow Together', sub: 'One tree. Built for two.', say: 'This lesson walks through using Willow together, with the person you love.' },
          { k: 'big', h: 'Willow is their tree.', sub: 'You help them tend it.', say: 'Willow is their tree. You are there to help them tend it. They decide what to answer, and what to share with you.' },
          { k: 'points', h: 'Every answer says who answered', items: [['They answered', 'In their own words or taps'], ['They answered, I tapped', 'They talk, you tap for them'], ["I'm answering from what I see", 'When they can no longer say']], say: 'Every check-in says who answered. They answered, on their own. They answered and you tapped, while they talked. Or, when they can no longer say, you answer from what you see. Those answers are kept apart, and never speak for their own tree.' },
          { k: 'screen', app: 'willow', app_name: 'Willow', title: 'Check-in', rows: [['Roots', 'Strong', '#5F7D48'], ['Trunk', 'Steady', '#8B5E1A'], ['Bark', 'Growing Edge', '#B8612F'], ['Branches', 'Strong', '#5F7D48'], ['Leaves', 'Steady', '#8B5E1A'], ['Fruit', 'Steady', '#8B5E1A']], tap: 2, panel: { h: 'Growing Edge', sub: 'Where new growth begins.', items: ['A practice for calm', 'Tend it with others beside you'] }, say: 'After a check-in, each part of the tree shows a word. Strong, Steady, or Growing Edge. A growing edge is where new growth begins, and Willow suggests a gentle practice for it.' },
          { k: 'points', h: 'Faith comes first', items: [['Asked every time', 'On the second screen'], ['Every answer welcome', 'Including none'], ['Faith cards', 'What matters in their tradition, at the bedside']], say: 'Willow asks about faith every time, on the second screen, because a chaplain always asks. Every answer is welcome, including none. The Bedside tab has faith cards for twenty nine traditions, so you know what matters to them at the bedside.' },
          { k: 'points', h: 'What you can see', items: [['They choose', 'Tree words, What Matters, Cuttings, the log'], ['Faith and notes start private', 'Until they share them'], ['Home safety stays private', 'Always']], say: 'What you can see is their choice. Tree words, What Matters, Cuttings, and the log are the usual ones. Faith answers and notes start private, until they share them. And their answer about safety at home always stays private.' },
          { k: 'points', h: 'Your own tree', items: [['Helpers have a tree too', 'Your own check-ins, your own practices'], ['Caring for you', 'Practices made for caregivers'], ['Switch between trees', 'Their tree, and yours']], say: 'You have your own tree in Willow too, because caregivers carry this as well. Your own check-ins. Practices made for caregivers. And you can switch between their tree and yours anytime.' },
          { k: 'big', h: 'The hospice line is at the top of Today.', sub: 'Call it first, day or night.', say: 'One last thing. The hospice twenty four hour line sits at the top of Today. For anything urgent, call it first, day or night.' },
          { k: 'quiz', q: "When you answer a check-in from what you see, because they can no longer say, what happens?", opts: ['It replaces their own answers', 'It is kept apart from their own tree', 'It is sent to the hospice'], right: 1, why: 'Answers from what you see are kept apart, and never speak for their own tree.', say: 'One question. What happens to answers you give from what you see?' }
        ] },

        { id: 'wl-h-weeks', n: 3, title: 'What the Last Weeks Can Look Like', mins: 3, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For the People Who Love Them', h: 'What the Last Weeks Can Look Like', sub: 'Knowing helps.', say: 'Many families say the hardest part was not knowing what was normal. This lesson walks through changes many people go through near the end of life. Every person is different, and your hospice nurse knows your person best.' },
          { k: 'flow', h: 'A world that slowly gets smaller', steps: [['Weeks before', 'More sleep, less eating, less talking'], ['Days before', 'Very little food or drink, restless or confused at times'], ['Hours before', 'Breathing changes, less response']], say: 'Here is the general shape. Weeks before, many people sleep more, eat less, and talk less. Their world gets smaller. Days before, they may take very little food or drink, and may be restless or confused at times. In the last hours, breathing changes, and they respond less.' },
          { k: 'big', h: 'Turning inward is normal.', sub: 'It is part of their own inner work.', say: 'Turning inward is normal. If they talk less or seem far away, they are often doing quiet inner work. Your presence still matters, even in the quiet.' },
          { k: 'points', h: 'When they stop eating', items: [['The body slows down', 'It cannot use food the same way'], ['Hunger usually fades', 'Most do not feel hunger or thirst'], ['Love looks different now', 'Ice chips, lip balm, a little taste']], say: 'When they stop eating, it is hard to watch. Food is love. But near the end, the body slows down and cannot use food the same way. Most people do not feel hunger or thirst. Love looks different now. Ice chips, lip balm, a little taste of something they enjoy, only what they want.' },
          { k: 'story', title: 'Welcome Home', lines: ['A daughter texted me early one morning: Dad is seeing ghosts. What does this mean?', 'When I arrived, her father turned toward something we could not see and raised both arms. Very quietly, he said, I love you. I love you. I love you.', 'That evening, he died peacefully, just as we had seen him: arms open.'], lesson: 'Visions near the end usually bring comfort. Ask who is there.', note: 'From a Grounded story by Chris Joy', link: { href: 'https://chri5j0y.substack.com/p/welcome-home', label: 'Read the Full Story: Welcome Home' }, say: "Chris tells about a daughter who texted early one morning: Dad is seeing ghosts. When Chris arrived, her father turned toward something they could not see, raised both arms, and quietly said, I love you, I love you, I love you. Many people near the end see loved ones who have died. It usually brings comfort. Ask who is there, and listen." },
          { k: 'points', h: 'In the last hours or days', items: [['Breathing changes', 'Pauses, then a few quick breaths'], ['A rattling sound', 'Usually bothers us more than them'], ['Cool hands and feet', 'Blotchy skin on knees and feet'], ['Less response', 'But keep talking to them']], say: 'In the last hours or days, breathing often changes, with pauses and then a few quick breaths. There may be a rattling sound in the throat. It usually bothers us more than it bothers them. Hands and feet may feel cool, and skin on the knees and feet may look blotchy. They respond less. Keep talking to them.' },
          { k: 'big', h: 'Sometimes there is a rally.', sub: 'A surprising burst of energy. Treat it as a gift.', say: 'Sometimes a person who has been very sleepy wakes up, talks, eats, and knows everyone. It is real, and it is often brief. Treat it as a gift. Use it to say what you want to say.' },
          { k: 'big', h: 'Call your hospice anytime something worries you.', sub: 'Restlessness, grimacing, or anything that looks like distress.', say: 'Most of all, call your hospice anytime something worries you. Restlessness, grimacing, or anything that looks like distress. They can help with comfort, day or night. You never have to guess alone.' },
          { k: 'quiz', q: 'When someone near the end stops eating, what usually helps most?', opts: ['Encouraging them to eat more', 'Ice chips, lip balm, and only what they want', 'Waiting to visit until they eat again'], right: 1, why: 'Near the end, love looks like comfort: ice chips, lip balm, and only what they want.', say: 'One question. When someone near the end stops eating, what usually helps most?' }
        ] },

        { id: 'wl-h-words', n: 4, title: 'When Words Run Out', mins: 3, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For the People Who Love Them', h: 'When Words Run Out', sub: 'Love still reaches them.', say: 'There may come a time when the person you love can no longer talk, or open their eyes. This lesson is about how love still reaches them.' },
          { k: 'big', h: 'Hearing may be one of the last senses to go.', sub: 'Speak to them, not about them.', say: 'Hearing may be one of the last senses to go. In one study, the brains of unresponsive hospice patients still responded to sound in their last hours. So speak to them, not about them. Tell them who is in the room.' },
          { k: 'points', h: 'Ways to reach them', items: [['Your voice', 'Tell them stories, read to them'], ['Their music', 'The songs they love, softly'], ['Touch', 'Hold a hand, stroke an arm'], ['A phone to their ear', 'For family far away']], say: 'Here are ways to reach them. Your voice, telling stories or reading. Their music, played softly. Touch, holding a hand or stroking an arm. And for family far away, a phone held gently to their ear.' },
          { k: 'story', title: 'If She Is Still Here', lines: ['On my day off, a daughter texted that her mom had taken a turn. I wrote back that I could come tomorrow.', 'She answered: If she is still here. I went right away.', 'We prayed, and the whole family cried and let go together. Her mom died peacefully a few hours after I left.'], lesson: 'If something is telling you to go now, go now.', note: 'From a Grounded story by Chris Joy', link: { href: 'https://chri5j0y.substack.com/p/if-she-is-still-here', label: 'Read the Full Story: If She Is Still Here' }, say: "Chris tells about a day off, when a daughter texted that her mom had taken a turn. He wrote back that he could come tomorrow. She answered, if she is still here. He went right away. Her mom died peacefully a few hours after he left. If something is telling you to go now, go now. And say what you want to say today." },
          { k: 'words', h: 'Things you can say now', items: ['Thank you for loving me.', "I'll take care of Mom.", "We're going to be okay.", 'You can rest when you are ready.'], say: 'Here are things families often say. Thank you for loving me. I will take care of Mom. We are going to be okay. And, when it feels right, you can rest when you are ready.' },
          { k: 'story', title: 'Please Help My Dad Die', lines: ['A man was struggling to let go. His son could not bring himself to come.', 'I told him his children would be okay, that his son loved him even from afar, and that he was free to go.', 'His arm lifted, as if reaching for something. His daughter cried, Dad, I am here. You can go. He died peacefully the next day, with her at his side.'], lesson: 'Telling someone, once, that they can go when they are ready can be a gift.', note: 'From a Grounded story by Chris Joy', link: { href: 'https://chri5j0y.substack.com/p/please-help-my-dad-die', label: 'Read the Full Story: Please Help My Dad Die' }, say: 'Chris tells about a man who seemed to be holding on, while one of his sons could not bring himself to come. Chris told him his children would be okay, that his son loved him even from afar, and that he was free to go. His arm lifted, as if reaching for something, and his daughter said, Dad, I am here, you can go. He died peacefully the next day, with her at his side.' },
          { k: 'big', h: 'Some people seem to wait.', sub: 'For a visitor, a date, or permission. No one can say for sure.', say: 'Some people seem to wait, for a visitor, a date, or permission. Bedside workers see it often, though no one can say for sure why. Is anyone missing? Is anything left unsaid? Saying it once, gently, is enough.' },
          { k: 'quiz', q: 'If the person you love can no longer respond, what can you still do?', opts: ['Stop talking, since they cannot hear', 'Keep talking to them, play their music, and hold their hand', 'Talk about them in the room as if they are not there'], right: 1, why: 'Hearing may be one of the last senses to go. Speak to them, play their music, and stay close.', say: 'One question. If the person you love can no longer respond, what can you still do?' }
        ] },

        { id: 'wl-h-ready', n: 5, title: "When They're Ready and You're Not", mins: 3, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For the People Who Love Them', h: "When They're Ready and You're Not", sub: 'Holding on, and letting go.', say: 'Sometimes the person you love finds peace with dying before you do. Sometimes it is the other way around. This lesson is about that hard space.' },
          { k: 'story', title: 'Peace That Passes Understanding', lines: ['A woman with advanced cancer chose to stop treatment. She was calm, and smiling.', 'Her husband sat outside in the driveway. He could not watch. Some in her family thought she was giving up.', 'She told me she was not afraid or hopeless. She felt held by God, and she was ready.'], lesson: 'Love sometimes holds on with everything it has. Sometimes it opens its hands.', note: 'Names and details changed', say: 'A woman with advanced cancer once chose to stop treatment. She was calm and smiling, while her husband sat out in the driveway because he could not watch. Some in her family thought she was giving up. She said she was not afraid or hopeless. She felt held by God, and she was ready. Love sometimes holds on with everything it has. Sometimes it opens its hands.' },
          { k: 'big', h: 'Being ready to die is different from wanting to end your life.', sub: 'If you are ever unsure, call your hospice.', say: 'Here is something important. Being at peace with dying is different from wanting to end your life. Many people near the end feel ready, and that can be deep spiritual peace. If they ever talk about ending their own life, or you are unsure which you are hearing, call your hospice right away, day or night.' },
          { k: 'points', h: 'If you are not ready', items: [['Say so, gently', 'I am not ready to lose you, and I love you'], ['Let both be true', 'Your grief and their peace can share a room'], ['Get support', 'The hospice chaplain or social worker'], ['Take breaks', 'Step outside when it is too much']], say: 'If you are not ready, you can say so, gently. I am not ready to lose you, and I love you. Let both be true. Your grief and their peace can share a room. Talk with the hospice chaplain or social worker. And step outside when it is too much.' },
          { k: 'big', h: "If they ask, Why is God doing this to me?", sub: 'You do not need an answer. You can stay.', say: 'Sometimes it is the other way around. They are angry, or afraid, or asking, why is God doing this to me. You do not need an answer. That question is as old as faith itself.' },
          { k: 'story', title: 'Why Is God Doing This to Me?', lines: ['A woman with Parkinson\u2019s shook with tremors and asked me, Why is God doing this to me?', 'I told her anyone in her shoes would ask the same thing, and that people all through scripture had asked it too.', 'Something shifted. She nodded and said, He has never left me.'], lesson: 'You can honor the question without rushing to answer it.', note: 'From a Grounded story by Chris Joy', say: 'Chris tells about a woman with Parkinsons who asked, between tremors, why is God doing this to me. He told her anyone in her shoes would ask the same thing, and that people all through scripture asked it too. Something shifted, and she said, he has never left me. You can honor the question without rushing to answer it.' },
          { k: 'points', h: 'When faith feels complicated', items: [['Listen first', 'Let them say the hard thing'], ['Stay curious', 'Doubt and anger are part of faith for many'], ['Offer their own words', 'A prayer or reading from their tradition'], ['Invite the chaplain', 'Or their own faith leader']], say: 'When faith feels complicated, listen first. Let them say the hard thing. Stay curious with them. For many people, doubt and anger are part of faith. Offer words from their own tradition. And invite the hospice chaplain, or their own faith leader.' },
          { k: 'quiz', q: 'Your person feels ready to die and you are not. What can help?', opts: ['Hiding your feelings completely', 'Letting both be true, and getting support for yourself', 'Convincing them to keep fighting'], right: 1, why: 'Your grief and their peace can share a room. Let both be true, and lean on your hospice team.', say: 'One question. Your person feels ready, and you are not. What can help?' }
        ] },

        { id: 'wl-h-you', n: 6, title: 'Caring for Yourself on the Way', mins: 2, scenes: [
          { k: 'title', hero: 'willow', eyebrow: 'For the People Who Love Them', h: 'Caring for Yourself on the Way', sub: 'You matter here too.', say: 'This last lesson is about you. Caring for someone at the end of life is love, and it is also hard, tiring work. You matter here too.' },
          { k: 'story', title: 'Grief Debt', lines: ['One week I caught myself walking around numb. Not sad, not angry. Just numb.', 'A few losses had stacked up quietly, and I kept telling myself I would feel them later.', 'Grief we put off piles up, like laundry we swear we will fold.'], lesson: 'Pay grief down a little at a time.', note: 'From a Grounded story by Chris Joy', link: { href: 'https://chri5j0y.substack.com/p/grief-debt', label: 'Read the Full Story: Grief Debt' }, say: 'Chris, who sits with dying people every week, tells about a week he caught himself walking around numb. Losses had stacked up quietly while he told himself he would feel them later. He calls it grief debt. It piles up, like laundry we swear we will fold. The kindness is paying it down a little at a time.' },
          { k: 'flow', h: 'Notice. Name. Express. Unpack.', steps: [['Notice it', 'Something is there'], ['Name it', 'As clearly as you can'], ['Express it', 'Talk, write, cry'], ['Unpack it', 'Walk, stretch, breathe']], say: 'Here is a simple way to pay it down. Notice it. Name it. Express it. Then unpack it with your body.' },
          { k: 'points', h: 'Signs you need a break', items: [['Short temper', 'Snapping at people you love'], ['Not sleeping or eating', 'Running on empty'], ['Feeling numb', 'Or far away'], ['Thinking, no one else can do this', 'Others can help']], say: 'Watch for signs you need a break. A short temper. Not sleeping or eating. Feeling numb. Or thinking, no one else can do this. Others can help, and letting them is part of caring well.' },
          { k: 'points', h: 'Help is there', items: [['Respite care', 'Ask your hospice about short breaks'], ['Hospice volunteers', 'Someone to sit while you rest'], ['Grief support', 'Now, and for about a year after'], ['988', 'Call or text if you are struggling']], say: 'Help is there. Ask your hospice about respite care, a short break for you. Hospice volunteers can sit while you rest. Grief support is there now, and for about a year after a death. And if you are struggling, call or text 988 anytime.' },
          { k: 'big', h: 'Feeling relief after a long road is normal.', sub: 'It does not mean you loved them less.', say: 'One more thing. After a long road, many people feel relief when it ends, and then guilt for feeling relief. Relief is normal. It does not mean you loved them less. It means you carried a lot, for a long time.' },
          { k: 'big', h: 'You are bending, and you are not alone.', sub: 'Held gently, all the way home.', say: 'A willow bends in the storm, so far you think it should break, and it does not. You are bending too. You are not alone. Thank you for walking with the person you love, all the way home.' },
          { k: 'quiz', q: 'What is grief debt?', opts: ['Money owed for a funeral', 'Grief that piles up when we keep putting it off', 'A kind of hospice bill'], right: 1, why: 'Grief we keep putting off piles up. Notice, name, express, and unpack to pay it down.', say: 'Last question. What is grief debt?' }
        ] }
      ] }
    ]
  },
  grove: {
    title: 'Learn The Grove',
    intro: 'Short lessons, narrated aloud, for the whole family to watch together.',
    tracks: [
      { id: 'grove-start', title: 'Start Here', who: 'For families growing side by side', lessons: [
        { id: 'gr-welcome', n: 1, title: 'Welcome to The Grove', mins: 2, scenes: [
          { k: 'title', hero: 'grove', eyebrow: 'The Grove', h: 'Welcome to The Grove', sub: 'Where our trees grow together.', say: 'Welcome to The Grove, where our trees grow together.' },
          { k: 'big', h: 'Your tree is yours. The grove is ours.', say: 'Your tree is yours. The grove is ours.' },
          { k: 'trees', h: 'A tree for every age', grove: true, say: 'Everyone in the family has their own tree, in their own app. Maple for kids, Aspen for middle schoolers, Oak for adults, and more on the way.' },
          { k: 'flow', h: 'How The Grove works', steps: [['Tend your own tree', 'In your own app'], ['Show your growth', 'Switch it on in your app'], ['Grow together', 'Side by side in The Grove']], say: 'Here is how it works. Everyone tends their own tree in their own app. Each app has a switch to show your growth on The Grove. Then your trees stand side by side here.' },
          { k: 'points', h: 'In The Grove', items: [['The Wall', 'Cheer each other on with posts and reactions'], ['Together', 'Practices to do as a family'], ['Visitors', 'They arrive as the days add up'], ['Grown-ups keep it kind', 'A grown-up can remove any post']], say: 'In The Grove, the family wall lets you cheer each other on. Together has practices to do as a family. Visitors arrive as the days add up. And a grown-up can remove any post, to keep it kind.' },
          { k: 'quiz', q: 'Where does each person do their daily tending?', opts: ['In their own tree app', 'Only in The Grove', 'On paper'], right: 0, why: 'Daily tending happens in each person\u2019s own tree app. The Grove is where the trees stand together.', say: 'Quick question. Where does each person do their daily tending?' }
        ] }
      ] }
    ]
  }
};
