/* =====================================================================
   THE GROVE . PRACTICE LIBRARY
   "Show me how" for every practice, plus the new practices folded in
   from Maple and Aspen. Edit words here, not in index.html.

   HOW[strand]["Practice name"] = [
     why it helps,
     "step|step|step",          (steps split on |)
     if it's hard,
     kid why, "kid step|kid step", kid if it's hard
   ]
   The name must match the first name in PRACTICES (grove/data.js).
   Kid fields are for Maple-age trees (the kid wording in data.js).

   NEW practices are at the bottom, in LIB_NEW. Each has its own
   words for the Today card plus its how-to.
   ages: "all" (everyone), "teen" (middle school, high school, and
   adults), "teenOnly" (middle school and high school only).
   ===================================================================== */

const HOW = {

// ---------- ROOTS (What grounds you) ----------
spirit:{
 "Gratitude and Intention":["Naming what you're thankful for trains your eyes to find the good, and an intention gives your day a direction without turning it into a test.",
  "Before you pick up your phone, sit up and take one slow breath.|Name three specific things you're thankful for. \"The quiet kitchen\" beats \"my home.\"|Add one thing from yesterday that felt like a gift, even a small one.|Choose one intention, a way of being rather than a task: patient, present, brave.|Say it once more as you start your day.",
  "Hard morning? One thank-you and one word is enough. Some days gratitude is a choice before it's a feeling.",
  "Saying thank you helps you notice the good things all around you.","In the morning, hold up three fingers.|Say one thing you're thankful for with each finger.","Stuck? Start with something you can see right now."],
 "Breath Prayer":["Tying a short phrase to your breath gives a busy mind somewhere to rest, and it goes wherever you go.",
  "Choose a short phrase that fits you: \"Here I am,\" \"Peace, be still,\" or \"I am held.\"|Sit comfortably and let your breath slow.|Breathe in on the first half of the phrase and out on the second.|Repeat for two to five minutes. When your mind wanders, come back to the phrase.|Use it again later: in line, at a red light, before a hard conversation.",
  "Words feel empty? Breathe with them anyway. The body often believes before the mind does.",
  "Slow breaths and quiet words help your body feel calm and loved.","Breathe in and think, \"I am.\"|Breathe out and think, \"loved.\"|Do it five times.","Wiggly? Try it lying down with a hand on your belly."],
 "Sit Spot":["Returning to the same spot outdoors teaches you to notice slow changes, and it roots you to one small piece of the earth.",
  "Pick a spot you can reach easily: a porch step, a bench, a tree in the yard.|Leave your phone inside.|Sit for five to ten minutes. Notice sounds, light, birds, and weather.|Come back a few times this week, at about the same time of day.|Notice what's changed since last time.",
  "Restless? Start with two minutes. The stillness grows on you. Can't get outside? A window you return to works too.",
  "Having your own quiet spot outside helps you feel calm and notice nature.","Pick a special spot outside.|Sit quietly and count the sounds you hear.|Visit again another day and look for what's new.","Hard to sit still? Try one minute first."],
 "Prayer":["Prayer is honest conversation with the sacred. You don't have to get the words right. Saying the true thing out loud loosens its grip on you.",
  "Find five quiet minutes.|Say, or write, what you're thankful for.|Say what you're carrying.|Say what you need. That's a whole prayer.|Sit for a moment in silence at the end.",
  "If you don't know who you're talking to anymore, say so. \"I don't know if you're there, but here's what's true\" is a real prayer. Silence counts too.",
  "Talking about what's in your heart helps it feel lighter.","Get quiet, maybe at bedtime.|Talk about what's in your heart, in prayer or in your own words, in whatever way fits your family.","Don't know what to say? Start with \"Thank you for...\""],
 "Quiet With No Agenda":["Silence with no goal lets your thoughts settle, like mud settling in still water, and makes room for whatever is sacred to you.",
  "Set a gentle timer for ten minutes.|Sit comfortably, eyes closed or soft.|Don't ask for anything or try to get anywhere. Just be present.|When thoughts come, let them pass and return to the quiet.|Try it together sometime. A family or a couple can share one silent minute.",
  "Ten minutes too long? Start with two. A busy mind is normal, not failure.",
  "Quiet time helps your body rest and your mind feel calm.","Sit still with your family, or by yourself, for one minute.|Listen to the quiet.|Share one sound you heard.","Giggles happen. Just start again."],
 "Examen":["Looking back at your day shows you where life flowed and where it drained, so you can choose more of the good.",
  "At day's end, get quiet for five minutes.|Replay the day slowly, like a movie.|Ask: where did I feel most alive?|Ask: where did I feel most drained?|Give thanks for the good, and let the rest go for tonight.",
  "Can't remember much? Pick one moment of each. Harsh on yourself? Notice it, don't grade it.",
  "Sharing the best and hardest parts of your day helps you feel heard.","At bedtime, tell a grown-up the best part of your day.|Then tell the hardest part.|Ask for theirs too.","No hard part today? Great. Share two best parts."],
 "Awe Walk":["Awe, that wow feeling, helps you feel part of something bigger and shrinks worries down to size.",
  "Head out for a slow walk, ten to twenty minutes, with your phone in your pocket.|Look for something vast, beautiful, or surprising: sky, trees, water, light, a tiny bug.|When you find it, stop and take it in for a few breaths.|Let yourself be amazed without explaining it.",
  "Don't feel awe right away? Keep noticing. It sneaks up on you. Can't go outside? Step to a window, look up at the sky, and take three slow breaths.",
  "Finding amazing things helps you feel happy and curious.","Go on a walk with a grown-up.|Find three things that make you say wow.|Tell each other your favorite.","Can't find three? One wow still counts."],
 "Lament":["Telling the sacred honestly what hurts keeps pain from hardening inside you. Many traditions have prayers of lament, like the Psalms.",
  "Name what hurts, as plainly as you can.|Write it or say it out loud, anger included.|Say what you wish were different.|End with one honest line: what you need, or simply \"I'm still here.\"",
  "Feels wrong to be angry at God or at life? Many traditions make room for exactly this. If the hurt feels too heavy to carry alone, tell someone you trust. If you're having thoughts of not wanting to be alive, call or text 988.",
  "Sharing a sad feeling helps it feel smaller, and it lets people help you.","Think of something that makes you sad.|Tell a grown-up you trust, or draw it and show them.","Hard to say? Try starting with \"I feel sad about...\""],
 "Hold Someone in Light":["Holding someone in mind with love widens your heart and connects you to them, even from far away.",
  "Each day, bring one person to mind.|Picture them surrounded by light, or held by whatever you hold sacred.|Pray for them, or silently wish them peace, for one minute.|Over the week, include someone you love, someone struggling, and someone you'll never meet.",
  "Mind goes blank? Start with the first person who comes to you. There's no wrong choice.",
  "Sending love helps you remember that everyone needs care.","Think of someone who needs help.|Put your hand on your heart and send them love.","Can't think of anyone? Send love to someone in your family."],
 "Ritual":["Ritual gives the sacred a shape your body can feel. It tells your whole self: this moment matters.",
  "Join your community of faith or practice this week, or choose a small ritual of your own.|Light a candle or pour a glass of water.|Name one thing you're setting down and one thing you're inviting in.|Sit with it for one minute.|Repeat it at the same time next week, so it gathers meaning.",
  "If ritual feels fake or too churchy, borrow from ordinary life: a slow walk to the mailbox, a deliberate cup of tea. Intention is what makes it sacred, not the props.",
  "Traditions connect you to your family and the people who came before you.","Ask someone in your family about a tradition, prayer, or song that's special to them.|Ask why it matters.|Try it together.","Not sure who to ask? Grandparents often love this question."],
 "Forgiveness Reflection":["Forgiveness loosens the grip an old hurt has on you. It isn't pretending the hurt didn't happen, and it doesn't mean trusting the person again.",
  "Choose a hurt you're ready to begin releasing. Not the biggest one.|Write what happened and how it affected you.|Write what you'd like to let go of: the replaying, the weight, the wish for a different past.|End with one small step, even \"I'm willing to begin.\"",
  "Not ready? That's honest. Write \"not yet\" and come back later. Forgiveness never means staying somewhere unsafe.",
  "Letting go of a mad feeling helps your heart feel lighter.","Draw something someone did that still bugs you.|Fold the paper up and put it away.|Tell a grown-up about it.","Still feel mad? That's okay. Feelings take time. If someone hurt you or keeps hurting you, tell a grown-up you trust right away."],
 "Wise Company":["Talking with someone wise helps you see your own life more clearly, and you learn what helps other people trust when life is hard.",
  "Pick someone: a spiritual director, chaplain, pastor, elder, or wise friend. Teens: a grandparent, coach, or youth leader counts.|Set a time, even a phone call.|Share one thing you're wondering about, or a belief you're still figuring out.|Ask: \"What helps you trust when life is hard?\"|Listen more than you talk.",
  "Nervous? Start with a question for them rather than a story about you. It's easier to ask in the car or on a walk.",
  "Asking big questions helps you learn and wonder.","Pick a grown-up you trust.|Ask a big question, like \"Why are we here?\" or \"What helps you feel peaceful?\"|Listen to their answer.","Feels awkward? Ask at bedtime or on a walk."]
},

// ---------- TRUNK (Purpose) ----------
create:{
 "Journal Often":["Ten minutes on the page helps your mind sort what you've seen and felt, so you don't carry it loose.",
  "Set a timer for ten minutes.|Start with a moment, not a theme: a hand, a word someone said, the light in a room.|Write without stopping or editing. No one else will read it.|When the timer ends, underline one line that surprised you.",
  "Stuck? Write \"What I keep thinking about is...\" and keep going. Messy counts.",
  "Drawing your day helps you remember it and share it.","Pick one thing that happened today.|Draw it.|Tell someone about your picture.","Can't decide? Draw the best part."],
 "Values Sort":["Naming what matters most helps you spend your time and your yes on the right things.",
  "Write a list of values that matter to you: honesty, family, faith, courage, play, kindness, and any others.|Circle your top ten.|Cross out until five are left.|Next to each, write one way it showed up this week.|Keep the list where you'll see it.",
  "Everything feels important? Ask which three you'd keep if you could only keep three, then add two more.",
  "Knowing what you love helps you know yourself.","Draw or list five things you love most.|Add one thing you're learning to get better at.|Tell someone about your favorite.","Stuck? Think about what makes you smile."],
 "Create Stuff":["Making something with your hands pulls your whole attention into the moment, and it reminds you that you can bring something new into the world.",
  "Choose something to make: a sketch, a meal, a knit row, a birdhouse, a tune.|Set aside twenty minutes and put your phone away.|Make it for yourself, not an audience.|Stop while it's still fun.",
  "\"I'm not creative\"? Cooking, arranging flowers, and fixing a squeaky door all count. Done beats good.",
  "Making things helps your brain grow and feels great.","Pick something to build, color, or craft.|Make it just for fun.|Show someone if you want to.","Not sure what to make? Try a card for someone."],
 "Playing":["Play with no goal lowers stress and reminds you that life isn't only work.",
  "Pick something just for fun: a puzzle, an instrument, a game, a hobby.|Put the phone away.|Play for fifteen to thirty minutes.|Notice when you laugh or lose track of time.",
  "Feel guilty playing? Play is how people of every age recharge. Put it on the calendar like anything else.",
  "Pretending helps you imagine, solve problems, and have fun.","Make up a story or a pretend game.|Act it out, alone or with someone.|Invite a grown-up to play a part.","Stuck? Pretend you're an animal for five minutes."],
 "Expressive Writing":["Writing what you've witnessed helps your mind process it, so it doesn't settle into your body.",
  "Find twenty minutes where no one will interrupt.|Write about something hard you've seen or lived through.|Write what happened, what it cost you, and what surprised you.|Don't edit or reread. Tear it up if you want.|Come back to it most days this week.",
  "Too heavy? Stop and write about something lighter, or take a walk. If writing stirs up more than you can hold, talk with a counselor or someone you trust.",
  "Drawing feelings lets them out when words are hard.","Pick colors that match how you feel.|Draw your feeling with shapes and lines.|Tell a grown-up about it if you want.","There's no wrong way. Scribbles count."],
 "Purpose Statement":["Knowing what you're living for right now gives the rest of your days a spine.",
  "Ask: what do I want my life to be about in this season?|Write one or two sentences. Start with \"Right now, I'm living for...\"|Read it aloud and cut any word that doesn't feel true.|Put it where you'll see it: a mirror, your phone screen, a card in your wallet.",
  "Too big? Make it for this month only. Purpose can change as life changes.",
  "Knowing who you are helps you make good choices.","Finish this sentence: \"I am someone who...\"|Draw a picture to go with it.|Hang it up.","Stuck? Ask a grown-up what they see in you."],
 "Keep Learning":["Learning something new keeps your mind growing and gives you something to look forward to.",
  "Pick something you're curious about, a skill you want to get better at, or something you might want to do someday.|Choose a way in: a book, a video, a class, a person who knows.|Spend twenty minutes on it.|Write down one thing you learned.",
  "No time? Ten minutes counts. Too many interests? Pick the one that's been nagging you longest.",
  "Asking questions and finding answers makes your brain stronger.","Pick something you wonder about.|Find out one new fact with a grown-up, a book, or a video.|Tell someone what you learned.","Can't think of a question? Ask \"How does ___ work?\""],
 "Use Your Gifts":["Offering what you're good at turns your gifts into care, and it reminds you that you matter to others.",
  "Name one thing you're good at: fixing, teaching, cooking, listening, organizing.|Think of someone who could use it this week.|Offer it simply: \"Could I help with that?\"|Afterward, write a line about how it felt to help.",
  "Not sure what your gifts are? Ask a friend, or think of what people often ask you for.",
  "Teaching someone makes you feel proud, and it helps them too.","Pick something you're good at, like a trick, a game, or a drawing.|Teach it to someone step by step.","They didn't get it right away? Show it again, slower."],
 "Make Something to Keep":["Finishing a small thing gives you something real to hold, and it grows confidence for bigger things.",
  "Pick one small thing you can finish: a letter, a page, a song, a project.|Set a time to work on it this week.|Finish it, even if it's not perfect.|Give it to someone, or keep it where you'll see it.",
  "Perfectionism slowing you down? Decide ahead of time what \"done\" looks like, and stop there.",
  "Finishing something makes you feel proud.","Pick something you started, like a drawing or a building.|Finish it.|Show it to someone.","Too big? Finish just one part today."],
 "Write Your Story":["Telling the story of a turning point helps you see how you've grown and who you became.",
  "Pick a turning point: a move, a loss, a decision, a hard choice.|Write what happened, plainly.|Write what it showed you about yourself.|Write who you became because of it.",
  "Too painful? Choose a smaller turning point first. You decide how much to write and who reads it.",
  "Making a book about you shows how special your story is.","Fold a few sheets of paper into a little book.|Draw where you live, who you love, and what you like.|Read it to someone.","Ask a grown-up to write the words while you draw."],
 "Legacy Letter":["Writing what you hope your people carry forward helps you live toward it now.",
  "Pick one person you love, or a few.|Write what you've learned that you hope they'll carry.|Write what you love about them.|Keep it, give it now, or put it with your important papers.",
  "Feels heavy? It doesn't have to be about dying. Many people write one on a birthday or at the new year. Start with one thing you want them to know.",
  "A note for future you shows how much you'll grow.","Draw or write about you right now: what you like, what you're good at, what you wonder.|Seal it in an envelope.|Write a date on it to open next year.","Ask a grown-up to keep it safe for you."],
 "Stand-For Card":["Carrying what you stand for keeps it close when choices come.",
  "Ask: what do I stand for, no matter what?|Write it in one short line on a small card.|Keep it in your wallet, pocket, or phone case.|When a hard choice comes, take it out and read it.",
  "Can't narrow it down? Start with one value from your Values Sort.",
  "Knowing your superpower helps you be brave.","Name your superpower, like kindness, bravery, or helping.|Draw it on a card.|Keep it in your pocket or backpack.","Ask a grown-up what superpower they see in you."]
},

// ---------- BARK (Mind and feelings) ----------
mind:{
 "Meditation":["A few minutes of sitting trains your attention and gives your nervous system a place to rest.",
  "Sit comfortably with your back supported, and set a timer for ten minutes.|Close your eyes or let them rest on the floor.|Follow your breath in and out.|When your mind wanders, and it will, notice and come back. That returning is the practice.|Show up again tomorrow.",
  "Can't sit still? Try five minutes, or Walking Meditation. Free apps like Insight Timer can hold the time for you.",
  "Slow belly breaths help your body calm down.","Put your hands on your belly.|Breathe in slowly and fill your belly like a balloon.|Let it out slowly. Do it three times.","Hard to feel? Lie down with a stuffed animal on your belly and watch it rise."],
 "Name It":["Naming a feeling helps settle it. Your thinking brain comes back online when you put a word to what you feel.",
  "When a strong feeling shows up, pause.|Name it quietly: \"This is worry.\" \"This is anger.\"|Notice where you feel it in your body.|Ask: what do I need right now?|Give yourself one small piece of it.",
  "No word comes? Start broad: mad, sad, glad, scared. Mixed feelings? Name both.",
  "Knowing your feelings helps you take care of them.","Check your feelings weather: sunny, cloudy, rainy, or stormy?|Tell a grown-up and say why.|When a feeling gets big, say its name: \"I feel mad.\"","Don't know? That's okay. Say \"I'm not sure yet.\""],
 "Slow Exhale":["A long exhale tells your body it's safe, and it works anywhere.",
  "Breathe in through your nose for a count of four.|Breathe out slowly for six.|Repeat ten times.|Use it when stress climbs: before a meeting, in traffic, before school.",
  "Counting feels hard? Just make the breath out longer than the breath in.",
  "Blowing out slowly helps your body calm down.","Hold up five fingers like birthday candles.|Take a big breath and blow one out slowly.|Blow out all five.","Going too fast? Pretend the candles are far away."],
 "Self-Compassion Break":["Being kind to yourself in a hard moment helps you recover faster than criticism does.",
  "When you're hard on yourself, pause.|Put a hand on your heart.|Say: \"This is hard.\"|Say: \"Others feel this too.\"|Say: \"May I be kind to myself.\"",
  "Feels fake? Picture what you'd say to a friend in the same spot, and say that to yourself.",
  "Kind words help you try again after a mistake.","When you make a mistake, take a breath.|Say, \"It's okay. I'm still learning.\"","Still feel bad? Ask a grown-up for a hug."],
 "Body Scan":["Noticing your body from feet to head helps you find and release tension you didn't know you were holding.",
  "Lie down or sit comfortably for fifteen minutes.|Spend the first half following your breath.|Then move your attention slowly from your feet to your head.|Notice tension without trying to fix it.|End with three slow breaths.",
  "Fall asleep? That's fine. Try it sitting up next time. Some places hard to feel? Just notice that.",
  "Noticing your body helps you know what it needs.","Pretend you have a flashlight.|Shine it slowly from your toes to your head.|Say how each part feels.","Wiggly? Try it lying down."],
 "Worry Window":["Giving worry a set time teaches your mind it doesn't have to worry all day.",
  "Pick fifteen minutes in the afternoon.|Write down every worry.|Next to each, write one thing you can do, or \"not mine to fix.\"|When worry shows up later, tell it: \"Not now. Later today.\"",
  "Worry won't wait? Jot it on a note and save it for the window.",
  "Drawing a worry makes it smaller and easier to talk about.","Draw your worry as a silly monster.|Tell a grown-up about it.","Scary worry? Tell a grown-up right away."],
 "Leaves on a Stream":["Watching thoughts float by helps you see that you are not your thoughts.",
  "Sit quietly and close your eyes.|Picture a stream with leaves floating by.|Place each thought on a leaf and watch it drift away.|Keep going for five minutes.",
  "Stuck on one thought? Let it float by as many times as it comes. Clouds work too.",
  "Watching thoughts float away helps your mind feel calm.","Close your eyes.|Pretend each thought is a bubble.|Watch it float up and pop.","Lots of bubbles? That's okay. Keep popping."],
 "Walking Meditation":["When your mind is too loud to sit, slow steps give it a place to land.",
  "Find a path, a hallway, or a yard.|Walk slowly for ten minutes.|Put your attention on each footfall: heel, ball, toes.|When your mind wanders, come back to your feet.|Stressed and short on time? A quick walk around the block counts.",
  "Feel silly walking slowly? Walk at your normal speed and count your steps.",
  "Slow walking helps a busy body feel calm.","Walk super slow.|Feel each foot touch the ground.|Try it for one minute.","Too slow? Walk like a cat sneaking."],
 "Breathwork and Stillness":["A breathing pattern calms your body, and the stillness after lets you rest in that calm.",
  "Sit comfortably.|Do four rounds of 4-7-8 breathing: in for four, hold for seven, out for eight.|Or try box breathing: in for four, hold for four, out for four, hold for four.|Then sit still for fifteen minutes.|Sit longer on your rest day if you can.",
  "Holding your breath feels uncomfortable? Shorten the counts, or skip the hold. Dizzy? Stop and breathe normally.",
  "Being still helps your body and mind rest.","Sit very still, like a calm pond.|Stay still for two minutes.|Notice what you hear.","Wiggly? Try thirty seconds first."],
 "Mindfulness":["Doing one ordinary thing fully brings you out of your head and into your life.",
  "Pick one ordinary task: dishes, coffee, folding laundry.|Do only that. No phone, no TV.|Notice the details: warmth, sound, smell, texture.|When your mind drifts, come back to the task.",
  "Mind keeps planning? That's normal. Every return is the practice.",
  "Noticing with your senses helps you feel calm.","Find 5 things you see.|Find 4 you hear and 3 you can touch.|Find 2 you smell and 1 you taste.","Hard to find all of them? Do what you can."],
 "Kind Voice Letter":["Hearing kindness in the voice of someone who loves you helps quiet the inner critic.",
  "Think of someone who loves you, living or gone.|Write a short letter to yourself in their voice.|Let them say what they'd say about the week you've had.|Read it back slowly.",
  "Can't hear their voice? Write the letter you'd write to a friend in your shoes.",
  "Kind words from a friend help you feel good about yourself.","Pretend you're your best friend.|Draw a picture or write a note to yourself.|Say what they like about you.","Ask a grown-up to help with the words."],
 "Sound and Silence":["A single tone can settle your nervous system below the level of thought, and the silence after is where rest happens.",
  "Sit or lie down and dim the lights.|Strike a bowl or chime, or play one long note.|Listen until it fades completely.|Sit in the silence for two minutes.",
  "No bowl? Tap a glass, ring a bell, or play a long tone on your phone.",
  "Listening closely helps your body slow down.","Ring a bell or tap a glass.|Listen until the sound disappears.|Raise your hand when you can't hear it anymore.","Try it again with your eyes closed."]
},

// ---------- BRANCHES (Relationships) ----------
connect:{
 "One Reach-Out a Day":["Small reaches keep relationships alive between the big moments.",
  "Think of one person each day.|Send a text, make a call, or write a note.|Keep it simple: \"Thinking of you today.\"|Don't wait for the perfect thing to say.",
  "No reply? That's okay. The reach still counts. Can't think of anyone? Scroll your contacts and pick the first person you miss.",
  "Being kind every day helps friendships grow.","Pick one person each day.|Draw them a picture or say something nice.","Shy? A smile and a wave count."],
 "Active Listening":["Being really heard is rare, and listening well is one of the kindest things you can give.",
  "In one conversation today, put your phone away.|Listen without planning your reply.|Ask one follow-up question.|Say back what you heard: \"So it sounds like...\"",
  "Catch yourself planning your answer? Notice it and come back to their words.",
  "Listening shows people you care.","When someone talks, look at them.|Listen all the way to the end.|Ask one question about what they said.","Want to interrupt? Hold your idea in your hand and wait."],
 "Phone-Free Time":["Phones out of sight tell the people with you that they matter more.",
  "Pick someone to spend time with.|Put both phones out of sight, in another room or a drawer.|Spend twenty minutes together: a game, a walk, a meal.|Notice how the time feels different.",
  "Feel the pull to check? Set a timer on the stove instead of your phone.",
  "Playing without screens is more fun together.","Pick a game with no screens: cards, blocks, or tag.|Play it with someone.","Bored? Ask a grown-up to teach you a game they played as a kid."],
 "Ask for Help":["Letting people help you is part of connection. It gives them a way to care for you.",
  "Pick one thing you could use help with this week, even something small.|Pick someone to ask.|Ask simply: \"Could you help me with something?\"|Say thank you, and notice how it felt.",
  "Feel like a burden? Most people like being asked. Start with something small, like a ride or a recommendation.",
  "Asking for help is a brave and smart thing to do.","When something is hard, stop.|Ask a grown-up or friend, \"Can you help me?\"","Nervous? Practice saying it with a grown-up first."],
 "Real Time Together":["Unhurried time is how relationships deepen.",
  "Pick someone and set a time this week.|Meet in person, or call if you're far apart.|Put the phone away.|Ask one question you've never asked them.|Let the time run a little longer than usual.",
  "Busy week? Thirty minutes counts. Put it on the calendar so it happens.",
  "Special time with a grown-up helps you feel loved.","Ask a grown-up for fifteen minutes of special time.|You choose what to do together.","Grown-up busy right now? Pick a time together for later."],
 "Gratitude Letter":["Telling someone how they changed your life fills both of you up, sometimes for weeks.",
  "Think of someone who made a difference in your life.|Write them a letter about what they did and what it meant.|Be specific: the day, the words, the difference.|Read it to them, in person or on a call, if you can.",
  "Can't reach them, or they've died? Write it anyway, and read it aloud somewhere that matters.",
  "Saying thank you makes people feel special.","Think of someone who helps you.|Make them a thank you card.|Give it to them and read it out loud.","Ask a grown-up to help write the words."],
 "Loving-Kindness":["Wishing others well softens your heart, even toward people who are hard to love.",
  "Sit quietly and take a few slow breaths.|Start with someone you love: \"May you be safe. May you be well. May you be at peace.\"|Move to someone you barely know, then someone who might feel left out.|If you're ready, someone you don't get along with. Pray for them or wish them well.|End by wishing yourself well too.",
  "The hard person too hard today? Stop at the one before. That's still the practice.",
  "Kind wishes help your heart feel warm.","Think of someone.|Wish them a happy day in your heart.|Try someone who might feel lonely.","Can't think of anyone? Start with your family."],
 "Show Up":["Belonging grows by showing up, again and again, in the same place.",
  "Pick one group: a club, a class, a service, a game night, a team.|Put it on the calendar.|Go, even if you don't know anyone.|Say hello to one person.",
  "Anxious walking in? Arrive a few minutes early when it's quieter, or bring a friend.",
  "Making friends starts with saying hi.","Look for someone new.|Say hi and ask them to play.","Nervous? Ask a grown-up to help you say hi."],
 "Give and Receive":["Connection flows both ways. Giving and receiving both build trust.",
  "Do one thing for someone without being asked.|Then let someone do something for you.|Say thank you without apologizing.|Notice which one felt harder.",
  "Receiving harder? Let someone bring you a coffee or hold a door. Start small.",
  "Helping and being helped are both part of being a good friend.","Plan three kind things to do this week.|Do something helpful without being asked.|Let someone help you too.","Tell a grown-up about each one."],
 "Repair a Rupture":["Mending a strained relationship, even a little, lightens a load you've been carrying.",
  "Think of a relationship you want to mend.|Pick one small step: a note, an apology, a first hello.|Say what you're sorry for, if anything, without explaining it away.|Let them respond in their own time.",
  "Not safe to reach out? You can do the inner work without contact. Write what you'd say and keep it. Repair never means going back to harm.",
  "Saying sorry helps friends feel close again.","If you had a fight, take a breath first.|Say sorry, or tell them how you feel.","Still mad? Ask a grown-up to help."],
 "Friends":["Friendships need time on the calendar, not just good intentions.",
  "Pick a friend you want to see more.|Plan something: a walk, a meal, a game.|Put a date on it.|Show up and enjoy it.",
  "Out of touch? Start with a simple message: \"I've missed you. Want to get coffee?\"",
  "Playing with friends helps friendships grow.","Pick a friend.|Ask a grown-up to help plan a time to play.","Nervous? Invite them to do something you both like."],
 "Tell Them":["People rarely know how much they mean to us unless we say it.",
  "Pick someone who matters to you.|Think of one specific thing they do, or who they are.|Tell them, in person if you can.|Don't brush it off. Let it land.",
  "Feels awkward? Write it in a note instead.",
  "Telling people you love them makes them feel special.","Pick someone in your family.|Tell them one reason you love them.","A hug counts too."]
},

// ---------- LEAVES: MOVE ----------
body:{
 "Movement":["Movement lifts mood, steadies sleep, and gives stress somewhere to go. You don't have to be an athlete. You just have to move a little, on purpose.",
  "Check the level you chose: gentle, moderate, or athletic.|Warm up for a few minutes first.|Do this week's movement at your own pace.|Cool down with a slow walk or a stretch.|Notice one thing your body could do today.",
  "Pain or a health condition? Check with your doctor, and choose the gentle level. Joint pain means stop. Five minutes counts.",
  "Moving and playing makes your body strong and your mood happy.","Pick a way to move: run, jump, dance, bike, or play tag.|Keep moving for twenty minutes.|Get a drink of water after.","Stuck inside? Have a dance party to two songs."],
 "Morning Daylight":["Morning light helps set your body clock, so you feel more awake in the day and sleep better at night.",
  "Within an hour of waking, step outside.|Stay out for five to ten minutes. Cloudy days count.|Don't look at the sun. Just be in the light.|Pair it with coffee, a short walk, or the dog.",
  "Dark winter mornings? Sit by your brightest window, or step out at lunch.",
  "Morning light helps your body wake up.","In the morning, go outside or stand by a sunny window.|Say good morning to the sky.","Cold out? A window works."],
 "Stretch Break":["Stretching releases the tension that builds up from sitting, screens, and stress.",
  "Twice a day, stand up.|Reach up tall and hold for three breaths.|Fold forward gently, knees soft.|Roll your shoulders and neck slowly.|Try it to a song you love, or as a routine after school or work.",
  "Hard to stand? Stretch from a chair. Nothing should hurt.",
  "Stretching helps your body feel loose and good.","Stand tall.|Reach your branches up high.|Sway in the wind. Do it three times.","Wobbly? Hold onto a chair."],
 "Body Check":["Pausing to ask what your body needs catches small problems before they grow.",
  "Three times today, pause.|Ask: what does my body need right now?|Water, food, rest, movement, or a breath?|Give it one thing.",
  "Forget? Tie it to something you already do, like meals.",
  "Listening to your body helps you take care of it.","Ask your body: am I tired, hungry, thirsty, or wiggly?|Then take care of it.","Not sure? Ask a grown-up to help."],
 "Two Hours Outdoors":["Time outside lowers stress and lifts mood, and it adds up faster than you'd think.",
  "Aim for two hours outside across the week.|Break it up: walks, yard work, a park bench, lunch outdoors.|Jot down your minutes if it helps.|Notice how you feel on the days you get out.",
  "Bad weather? Dress for it, or count time by an open window. Ten minutes at a time adds up.",
  "Playing outside helps your body and mind feel good.","Go outside every day this week.|Look for bugs, clouds, and birds.|Tell someone your best find.","Rainy? Puddle jumping counts."],
 "Strength Training":["Strong muscles protect your joints, your balance, and your mood.",
  "Pick two or three days this week.|Warm up for a few minutes.|Do a short round: squats, push ups (the wall is fine), bridges, and a plank.|Do ten of each, or what you can.|Rest a day in between.",
  "Too hard? Use a chair for squats and a wall for push ups. Pain means stop. Check with your doctor if you have a health condition.",
  "Moving like animals makes your muscles strong.","Do bear crawls across the room.|Then frog jumps and crab walks.","Tired? Rest, then try one more."],
 "Move Every Hour":["Long sitting slows your body down. Short breaks wake it back up.",
  "Notice when you've been sitting for an hour.|Stand up and move for two minutes: walk, stretch, get water.|Set a gentle timer if it helps.|Try standing for phone calls.",
  "Stuck in meetings? Stand at the back, or stretch your legs under the table.",
  "Wiggle breaks help your brain get ready to learn.","After screen time or homework, get up.|Wiggle, hop, or dance for one song.","Ask a grown-up to set a timer."],
 "Yoga":["Gentle yoga builds strength and flexibility while it calms your mind.",
  "Pick two times this week.|Find a free gentle yoga video, fifteen to twenty minutes.|Go at the pace your body allows. Skip anything that hurts.|End lying still for one minute.",
  "Not flexible? That's why you do it. Chair yoga counts.",
  "Yoga poses help your body stretch and your mind feel calm.","Try cat, cow, dog, and cobra poses.|Make the animal sounds too.","Need help? Look at pictures of the poses together."],
 "Move With Someone":["Movement shared is easier to keep, and it's time together too.",
  "Invite someone: a walk, a bike ride, a game of catch.|Pick a time and put it on the calendar.|Go at a pace where you can both talk.|Plan the next one before you part.",
  "No one free? Join a walking group or a class, or call someone while you walk.",
  "Moving together is more fun.","Pick a game that makes everyone move: tag, catch, or a dance party.|Invite your family.","Grown-ups tired? Start with one song."],
 "Thank Your Body":["Thanking your body shifts your focus from how it looks to what it does for you.",
  "Think back over the week.|Write down three things your body did for you.|Thank it, the way you'd thank a friend.|If there's a part you're usually hard on, thank it too.",
  "Hard time with your body? Start simple: breathing, hugging, getting you here today.",
  "Your body does so much for you every day.","Think of something your body did today, like running or hugging.|Tell your body thank you.","Pick one body part and thank it."]
},

// ---------- LEAVES: REST ----------
rest:{
 "Sleep":["Sleep is where your body repairs and your mind sorts the day. A steady bedtime makes everything else easier.",
  "Pick a bedtime that gives you seven to nine hours.|Set a reminder thirty minutes before.|Dim the lights and wind down.|Wake at the same time every day, even weekends.",
  "Can't fall asleep after twenty minutes? Get up, read something calm in dim light, and go back when you're sleepy. Ongoing trouble? Talk with your doctor.",
  "Sleep helps you grow and feel happy.","Go to bed at the same time every night.|Pick your pajamas and a book.|Lights out when it's time.","Not sleepy? Lie quietly and rest your eyes."],
 "Screen-Free Evening":["Screens keep your brain alert. Turning them off early helps your body get ready for sleep.",
  "Pick a screens-off time, thirty to sixty minutes before bed.|Charge your phone outside the bedroom.|Use a simple alarm clock if you need one.|Fill the time with something calm: a book, a stretch, a talk.",
  "Need your phone as an alarm? Put it across the room, face down, with notifications off.",
  "Turning off screens helps your body get sleepy.","Turn off screens before bath and books.|Tuck the tablet into its own bed to charge.","Ask a grown-up to help you remember."],
 "Micro-Rest":["Short rests during the day keep you from running on empty.",
  "Three times today, stop for two minutes.|Close your eyes.|Drop your shoulders, and loosen your jaw and hands.|Let the breath slow.",
  "No private spot? Rest in the car, the bathroom, or with your eyes open, looking out a window.",
  "Little rests help your body recharge.","Pull into your shell like a turtle.|Close your eyes and rest for two minutes.","Ask a grown-up to time it."],
 "Same Wake Time":["A steady wake time steadies sleep more than almost anything else.",
  "Pick a wake time you can keep all week.|Set your alarm for it, weekend included.|Get light soon after you wake.|Tired? Go to bed earlier rather than sleeping in.",
  "Weekend feels unfair? Stay within an hour, and take an afternoon rest instead.",
  "Waking at the same time helps your body feel ready.","Wake up at the same time each morning.|Open the curtains and say good morning.","Ask a grown-up for a wake-up song."],
 "Wind Down":["Doing the same calm things each night teaches your body it's time to sleep.",
  "Write a simple wind-down plan: three calm things in the same order.|Try a warm shower, a paper book, a slow stretch.|Keep the room dark and cool.|Do it the same way each night this week.",
  "Nights vary? Keep just the last step the same every night.",
  "A cozy bedtime helps you fall asleep.","Bath, pajamas, teeth, book, snuggle.|Do it the same way every night.","Make a picture chart of the steps."],
 "Sleep Body Scan":["Relaxing each part of your body helps you let go of the day and drift toward sleep.",
  "Lie in bed and take three slow breaths.|Bring your attention to your toes and let them grow heavy.|Move slowly up: feet, legs, belly, hands, arms, shoulders, face.|Let each part sink into the bed.",
  "Mind wanders? Go back to wherever you left off. Falling asleep before you finish is the goal.",
  "Relaxing your body helps you fall asleep.","Lie in bed.|Let your body melt like a snowman in the sun.|Start with your toes and melt all the way up.","Ask a grown-up to say the body parts slowly."],
 "Worry Window":["Writing worries down before evening helps your mind let go of them at bedtime.",
  "Before evening, sit down with a notebook for ten minutes.|Write what's on your mind.|Next to each, write one next step, or \"not tonight.\"|Close the notebook. It will be there tomorrow.",
  "Worries come back at bedtime? Keep the notebook by the bed and jot them down fast.",
  "Telling a worry helps you sleep.","Tell a grown-up one worry.|Put it in a pretend jar for the night.|It can wait until morning.","Big worry? Tell a grown-up right away."],
 "Take a Real Break":["Real breaks, not errands, refill the energy you give away all day.",
  "Once a day, step away for fifteen minutes.|No work, no screens, no caregiving, no errands.|Sit outside, drink something warm, or just rest.|Tell someone you're taking it, so they can cover.",
  "Caregiving around the clock? Ask someone to cover fifteen minutes. You matter too.",
  "A cozy break helps you feel better.","Make a cozy corner with a pillow and blanket.|Rest there when you need a break.","No space? A blanket fort counts."],
 "Sabbath Hour":["Time with nothing to produce reminds you that you are more than what you get done. Many traditions keep a weekly sabbath.",
  "Pick one hour this week and put it on the calendar.|Nothing to produce and nothing to fix.|Rest, walk, pray, nap, or sit with people you love.|Protect it like any other appointment.",
  "An hour feels impossible? Start with fifteen minutes and let it grow.",
  "Slow time together helps everyone rest.","Pick one slow hour this week.|Cuddle up with a grown-up.|Read together with no rushing.","Hour too long? Read one book."],
 "Slow Morning":["A morning without rushing lets your body and mind catch up.",
  "Pick one morning or afternoon this week.|Clear anything that can wait.|Wake without an alarm, if you can.|Do only what you want to do, slowly.",
  "Every morning is full? Let one thing wait until tomorrow, and take that time back.",
  "Slow mornings help you start the day happy.","Stay in pajamas a little longer one morning.|Take it slow.","School day? Save it for the weekend."],
 "Rest Outside":["Resting outside lets the day slow down around you.",
  "Find a porch, a park, or a blanket in the grass.|Sit or lie down for twenty minutes.|Put the phone away or on silent.|Watch the sky, the trees, or the birds.",
  "Weather won't cooperate? Sit by an open window.",
  "Resting outside helps you feel calm.","Lie on the grass.|Find shapes in the clouds.","No clouds? Watch the leaves move."],
 "Guard Your Rest":["Saying no to one thing is a way of saying yes to rest. Protecting rest protects everything else.",
  "Look at your week.|Find one thing you can say no to, cancel, or hand off.|Say no kindly and clearly.|Use the time to rest.",
  "Hard to say no? Try: \"I can't this week, but thank you for asking.\"",
  "Knowing when you're tired helps you take care of yourself.","When you feel tired, stop.|Say, \"I need a rest.\"","That's a strong thing to say. Grown-ups say it too."]
},

// ---------- LEAVES: NOURISH ----------
nourish:{
 "One Slow Meal":["Eating slowly, sitting down, lets you taste your food and notice when you're full.",
  "Pick one meal a day.|Sit down at a table.|No screens.|Take your time and taste each bite.",
  "Busy day? Sit down for the five minutes it takes to eat. Eating alone? Light a candle or eat by a window.",
  "Eating slowly helps you enjoy your food.","Eat at the table, not in front of a screen.|Chew slowly and taste your food.","Ask a grown-up to eat with you."],
 "Water First":["Water helps your energy, focus, and mood. Many people are a little thirsty and don't know it.",
  "Drink a glass of water when you wake up.|Drink another before each meal.|Carry a water bottle.|Notice how your body feels.",
  "Don't like plain water? Add fruit slices. Have a condition that limits fluids? Follow your doctor's guidance.",
  "Water helps your body and brain work well.","Fill your own water bottle.|Drink from it all day.|Notice how your body feels.","Pick a fun bottle or a straw."],
 "Mealtime Blessing":["Pausing to give thanks connects you to the earth and to the people who brought you your food.",
  "Before you eat, pause.|Give thanks for the food and the hands behind it: farmers, drivers, cooks.|Use any words, a traditional prayer, or silence.|Take your first bite slowly.",
  "Eating with people who don't pray? A quiet moment of thanks inside counts.",
  "Saying thanks for food helps you remember the people who made it.","Before you eat, stop.|Say thanks for the food and the people who made it.","Take turns saying it at the table."],
 "Regular Meals":["Steady meals mean steady energy and a steadier mood.",
  "Eat something within a couple hours of waking.|Then eat about every four to five hours.|Keep easy food ready for busy days.|Notice how your energy changes.",
  "Not hungry in the morning? Start small: fruit, yogurt, or toast. Have a health condition? Follow your doctor's plan.",
  "Breakfast gives you energy to learn and play.","Eat breakfast every morning.|It's fuel for learning and playing.","Rushed? Grab a banana and a cheese stick."],
 "Build a Real Plate":["Protein, vegetables, and a healthy fat keep your energy steady so you don't crash.",
  "At one meal a day, look at your plate.|Add a protein: eggs, beans, fish, chicken, or tofu.|Add a vegetable, or two.|Add a healthy fat: olive oil, nuts, or avocado.|Notice which meals leave you steady.",
  "Budget tight? Beans, eggs, frozen vegetables, and oats go a long way. There are no rules to break here. Just notice.",
  "Lots of colors on your plate help you grow strong.","At dinner, try to eat three colors of real food.|Red, green, orange, purple, and yellow all count.","Picky? One new color bite is a win."],
 "Cook One Meal":["Cooking from scratch puts you in charge of what you eat, and it can be restful.",
  "Pick one simple meal: eggs and toast, soup, a pan of roasted vegetables.|Get what you need.|Cook it, and taste as you go.|Eat it sitting down.",
  "Never cooked? Start with eggs. Short on time? Make a big pot and eat it twice.",
  "Helping cook makes food taste even better.","Help a grown-up cook one meal.|Wash, stir, or set the table.","Stay safe: grown-ups handle knives and the stove."],
 "Notice How Food Feels":["Noticing how food makes you feel helps you learn what your body likes, without rules.",
  "After meals this week, set a gentle reminder for an hour later.|Notice your energy, mood, and comfort.|Jot a word or two if it helps.|Just notice. No rules.",
  "If food has been hard for you, skip the notes and talk with a doctor or dietitian you trust.",
  "Your tummy can tell you when you're full.","After you eat, ask your tummy.|Still hungry, full, or just right?","Not sure? That's okay. Keep asking."],
 "Keep Real Food Close":["What you see first is what you reach for.",
  "Put fruit, nuts, or cut vegetables where you'll see them first.|Wash and cut produce when you get home from the store.|Keep a snack in your bag or car.",
  "Food goes bad before you eat it? Buy smaller amounts, or keep frozen fruit and nuts on hand.",
  "Snacks that grow give you good energy.","Find a snack that grew somewhere.|An apple, carrots, or grapes all count.","Ask a grown-up to keep them where you can reach."],
 "Shared Meal":["Eating together is one of the oldest ways people connect.",
  "Pick someone to share a meal with this week.|Put phones away.|Ask a question and listen.|Linger at the table.",
  "Live alone? Invite a neighbor, call someone during dinner, or go to a community meal.",
  "Eating together helps families feel close.","Eat one meal with your family this week.|Everyone shares a good part of their day.","Busy family? Breakfast counts."],
 "A Dish That Means Something":["Food carries memory. Making a dish that means something connects you to the people behind it.",
  "Pick a dish that carries a memory, maybe one someone used to make for you.|Find the recipe, or ask someone who knows it.|Make it, or eat it somewhere that serves it.|Tell its story to someone.",
  "Grief comes up? That's okay. Food and grief often travel together. Let it come.",
  "Family foods carry family stories.","Ask a grown-up about a food from when they were little.|Help make it together.","Can't make it? Draw it and listen to the story."],
 "Grow or Gather":["Getting close to where food comes from helps you appreciate it.",
  "Pick one: grow herbs on a windowsill, visit a farmers market, or pick something fresh.|Choose one thing to grow or bring home.|Cook or eat it this week.|Notice how it tastes.",
  "No space? A single pot of basil counts. So does the grocery store produce aisle.",
  "Watching something grow is exciting.","Plant a seed in a cup of dirt.|Water it and watch it grow.","Beans maple fast."],
 "Feed Someone":["Feeding people is one of the oldest ways to love them.",
  "Think of someone who could use a meal: a new parent, someone grieving, someone sick.|Make or bring them food.|Keep it simple.|Drop it off with a short note.",
  "Can't cook? Send a meal, or bring groceries.",
  "Sharing food is a way to share love.","Share a snack with a friend or someone in your family.","Ask first if they have any allergies."]
},

// ---------- FRUIT (Hope) ----------
hope:{
 "Three Good Things":["Writing down good things and why they happened trains your mind to notice the good, and it lifts your mood over time.",
  "Before bed, open a notebook.|Write three good things from today.|Next to each, write why it happened.|On a hard day, one thing you're thankful for still counts.",
  "Can't think of three? Tiny counts: a good cup of coffee, a kind text, a laugh.",
  "Remembering good things helps you feel happy.","At bedtime, think back over your day.|Tell someone three good things.","Stuck? What made you smile today?"],
 "Something to Look Forward To":["Having something good ahead gives you hope, and looking forward is half the joy.",
  "Pick one small thing you'd enjoy: a meal, a walk, a call, a show.|Put it on the calendar this week.|Picture it once in a while as the day gets closer.|Enjoy it when it comes.",
  "Nothing appeals? Pick something tiny, like a favorite tea on Friday.",
  "Looking forward to fun things makes waiting exciting.","Pick something fun coming up.|Draw it.|Count down the days on a calendar.","Nothing coming up? Plan something small with a grown-up."],
 "Capture the Moment":["Writing down a moment that gave you a lift helps you keep it.",
  "Watch today for a moment that gave you even a small lift.|Write it down: what happened and why it landed.|Add a photo if you like.|Read back over your moments at the end of the week.",
  "Missed it in the moment? Think back at the end of the day. It still counts.",
  "Remembering happy moments helps them last.","When something makes you smile, take a pretend picture in your mind.|Tell someone about it.","Ask a grown-up for their snapshot too."],
 "Joy List":["Collecting small joys shows you how many you already have.",
  "Start a list on paper or on your phone.|Add small things that bring you joy.|Add to it every day this week.|Pick one to do today.",
  "Stuck? Think with your senses: a smell, a sound, a taste you love.",
  "Saving happy things helps on sad days.","Write or draw happy things on little papers.|Put them in a jar.|Pull one out on a sad day.","Ask a grown-up to write the words."],
 "Tiny Next Step":["Small steps build hope. Taking one proves change is possible.",
  "Pick one thing you'd like to be different.|Name the smallest possible next step.|Take it today.|Notice how it feels, and pick the next one.",
  "Still too big? Make the step even smaller. Or do one thing your future self will thank you for.",
  "Practicing a little at a time helps you get better.","Pick something you want to get better at.|Practice it for five minutes.","Still hard? That's how getting better feels."],
 "Hope Map":["Hope grows when you can see more than one path forward.",
  "Write a goal in the middle of a page.|Around it, list paths toward it.|For each path, list what might block it and a way around.|Pick one path to start.|Tell someone about your goal.",
  "Goal feels far off? Pick a smaller goal that points the same direction.",
  "Drawing your dream helps you believe you can reach it.","Draw something you hope for.|Draw two paths to get there.|Write \"I can do it!\"","Ask a grown-up to help with the steps."],
 "Savoring Walk":["Slowing down to savor good things helps them last longer.",
  "Take a ten minute walk.|Look for good things: a smell, a color, a sound.|Notice three things that are growing or changing.|Linger on each one for a few breaths.",
  "Nothing good on your route? Look closer: moss, light, a bird.",
  "Looking for beautiful things makes a walk an adventure.","Go on a walk.|Find three beautiful things.","Ask a grown-up to hunt too."],
 "Pay It Forward":["Doing good for someone who can't pay you back grows hope in both of you.",
  "Look for someone you can help who can't repay you.|Do something generous: pay for a coffee, leave a note, help a stranger.|Don't tell anyone.|Notice how it feels.",
  "Money tight? Give time or a kind word.",
  "Secret kindness makes someone's day.","Do something kind in secret.|Leaving a nice note counts.","Ask a grown-up for ideas."],
 "Best Possible Self":["Picturing a good future helps you move toward it, and it lifts your mood today.",
  "Imagine your life a year from now, if things go as well as they reasonably could.|Write about it for ten minutes: where you are, who's with you, what you're doing.|Or write a letter to yourself, one year from now.|Pick one thing in it you could start now.",
  "Hard to picture good things? Start with one area: work, home, or friends.",
  "Dreaming big is fun and helps you grow.","Draw yourself doing something you love when you're bigger.|Tell someone about it.","Anything goes. Big dreams are fine."],
 "Volunteer":["Giving time to something bigger than you grows hope, for them and for you.",
  "Pick a place: a food shelf, a neighbor, a cause you care about.|Find a time this week.|Give an hour.|Notice who you met.",
  "No time? Help a neighbor for fifteen minutes. That counts.",
  "Helping others makes the world better.","With a grown-up, find a way to help at home, school, or in your neighborhood.|Do it together.","Feel too little to help? Picking up litter or drawing cards counts."],
 "Inspire Hope":["Telling someone you believe in them can carry them through a hard stretch.",
  "Think of someone going through a hard time.|Tell them you believe in them.|Say why, specifically.|Check in again later in the week.",
  "Don't know what to say? \"I'm thinking of you, and I believe in you\" is enough.",
  "Cheering someone on helps them keep trying.","When things are hard for someone, tell them, \"You can do it!\"","Draw a cheer card."],
 "Growth Reflection":["Looking back at how you've grown shows you what's working and what to carry forward.",
  "Look back over these weeks.|Ask: what grew?|Ask: what surprised me?|Ask: what am I carrying forward?",
  "Doesn't feel like much grew? Small counts. Look through your journal for clues.",
  "Seeing how you grew makes you proud.","Tell a grown-up one way you've grown this season.","Ask them what they noticed."]
}
};

// =====================================================================
// NEW PRACTICES, folded in from Maple and Aspen
// =====================================================================
const LIB_NEW = [
 // ---------- Roots ----------
 { id:"peaceful-place", part:"roots", strand:"spirit", ages:"all", name:"Peaceful Place",
   text:"Draw or picture a place where you feel at peace, and return to it in your mind.", busy:"Close your eyes and picture your peaceful place for three breaths.",
   kidName:"My Peaceful Place", kidText:"Draw a place where you feel calm and safe.", kidBusy:"Picture your calm place.",
   how:["Picturing a peaceful place reminds your body that calm is real, and you can go back to it anytime in your mind.",
    "Close your eyes and picture a place where you feel at peace, real or imagined.|Fill in the details: colors, sounds, smells, the temperature of the air.|Sketch it, or write a few lines about it.|When stress rises, close your eyes and go there for three breaths.",
    "Not an artist? Stick figures count. No place comes to mind? Borrow one: a quiet beach, a porch at dusk, a forest path.",
    "Drawing a peaceful place helps you remember calm, even when feelings get big.","Picture a place where you feel calm and safe.|Draw it.|Keep it where you'll see it.","Scribbles count. It's just for you."] },
 { id:"true-no-matter-what", part:"roots", strand:"spirit", ages:"all", name:"True No Matter What",
   text:"Write one thing about you that stays true no matter what anyone posts or says.", busy:"Say one true thing about yourself.",
   kidName:"True About Me", kidText:"With a grown-up, name one good thing that's always true about you.", kidBusy:"Say, \"I am loved.\"",
   how:["Writing down what's true about you helps you hold steady when others post, say, or think something different.",
    "Open a notebook or a private note.|Finish this sentence: \"No matter what anyone says, it's true that I...\"|Write one more line about how you know it's true.|Read it again on a day you feel small.",
    "Blank page? Start with something you care about, or someone who loves you. If you have faith, a line like \"I am loved by God\" counts.",
    "Knowing good things about yourself helps when someone says something mean.","Ask a grown-up to help you name one good thing that's always true about you.|Draw or write it, and keep it close.","Stuck? Start with \"I am loved.\""] },
 { id:"write-a-blessing", part:"roots", strand:"spirit", ages:"all", name:"Write a Blessing",
   text:"Write a short prayer, wish, or blessing for your day, or for someone else's.", busy:"Say a one-line blessing for your day.",
   kidName:"My Blessing", kidText:"Make up one kind wish for your day, like \"Help me be kind.\"", kidBusy:"Say one kind wish.",
   how:["A written blessing sets your heart for the day, and blessing someone else turns your attention outward.",
    "In the morning, take a quiet minute.|Write a short prayer, wish, or blessing, one to three lines.|Choose who it's for: your own day, someone you love, or someone having a hard time.|Read it once more before you go, or send it to them.",
    "Not sure what to write? Try: \"May today hold one good surprise, and may I be kind.\"",
    "A kind wish for your day helps you start it happy.","Make up one kind wish for today, like \"Help me be kind.\"|Say it or draw it before school.","Ask a grown-up to make one with you."] },
 { id:"carry-a-question", part:"roots", strand:"spirit", ages:"teen", name:"Carry a Question",
   text:"Name a big question about faith or life you've never said out loud. Walk with it, or write it down.", busy:"Write down one question you're carrying.",
   how:["Questions are a sign of growing, not of losing faith. Walking or writing with a big question lets your mind work on it without pressure.",
    "Name one big question about faith or life you've never said out loud.|Write it down, just for you.|Take a ten minute walk and let your mind wander around it. You don't need an answer.|When you're ready, share it with someone you trust.",
    "No question comes? Ask yourself: what matters most to me? Nervous writing it down? It's private until you choose otherwise."] },
 { id:"sunrise-or-sunset", part:"roots", strand:"spirit", ages:"all", name:"Sunrise or Sunset",
   text:"Watch a sunrise or sunset from start to finish, with no phone.", busy:"Look up at the sky for one minute.",
   kidName:"Watch the Sky", kidText:"Watch a sunset with a grown-up and name all the colors you see.", kidBusy:"Look at the sky and name one color.",
   how:["Watching the sky change without a phone fills you with awe and helps you feel part of something bigger.",
    "Check the time for sunrise or sunset, and pick a spot with a view.|Leave your phone behind, or put it away.|Watch from start to finish: the colors, the light, the quiet.|Say thank you, in your own words, for the day beginning or ending.",
    "Missed it, or clouds rolled in? Watching clouds or stars works too.",
    "Watching the sky change helps you feel calm and amazed.","Watch a sunset with a grown-up.|Name all the colors you see.","Sunset past bedtime? Try the sky at dinner, or a sunrise on a weekend."] },
 { id:"something-bigger", part:"roots", strand:"spirit", ages:"teen", name:"Something Bigger",
   text:"Write about a time you felt part of something bigger than yourself.", busy:"Remember one time you felt part of something bigger.",
   how:["Remembering times you felt part of something bigger shows you where your roots already are.",
    "Think of a time you felt part of something bigger than yourself.|Write what happened, where you were, and who was there.|Write how it felt in your body.|Ask: where could I find more of that this month?",
    "Can't think of one? A team, a concert, a worship service, a crowd singing, or a night under the stars can all count."] },
 { id:"slow-sacred-reading", part:"roots", strand:"spirit", ages:"teen", name:"Slow Sacred Reading",
   text:"Read a short sacred text, poem, or prayer slowly, twice. Notice what stays with you.", busy:"Read one line slowly, twice.",
   how:["Sacred texts hold words people have leaned on for centuries. Reading slowly, more than once, lets them find you where you are.",
    "Choose one short passage: a psalm, a poem, or a line from your tradition.|Read it slowly, twice. Out loud helps.|Notice the word or phrase that catches you.|Sit with it for a minute. What might it be saying to you today?",
    "If your old text feels loaded or painful, start with the Psalms, a poet, or a teacher you trust. Read for comfort before you read for answers."] },

 // ---------- Trunk ----------
 { id:"strength-spotting", part:"trunk", strand:"create", ages:"all", name:"Strength Spotting",
   text:"Ask someone you trust to name a strength they see in you. Write it where you'll see it.", busy:"Name one thing you did well today.",
   kidName:"Strength Detective", kidText:"Ask a grown-up, \"What is something I am good at?\"", kidBusy:"Say one thing you're good at.",
   how:["Hearing a strength from someone else helps you believe it, and it shows you gifts you might not see yourself.",
    "Make your own list of five things you're good at.|Ask someone you trust to add one.|Write the strength they named where you'll see it.|Watch for it this week, and notice when you use it.",
    "Awkward to ask? Say it's part of something you're trying. Most people love this question.",
    "Knowing your strengths helps you feel brave.","Ask a grown-up to watch for one of your strengths this week.|They tell you what they noticed, like \"You were brave when...\"|Write or draw it and keep it where you can see it.","It's okay to feel shy. Strengths are real even when you're quiet about them."] },
 { id:"helper-job", part:"trunk", strand:"create", ages:"all", name:"Helper Job",
   text:"Take on one small job your family or group counts on, every day this week, without being asked.", busy:"Do one helpful thing without being asked.",
   kidName:"Helper Job", kidText:"Pick one way to help at home or at school, and do it every day this week.", kidBusy:"Help with one thing today.",
   how:["Being counted on gives you a place in something bigger than yourself.",
    "Pick one small job others rely on: feeding the dog, taking out the trash, setting up chairs.|Tell someone you'll do it this week.|Do it every day, without being reminded.|Notice how it feels to be part of how things run.",
    "Forgot a day? Pick it back up tomorrow. A good job is one you can actually keep.",
    "Helping makes you an important part of your family or class.","Pick one job that helps your family or class.|Do it every day this week.|Notice how it feels to help.","Forgot? Ask a grown-up for a reminder."] },
 { id:"who-counts-on-me", part:"trunk", strand:"create", ages:"all", name:"Who Counts on Me",
   text:"Think of one person who needs you, and why.", busy:"Name one person who's glad you're here.",
   kidName:"Who Needs Me", kidText:"Think of someone who is happy you're in their life. Draw them.", kidBusy:"Name someone who loves you.",
   how:["Knowing you matter to someone is one of the deepest sources of meaning.",
    "Get quiet for two minutes.|Think of one person who needs you, or is glad you're here.|Name why: what do you bring them?|Do one small thing for them today.",
    "Hard to think of anyone? Pets count. Coworkers count. The neighbor you wave to counts. If you feel like no one would miss you, please talk with someone today, or call or text 988.",
    "Knowing someone is glad you're here helps you feel important and loved.","Think of someone who is happy you're in their life.|Draw them, or tell them hi.","Can't pick? Everyone in your family counts."] },
 { id:"values-in-action", part:"trunk", strand:"create", ages:"teen", name:"Values in Action",
   text:"At day's end, name one choice that matched what matters most to you.", busy:"Ask yourself: what matters most to me today?",
   how:["Noticing when your choices line up with your values helps you become the person you want to be, one choice at a time.",
    "In the morning, ask: what matters most to me today?|At day's end, look back.|Name one choice that matched it.|Gently name one you'd make differently tomorrow.",
    "No match today? That's information, not failure. Pick one small choice for tomorrow."] },
 { id:"someone-i-admire", part:"trunk", strand:"create", ages:"all", name:"Someone I Admire",
   text:"Picture someone you look up to. Name what you admire, and one way to grow toward it.", busy:"Name one thing you admire in someone.",
   kidName:"My Hero", kidText:"Think of someone you look up to. Draw them and say why.", kidBusy:"Name one person you look up to.",
   how:["The people we admire show us who we want to become.",
    "Picture someone you look up to, living or not, famous or not.|Write what you admire about them.|Pick one of those qualities.|Name one small way to practice it this week.",
    "Nobody comes to mind? Think of a character in a story, or someone who was kind to you once.",
    "Looking up to good people helps you grow like them.","Think of someone you look up to.|Draw them and say one thing you like about them.","Grown-ups, teachers, and older kids all count."] },
 { id:"meaning-interview", part:"trunk", strand:"create", ages:"all", name:"Meaning Interview",
   text:"Ask an older person what gave their life or work meaning, and really listen.", busy:"Ask someone one question about what matters to them.",
   kidName:"Ask a Grown-Up", kidText:"Ask a grown-up, \"What makes you happy?\" or \"What was your favorite job ever?\"", kidBusy:"Ask a grown-up one question about their life.",
   how:["Hearing what gave someone else's life meaning helps you find your own, and being asked is a gift to them.",
    "Pick an older person: a grandparent, neighbor, coach, or coworker.|Ask: \"What gave your life meaning when you were my age?\" or \"What makes your work meaningful?\"|Listen, and ask one follow-up question.|Write down one thing they said that you want to remember.",
    "Nervous? Ask during something else, like a drive or a meal. Most people light up at this question.",
    "Asking questions helps you learn from people who love you.","Pick a grown-up.|Ask what makes them happy, or what their favorite job was.|Listen to their answer.","Ask a grown-up to help you think of a question."] },

 // ---------- Bark ----------
 { id:"grounding-54321", part:"bark", strand:"mind", ages:"all", name:"5-4-3-2-1 Grounding",
   text:"Name five things you can see, four you can feel, three you can hear, two you can smell, and one you can taste.", busy:"Name three things you can see right now.",
   kidName:"Five Senses Check", kidText:"Find 5 things you see, 4 you can touch, 3 you hear, 2 you smell, and 1 you taste.", kidBusy:"Name three things you can see.",
   how:["Using your senses pulls you out of racing thoughts and back into the present moment.",
    "Pause wherever you are.|Name five things you can see.|Name four things you can feel.|Name three things you can hear, and two you can smell.|Name one thing you can taste.",
    "Can't find all of them? Do what you can. Even the first two steps help.",
    "Noticing with your senses helps big feelings get smaller.","Find 5 things you see and 4 you can touch.|Find 3 you hear, 2 you smell, and 1 you taste.","Do it with a grown-up and take turns."] },
 { id:"plant-your-feet", part:"bark", strand:"mind", ages:"all", name:"Plant Your Feet",
   text:"When feelings get big, press your feet into the floor like roots and take three slow breaths.", busy:"Feet on the floor, one slow breath.",
   kidName:"Tree Roots", kidText:"When feelings get big, press your feet into the floor like tree roots and take three slow breaths.", kidBusy:"Press your feet down and take one big breath.",
   how:["Pressing your feet down reminds your body it's steady and supported, even when your feelings aren't.",
    "Notice a big feeling rising.|Press both feet firmly into the floor.|Picture roots growing down from your feet.|Take three slow breaths, longer out than in.",
    "In a place you can't pause? Do it under the desk. No one needs to know.",
    "Pretending your feet are roots helps you feel strong and calm.","Press your feet into the floor.|Pretend they're tree roots.|Take three slow breaths.","Try it standing up, tall like a tree."] },
 { id:"true-or-just-loud", part:"bark", strand:"mind", ages:"teen", name:"True or Just Loud",
   text:"Catch one harsh thought. Ask: is this true, or just loud? Then write a kinder way to say it.", busy:"Notice one thought and ask: is this true, or just loud?",
   how:["Harsh thoughts feel true because they're loud. Questioning them loosens their hold.",
    "Catch one harsh thought about yourself.|Write it down exactly.|Ask: is this true, or just loud? What's the evidence?|Write a kinder, truer way to say it.|Read the new version out loud.",
    "Can't find a kinder version? Write what a good friend would say instead."] },
 { id:"both-can-be-true", part:"bark", strand:"mind", ages:"teen", name:"Both Can Be True",
   text:"Write two feelings you have right now that seem opposite. Let both stand.", busy:"Name two feelings you have right now.",
   how:["Mixed feelings are normal. Letting both be true is less exhausting than forcing one to win.",
    "Notice what you're feeling right now.|Write two feelings that seem to pull against each other: excited and scared, relieved and sad.|Write \"Both can be true.\"|Notice what happens when you stop picking one.",
    "Only one feeling there today? That's fine. Come back to this when things feel mixed."] },
 { id:"talk-it-through", part:"bark", strand:"mind", ages:"all", name:"Talk It Through",
   text:"Tell someone you trust about one thing that's been hard or on your mind.", busy:"Send one honest line to someone you trust.",
   kidName:"Tell a Grown-Up", kidText:"Tell a grown-up about one thing that was hard today.", kidBusy:"Tell someone one hard thing.",
   how:["Saying a hard thing out loud to someone who cares shrinks it and helps you see it more clearly.",
    "Pick someone you trust: a friend, a family member, a counselor, or a mentor.|Pick a good time, maybe on a walk or a drive.|Start simply: \"Something's been on my mind.\"|Let them listen. You don't need them to fix it.",
    "Don't know who to tell? A counselor, chaplain, or pastor can be a good first person. If it feels like too much, call or text 988.",
    "Telling a grown-up helps hard things feel smaller.","Pick a grown-up you trust.|Tell them about one thing that was hard today.","Hard to start? Say, \"Can I tell you something?\""] },
 { id:"calm-down-toolkit", part:"bark", strand:"mind", ages:"all", name:"Calm-Down Toolkit",
   text:"Ask two people how they calm down. Add what works to your own short list of what helps you.", busy:"Name one thing that helps you calm down.",
   kidName:"My Calm Box", kidText:"With a grown-up, make a list or box of things that help you calm down.", kidBusy:"Name one thing that helps you calm down.",
   how:["Knowing what helps you calm down before you need it makes hard moments easier.",
    "Ask two people how they calm down when they're upset.|Share one thing that helps you, too.|Write your own list of three to five things that help.|Keep it on your phone or a card.|Next time you're upset, pick one thing from it.",
    "Not sure what helps? Try something from this library, like Slow Exhale or Plant Your Feet, and see.",
    "Having a plan helps when feelings get big.","With a grown-up, make a list or box of things that help you calm down.|Next time you're upset, pick one.","Ideas: a hug, a drink of water, balloon breaths, a favorite stuffed animal."] },
 { id:"small-wins", part:"bark", strand:"mind", ages:"all", name:"Small Wins",
   text:"Write one thing you did well today, even if it was small.", busy:"Name one small win from today.",
   kidName:"I Did It", kidText:"Tell a grown-up one thing you did well today.", kidBusy:"Say one thing you did well.",
   how:["Noticing small wins builds confidence and trains your mind to see what's going right.",
    "At the end of the day, think back.|Find one thing you did well, even something small.|Write it down.|Keep the list going, and read it on a hard day.",
    "Hard day? Getting through it counts as a win.",
    "Noticing what you did well helps you feel proud.","Think of one thing you did well today.|Tell a grown-up about it.","Small things count, like being kind or trying something new."] },
 { id:"learn-from-a-mistake", part:"bark", strand:"mind", ages:"teen", name:"Learn From a Mistake",
   text:"Write about a mistake and what it taught you.", busy:"Name one thing a recent mistake taught you.",
   how:["Mistakes are part of how people grow. Writing about one turns shame into something useful.",
    "Pick a recent mistake. Not the biggest one.|Write what happened, plainly.|Write what it taught you.|Write one thing you'll try next time.",
    "Too hard on yourself? Write it the way you'd talk to a friend who made the same mistake."] },
 { id:"scroll-break", part:"bark", strand:"mind", ages:"teen", name:"Scroll Break",
   text:"Take one evening off social media or group chats, and notice how you feel after.", busy:"Put your phone in another room for thirty minutes.",
   how:["Constant scrolling and group chats keep your mind on alert. A break gives it a chance to settle.",
    "Pick one evening this week.|Tell your people you'll be offline, if that helps.|Put your phone in another room, or log out of the apps.|Do something else: read, walk, talk, make something.|Notice how you feel afterward.",
    "Hard to stay off? Start with thirty minutes, or ask someone to help you set a screen-free time each day."] },
 { id:"peaceful-music", part:"bark", strand:"mind", ages:"all", name:"Peaceful Music",
   text:"Put on calm music and let yourself just be, with no scrolling.", busy:"Listen to one calm song.",
   kidName:"Calm Song", kidText:"Listen to a calm song with your eyes closed and notice how you feel.", kidBusy:"Listen to one calm song.",
   how:["Calm music can quiet a busy mind and help you notice what you feel inside.",
    "Pick music that feels peaceful.|Put your phone face down, or away.|Close your eyes and just listen, for one song or five minutes.|When it ends, notice how you feel now.",
    "Hand keeps reaching for your phone? Put it in another room first.",
    "Music can help your body feel calm.","Pick one calm song.|Close your eyes and listen.|Notice how you feel when it ends.","Hard to sit still? It's okay to sway."] },

 // ---------- Branches ----------
 { id:"my-people-tree", part:"branches", strand:"connect", ages:"all", name:"My People Tree",
   text:"Draw a tree and put your people on it. Star the ones you'd go to for help.", busy:"Name one person you could call if something went wrong.",
   kidName:"My People Tree", kidText:"Draw a tree and put your people on the branches. Put a star by someone you can go to for help.", kidBusy:"Name one grown-up you can go to for help.",
   how:["Seeing your people on the page shows you how held you are, and who to reach for when you need help.",
    "Draw a tree with roots, a trunk, and branches.|Put the people who shaped you in the roots, those closest to you in the trunk, and friends and community in the branches.|Star the ones you'd go to if something went wrong.|Star who you'd tell if a friend were in trouble.|Keep it where you can find it.",
    "Tree looks thin? That's worth knowing. Pick one branch to grow this month. Everyone needs at least one person to call.",
    "Knowing your people helps you feel safe.","Draw a big tree with lots of branches.|Write or draw your people on the branches.|Put a star by someone you can go to for help.","Ask a grown-up to help you remember everyone."] },
 { id:"make-room", part:"branches", strand:"connect", ages:"all", name:"Make Room for Someone",
   text:"Look for someone on the edges. Invite them to sit, play, or join in.", busy:"Say hi to someone who seems alone.",
   kidName:"Ask to Play", kidText:"Look for someone who might be alone, and ask them to play or sit with you.", kidBusy:"Say hi to someone new.",
   how:["Being invited in can change someone's day, and widening the circle makes it stronger for everyone.",
    "Look around: at lunch, at work, after a service, at a game.|Notice someone who seems alone or new.|Invite them: \"Want to sit with us?\" or \"Want to join?\"|Introduce them to one other person.",
    "Nervous? Bring a friend along. They might say no, and that's okay. Try again another day.",
    "Asking someone to play can make their whole day.","Look for someone who might be alone.|Ask them to play or sit with you.|Try it again with someone new next week.","Scared? Ask a friend to go with you."] },
 { id:"good-friend", part:"branches", strand:"connect", ages:"teen", name:"What Makes a Good Friend",
   text:"Write about a friend who helps you feel like yourself, and the kind of friend you want to be.", busy:"Name one thing a good friend does.",
   how:["Knowing what good friendship looks like helps you choose friends well, and be one.",
    "Think of a friend who helps you feel more like yourself.|Write what they do that makes that true.|Write the kind of friend you want to be.|Pick one thing to practice this week.",
    "No friend like that right now? Write what you're looking for. That's where finding one starts."] },

 // ---------- Leaves ----------
 { id:"my-body-tree", part:"leaves", strand:"body", ages:"all", name:"My Body Tree",
   text:"Draw your body as a strong tree. Label what each part helps you do.", busy:"Name one thing your body helps you do.",
   kidName:"My Body Tree", kidText:"Draw your body as a strong tree. Label what each part helps you do.", kidBusy:"Name one thing your arms or legs help you do.",
   how:["Seeing your body as a tree helps you notice what it does for you, not just how it looks.",
    "Draw a tree shaped like you: roots for feet, a trunk for your body, branches for arms.|Label what each part helps you do: walk, hug, carry, create.|Add leaves for the things you're thankful your body can do.|Keep it where you'll see it.",
    "Hard time with your body right now? Label just one part. And if how you see your body has been hard for a while, talk with someone you trust.",
    "Your body is strong like a tree.","Draw your body as a tree.|Label what each part helps you do, like run, hug, or jump.","Ask a grown-up to write the words."] },
 { id:"my-no-plan", part:"leaves", strand:"body", ages:"teenOnly", name:"My No Plan",
   text:"Write your plan for saying no if someone offers you something, and tell a grown-up what you've seen offered.", busy:"Pick one line you'll use to say no.",
   how:["Deciding ahead of time makes it much easier to say no in the moment.",
    "Think about what you might be offered: vapes, alcohol, pills, or something else.|Write two or three lines you'll use, like \"No thanks, I'm good\" or \"I've got practice tomorrow.\"|Plan a way out: a code word you can text a grown-up who will come get you.|Tell a trusted grown-up what you've seen other kids being offered.",
    "Worried about getting a friend in trouble? You can talk about what's going around without naming anyone. If someone is in danger, tell a grown-up right away."] },

 // ---------- Fruit ----------
 { id:"tomorrow-wish", part:"fruit", strand:"hope", ages:"all", name:"Tomorrow Wish",
   text:"Before bed, name one good thing you hope happens tomorrow. In the morning, look for it.", busy:"Name one good thing you hope happens tomorrow.",
   kidName:"Tomorrow Wish", kidText:"Before bed, say one good thing you hope happens tomorrow.", kidBusy:"Say one wish for tomorrow.",
   how:["Ending the day with a hope gives you something to look for, and looking helps you find it.",
    "Before bed, think about tomorrow.|Name one good thing you hope happens.|Say it out loud, or write it down.|In the morning, remember it and look for it.",
    "Dreading tomorrow? Hope for one small thing: a good lunch, a kind word.",
    "A wish for tomorrow helps you fall asleep happy.","Before bed, say one good thing you hope happens tomorrow.|In the morning, look for it.","Ask a grown-up to share a wish too."] },
 { id:"share-good-news", part:"fruit", strand:"hope", ages:"all", name:"Share Good News",
   text:"Tell someone about something you're excited about or looking forward to.", busy:"Tell someone one good thing.",
   kidName:"Share Good News", kidText:"Tell someone about something you're excited about.", kidBusy:"Tell someone one happy thing.",
   how:["Sharing good news with someone who cares makes the good feeling grow and last.",
    "Notice something you're excited about or looking forward to.|Pick someone who'll be glad for you.|Tell them, with details.|When they share good news, be glad with them too.",
    "Feels like bragging? Sharing joy is a gift. Start with someone close.",
    "Telling happy news makes it feel even happier.","Think of something you're excited about.|Tell someone about it.","Practice by telling a pet or a stuffed animal first."] },
 { id:"hope-story", part:"fruit", strand:"hope", ages:"all", name:"Ask for a Hope Story",
   text:"Ask an older person about a time things got better for them, or what they hoped for at your age.", busy:"Ask someone about one time things got better.",
   kidName:"Ask About Hope", kidText:"Ask a grown-up what they hoped for when they were your age.", kidBusy:"Ask a grown-up what they wished for as a kid.",
   how:["Hearing how things got better for someone else helps you believe they can get better for you.",
    "Pick someone older you trust.|Ask: \"Tell me about a time things got better for you.\"|Or ask: \"What did you hope for at my age?\"|Listen, and ask what helped.",
    "Nervous? Ask in the car or over a meal.",
    "Grown-ups' stories help you know good things can happen.","Pick a grown-up.|Ask what they hoped for when they were your age.","Try a grandparent. They love this question."] },
 { id:"made-it-through", part:"fruit", strand:"hope", ages:"teen", name:"I Made It Through",
   text:"Think of a hard time you got through. Remember what helped, and that you made it.", busy:"Remember one hard time you got through.",
   how:["Remembering hard times you got through reminds you that you can get through this one too.",
    "Think of a hard time you got through.|Write what helped: people, choices, faith, time.|Write what you learned about yourself.|Read it on a hard day.",
    "Still in the middle of a hard time? Write about a smaller one you got through. If you can't see a way through right now, reach out to someone you trust, or call or text 988."] },
 { id:"clear-one-space", part:"fruit", strand:"hope", ages:"all", name:"Clear One Small Space",
   text:"Clean up one small space, a drawer or a desk, and notice how it feels after.", busy:"Clear one surface for five minutes.",
   kidName:"Clean Up One Spot", kidText:"Clean up one small spot, like your desk or a shelf.", kidBusy:"Put away five things.",
   how:["Clearing one small space gives you a quick win, and a feeling that things can change.",
    "Pick one small space: a drawer, a desk, a counter.|Set a timer for ten minutes.|Clear it out. Toss or put away what doesn't belong.|Notice how it feels after.",
    "Overwhelmed by the whole house? That's why it's one small space. Stop when the timer ends.",
    "A clean spot feels good.","Pick one small spot, like your desk or a shelf.|Clean it up.|Show a grown-up.","Make it a race against a song."] }
];

// =====================================================================
// THE LIBRARY: every Grove practice plus the new ones, in part order.
// Grove practices keep their place in the twelve-week rotation. New
// practices live only here until someone picks one.
// Session 6's site-wide search can read window.GroveLibrary.
// =====================================================================
const LIBRARY = (function(){
  const out = [];
  PARTS.forEach(pt => {
    pt.strands.forEach(sid => {
      const seen = {};
      (PRACTICES[sid] || []).forEach((p, i) => { if (seen[p[0]]) return; seen[p[0]] = 1;
        out.push({ key:'g:'+sid+':'+i, part:pt.id, strand:sid, idx:i, ages:'all', isNew:false,
          name:p[0], text:p[1], busy:p[2], kidName:p[3], kidText:p[4], kidBusy:p[5], how:(HOW[sid] || {})[p[0]] || null }); });
    });
    LIB_NEW.filter(n => n.part === pt.id).forEach(n => out.push(Object.assign({ key:'n:'+n.id, isNew:true }, n)));
  });
  const low = a => a.filter(Boolean).join(' ').replace(/<[^>]+>/g, '').toLowerCase();
  out.forEach(it => { it.findName = low([it.name, it.kidName]); it.findText = low([it.text, it.kidText, PART[it.part].name, PART[it.part].sub, STRAND[it.strand].name]);
    it.find = it.findName + ' ' + it.findText + ' ' + low([(it.how || []).join(' ')]); });
  return out;
})();
const LIB_BY_KEY = Object.fromEntries(LIBRARY.map(it => [it.key, it]));
// Which practices fit which tree. "teen" means middle school and up.
const libFits = (it, age) => it.ages === 'all' || (it.ages === 'teen' ? age !== 'maple' : it.ages === 'teenOnly' ? (age === 'aspen' || age === 'pine') : true);
function libSearch(q, age){
  const words = String(q || '').toLowerCase().split(/\s+/).filter(Boolean);
  const hits = LIBRARY.filter(it => (!age || libFits(it, age)) && words.every(w => it.find.includes(w)));
  if (!words.length) return hits;
  // Strongest matches first: the practice name, then what it says, then the how-to.
  const score = it => words.reduce((n, w) => n + (it.findName.includes(w) ? 3 : it.findText.includes(w) ? 2 : 1), 0);
  return hits.map((it, i) => [it, score(it), i]).sort((a, b) => b[1] - a[1] || a[2] - b[2]).map(x => x[0]);
}
window.GroveLibrary = { items: LIBRARY, get: k => LIB_BY_KEY[k] || null, fits: libFits, search: libSearch };
