/* =====================================================================
   WILLOW FAITH . the faith question and tradition cards
   Read by Willow and Willow Guide. Edit wording here.
   Every card ends the same way: families practice their faith in their
   own ways. Ask. Cards are drafts until a reviewer from that tradition
   reads them (see the Owner review list).
   ===================================================================== */
(function(){
const INTAKE = {
  who: `What should we know about you as a person, so we can care for you well?`,
  ask: `Faith, spirit, or something else. What has mattered to you?`,
  welcome: `Every answer is welcome here, including none.`,
  groups: [
    ['christian', `Christian`, ['catholic', 'lutheran', 'methodist', 'presbyterian', 'episcopal', 'baptist', 'nondenom', 'pentecostal', 'anabaptist', 'orthodox', 'lds', 'jw', 'adventist', 'quaker', 'cs', 'christian-other']],
    ['faiths', `Other faiths`, ['jewish', 'muslim', 'hindu', 'buddhist', 'sikh', 'bahai', 'uu']],
    ['land', `Family and land ways`, ['hmong', 'indigenous', 'nature']],
    ['paths', `Other paths`, ['sbnr', 'agnostic', 'atheist', 'humanist', 'raised', 'private']]
  ],
  own: `My own words`,
  follow: [
    ['matters', `How much does it matter to you right now?`, [['none', `Not at all`], ['little', `A little`], ['lot', `A lot`], ['unsure', `I'm not sure`]]],
    ['lives', `How do you live it out, if you do?`, [['prayer', `Prayer`], ['worship', `Worship`], ['reading', `Sacred reading`], ['music', `Music`], ['outdoors', `Time outdoors`], ['meditation', `Meditation`], ['family', `Family traditions`], ['helping', `Helping others`], ['own', `My own way`]]],
    ['changed', `Has your relationship with it changed?`, [['steady', `Steady`], ['stronger', `Stronger`], ['quiet', `Gone quiet`], ['away', `I stepped away`], ['hurt', `It hurt me`], ['complicated', `It's complicated`]]]
  ],
  call: `Is there someone from your faith or community we should call?`,
  never: `Is there anything we should never do?`,
  neverEx: `"Don't pray over me." "No visits from my old church." "Never remove my garments."`,
  universal: `When someone answers "Not at all" or "Rather not say," Willow uses universal language: meaning, love, legacy, what grounds you.`
};

const RULES = [
  [`Never pray in a tradition that isn't theirs without asking first.`, `Offer, don't perform. "Would you like a prayer? From your tradition, or in my own words?"`],
  [`Never use the bedside to convert.`, `Not chaplains, not doulas, not family. When a relative pushes, the chaplain's job is to protect the dying person's own faith, or their lack of one.`],
  [`Ask before touching the body after death.`, `Some traditions want same-gender care, some want the body left undisturbed for a time, some want family to wash and dress. Ask first, every time.`],
  [`A clear mind at death matters to some traditions.`, `Buddhist, Hindu, and many Muslim families may want the person alert enough to pray. That is a conversation with the hospice nurse about balancing comfort and clarity, not a refusal of comfort.`],
  [`Cremation, embalming, autopsy, and donation views differ.`, `Never assume. The funeral home and the family's clergy can help.`],
  [`When clergy can't come in time,`, `Willow always offers what family can do themselves, and says plainly that God's love is not stuck in traffic.`]
];

const END = `Families practice their faith in their own ways. Ask.`;

// Card fields: words, comfort, before, after, ask, hard, call, avoid, care, note, keys.
const CARDS = {
  catholic: { name: `Catholic`,
    words: `God, Jesus, Mary, the saints. "Last rites" is what most families will call it.`,
    comfort: `The rosary, Hail Mary, Our Father, the Divine Mercy chaplet, holy water, a crucifix, medals or a scapular. Saint Joseph is the patron of a happy death.`,
    before: `Anointing of the Sick and Confession need a priest. Viaticum (last Communion) can come from a priest, deacon, or lay minister. A priest can also give the Apostolic Pardon. Anyone can pray the rosary and prayers of commendation.`,
    after: `Anointing is for the living. After death, the priest prays for the dead. Cremation is allowed, with the remains kept together and buried or placed in a sacred place. Vigil or wake, funeral Mass, committal.`,
    ask: `"Would you like a priest? Has it been a while since Confession?" "Is there a parish you belong to?"`,
    hard: `"The priest didn't make it. Did I fail them?" Willow answers gently: the Church teaches that sorrow for sin with love of God is met by God's mercy, even without a priest. Also: divorce and Communion, fear of hell or purgatory, children who left the Church.`,
    call: `Their parish, or the hospice can find a priest on call. Say "urgent" when time is short.`,
    keys: `last rites, priest, anointing, confession, rosary, Hail Mary, Viaticum, holy water, Mass, purgatory` },
  lutheran: { name: `Lutheran`,
    words: `God, Jesus, grace, gift. "Remember your baptism."`,
    ask: `Which Lutheran church? ELCA, LCMS, and WELS practice differently, and in Minnesota it matters.`,
    comfort: `"Children of the Heavenly Father," "Beautiful Savior," "A Mighty Fortress," Psalm 23, Romans 8:38-39, and the Song of Simeon: "Lord, now lettest thou thy servant depart in peace" (Luke 2:29, KJV).`,
    before: `The Commendation of the Dying. In LCMS practice it includes prayer, a psalm and reading, a litany, confession and absolution, and the Lord's Supper, with a version for when no pastor can be there. LCMS and WELS usually give Communion only through their own pastor. ELCA Communion is open to the baptized.`,
    after: `Funeral in the church, burial or cremation.`,
    hard: `"Have I done enough?" The Lutheran answer is grace: it was never about enough. Watch for quiet Scandinavian and German stoicism: "Don't make a fuss." Make room to fuss.`,
    call: `Their own pastor, by synod.`,
    keys: `pastor, ELCA, LCMS, WELS, Communion, Commendation of the Dying, baptism, grace, synod` },
  methodist: { name: `Methodist`,
    words: `God, Jesus, grace. "Strangely warmed" if they know their Wesley.`,
    comfort: `Charles Wesley hymns, Psalm 23, the Lord's Prayer.`,
    before: `The United Methodist Ministry with the Dying includes Communion, reaffirming the baptismal covenant, the Lord's Prayer or Psalm 23, and a commendation with a hand on the head. Communion is an open table: anyone may receive. Its prayers come from the public domain 1979 Book of Common Prayer.`,
    call: `Their pastor.`,
    keys: `Methodist, UMC, Wesley, open table, Communion` },
  presbyterian: { name: `Presbyterian and Reformed`,
    words: `God, Christ, providence, sovereignty.`,
    comfort: `The Psalms above all. The first question of the Heidelberg Catechism (1563) is a deathbed classic: "What is your only comfort in life and in death?" Its answer begins, "That I am not my own, but belong... to my faithful Savior Jesus Christ."`,
    before: `No last rites sacrament. Prayer, scripture, and Communion through the pastor and elders.`,
    hard: `"Is this God's will?" can comfort or wound. Some fear they are not among the chosen. Lead with belonging, not with doctrine.`,
    call: `Their pastor or an elder.`,
    keys: `Presbyterian, PCUSA, Reformed, CRC, Heidelberg, only comfort, elder` },
  episcopal: { name: `Episcopal and Anglican`,
    words: `God, Christ, the Spirit.`,
    comfort: `The Book of Common Prayer itself. The 1979 Ministration at the Time of Death includes a prayer for a person near death and a Litany at the Time of Death. It is public domain, so Willow includes it in full, with the commendation "Depart, O Christian soul."`,
    before: `A priest anoints. Confession can be heard by a priest, or a deacon or lay person can declare God's forgiveness using the prayer book's form. Communion from a priest, deacon, or lay Eucharistic visitor.`,
    call: `Their rector or parish.`,
    keys: `Episcopal, Anglican, Book of Common Prayer, Depart O Christian soul, litany` },
  baptist: { name: `Baptist`,
    words: `God, Jesus, Lord, saved, heaven.`,
    comfort: `Scripture read aloud (John 14:1-3, Romans 8, Psalm 23), "Amazing Grace," "It Is Well with My Soul," "Blessed Assurance." All three hymns are public domain.`,
    before: `No sacraments or last rites. Prayer, scripture, and the pastor's visit are the heart of it. Some churches lay hands and pray.`,
    hard: `"Am I saved? Did I do it right?" And the heaviest one: "My son never accepted Christ." Meet assurance with scripture, and meet fear for others with presence, not answers.`,
    note: `Many Black Baptist families speak of a homegoing: a gathered family, gospel music, a celebration as much as a farewell. Hope for a miracle may be strong. Honor it (see the miracle guide).`,
    call: `Their pastor, and often the church mothers or deacons.`,
    keys: `Baptist, saved, assurance, salvation, Amazing Grace, It Is Well, homegoing` },
  nondenom: { name: `Non-denominational and Evangelical`,
    words: `Jesus, God, "my relationship with the Lord."`,
    comfort: `Worship songs they love (named and linked, never copied), scripture, praying together out loud, a prayer circle.`,
    before: `No formal rite. Their pastor or small group may want to come pray.`,
    hard: `"Am I right with God?" Some have no church home now, and feel that loss. Willow can offer a chaplain as the church that came to them.`,
    call: `Their pastor or small group leader.`,
    keys: `nondenominational, evangelical, praise, worship song, small group, prayer circle` },
  pentecostal: { name: `Pentecostal and Charismatic`,
    words: `Jesus, the Holy Spirit, healing, victory, the blood.`,
    comfort: `Loud worship, laying on of hands, anointing with oil by the elders (James 5:14), prayer in tongues, a full room.`,
    hard: `Hope for a miracle is often strong, and the deepest wound is "I didn't have enough faith." Willow says plainly: dying is not a failure of faith. Palliative experts also suggest inviting the patient's own pastor to the family meeting.`,
    call: `Their pastor.`,
    keys: `Pentecostal, Assemblies of God, healing, miracle, tongues, anointing oil, not enough faith` },
  anabaptist: { name: `Mennonite, Amish, and Anabaptist`,
    words: `God, Jesus, community, "God's will."`,
    comfort: `Quiet, hymns sung in harmony, the church community bringing meals and sitting with the family.`,
    after: `Amish families often prepare the body themselves and keep services plain. Ask before taking photos.`,
    call: `The bishop, minister, or deacon of their church.`,
    keys: `Mennonite, Amish, Anabaptist, Hutterite, plain` },
  orthodox: { name: `Orthodox`,
    words: `God, Christ, the Theotokos (Mary), the saints.`,
    comfort: `Icons near the bed, a prayer rope, the Jesus Prayer: "Lord Jesus Christ, Son of God, have mercy on me."`,
    before: `Confession, Holy Unction, and Communion through an Orthodox priest.`,
    after: `Trisagion prayers. The Church generally opposes cremation. Memorials at 40 days and beyond.`,
    call: `Their parish priest.`,
    keys: `Orthodox, Greek, Russian, Ethiopian, icon, unction, Jesus Prayer, Trisagion` },
  lds: { name: `Latter-day Saint`,
    words: `Heavenly Father, the Savior, families forever.`,
    comfort: `A priesthood blessing (anointing with consecrated oil, given by Melchizedek priesthood holders), hymns, the hope that families can be together forever.`,
    after: `Temple garments are sacred. Ask before removing them, and keep the body covered. Family or Relief Society sisters may dress the body in temple clothing.`,
    hard: `Family members who left the church; sealings and what they mean now.`,
    call: `The ward bishop or ministering brothers and sisters.`,
    keys: `LDS, Mormon, priesthood blessing, garments, bishop, sealed, Relief Society` },
  jw: { name: `Jehovah's Witness`,
    words: `Jehovah, Jesus, the resurrection, Paradise.`,
    comfort: `Visits and prayer from congregation elders, scripture about the resurrection (John 5:28-29).`,
    avoid: `"She's in heaven now." Most Witnesses hope for resurrection to life on a paradise earth, and many see death as a sleep. No last rites. Blood transfusions are refused.`,
    call: `The congregation elders.`,
    keys: `Jehovah's Witness, Kingdom Hall, elders, blood, resurrection, paradise` },
  adventist: { name: `Seventh-day Adventist`,
    words: `God, Jesus, the blessed hope, the Sabbath (sundown Friday to sundown Saturday).`,
    avoid: `"He's watching over you now." Many Adventists see death as a sleep until Christ returns.`,
    comfort: `An anointing service by the pastor and elders, Sabbath hymns, the Second Coming as hope.`,
    call: `Their pastor.`,
    keys: `Adventist, SDA, Sabbath, second coming` },
  quaker: { name: `Quaker (Friends)`,
    words: `The Light, the Spirit, "holding you in the Light."`,
    comfort: `Shared silence. Less ritual, more presence.`,
    after: `A memorial meeting for worship.`,
    call: `Their meeting's clerk or friends.`,
    keys: `Quaker, Friends, held in the Light, silence` },
  cs: { name: `Christian Science`,
    words: `God, divine Mind, Love.`,
    comfort: `Prayer, a Christian Science practitioner, and Christian Science nurses who give non-medical care. Some will decline medication. Respect it, and make sure they know comfort care is there if they want it.`,
    call: `Their practitioner or branch church.`,
    keys: `Christian Science, practitioner` },
  jewish: { name: `Jewish`,
    ask: `Orthodox, Conservative, Reform, or cultural? Practice varies widely.`,
    words: `God, HaShem (Orthodox families often use this), Adonai. Avoid Christian prayers, crosses, and "in Jesus' name."`,
    comfort: `The Shema, traditionally among the last words. The Vidui, a confession before death, said by the person or with a rabbi or family. Psalms (Tehillim), especially 23 and 121. The Mi Sheberach prayer for healing.`,
    after: `The body is not left alone. A shomer sits with it. The chevra kadisha performs the ritual washing. Burial is as soon as possible, traditionally within a day. Cremation and autopsy are traditionally avoided, though Reform practice varies. Mourners may say "Baruch Dayan HaEmet" on hearing of a death. Then shiva (seven days), Kaddish said by mourners, the yahrzeit each year.`,
    hard: `"Is there anything after this?" Judaism holds many answers, and "we don't know" is an honest Jewish answer too. Family history of the Holocaust may surface. God's silence may be named out loud.`,
    call: `Their rabbi or synagogue. The funeral home can reach the chevra kadisha.`,
    keys: `Jewish, rabbi, Shema, Vidui, shomer, chevra kadisha, shiva, Kaddish, yahrzeit, Baruch Dayan HaEmet` },
  muslim: { name: `Muslim`,
    note: `Important for St. Cloud's Somali community. Ask about an interpreter, and never use children to interpret.`,
    words: `Allah, insha'Allah (God willing), alhamdulillah (praise God).`,
    comfort: `The Shahada, recitation of the Qur'an, du'a (personal prayer), facing the Qiblah, and family presence. Surah Yasin (chapter 36) is often recited, with the person on their right side facing the Qiblah when possible. Help with prayer five times a day, including dry ablution if water is hard. Expect many visitors. It is love, not a crowd problem.`,
    care: `Same-gender caregivers when possible. Keep the body covered for modesty. Islamic scholars consulted on sedation found it permissible under medical necessity, while stressing that the person should be able to recite the Shahada at the end. That is a nurse conversation, not a refusal of comfort.`,
    after: `Close the eyes, straighten the body, cover it. Cremation is prohibited. Burial is as soon as possible, ideally within 24 hours, and ritual washing (ghusl) is done by family or trained community members of the same gender.`,
    hard: `"Is my illness a punishment?" In Islam, illness can be a test and a purification, and patience (sabr) is honored. "Is it wrong to stop treatment?" Point gently to their imam.`,
    call: `The family's imam or local mosque.`,
    keys: `Muslim, Islam, imam, mosque, Qur'an, Yasin, Shahada, qibla, ghusl, du'a, Somali, janazah` },
  hindu: { name: `Hindu`,
    words: `God, Bhagwan, or the family's deity: Krishna, Shiva, Rama, Devi. Karma, dharma, rebirth, moksha.`,
    comfort: `Chanting God's name (Om, "Om Namah Shivaya," "Ram"), readings from the Bhagavad Gita, bhajans (devotional songs). Near death, some families place Ganga water and a tulsi leaf in the mouth. Some wish to give gifts to those in need before death.`,
    care: `The last thoughts matter in many Hindu teachings, so families may want the person as alert as comfort allows.`,
    after: `Family often washes and dresses the body. Cremation is usual and prompt. Thirteen days of mourning rites are common.`,
    hard: `"Is this my karma?" Never let karma become blame. "Did I fulfill my duty to my family?"`,
    call: `A pandit (priest) at the family's temple.`,
    keys: `Hindu, pandit, temple, Ganga water, tulsi, Gita, karma, cremation` },
  buddhist: { name: `Buddhist`,
    ask: `Which tradition? Theravada (Thai, Lao, Cambodian, Burmese, Sri Lankan), Mahayana (Vietnamese, Chinese, Japanese Pure Land, Zen), or Tibetan.`,
    words: `The Buddha, the Dharma, the Sangha, impermanence, compassion.`,
    comfort: `Chanting and sutras, a calm and quiet room, breath awareness. In Pure Land practice, reciting Amitabha's name. Monks or nuns at the bedside.`,
    care: `The state of mind at death is believed to shape what comes next. Some prefer the clearest mind comfort allows.`,
    after: `Some families want the body left undisturbed for hours or longer while chanting continues. Ask before moving anything. Rites may continue for 49 days.`,
    hard: `Fear of a difficult rebirth, guilt about karma, the work of letting go.`,
    call: `Their temple or a monastic.`,
    keys: `Buddhist, monk, temple, chanting, sutra, Amitabha, rebirth, 49 days` },
  sikh: { name: `Sikh`,
    words: `Waheguru, the Guru, hukam (God's will).`,
    comfort: `Recitation of Gurbani (Japji Sahib, Sukhmani Sahib, Kirtan Sohila), quiet chanting of "Waheguru."`,
    care: `Never remove or cut the five articles of faith (uncut hair, kara, kanga, kachera, kirpan), in life or after death. Respect the turban.`,
    after: `Cremation, with prayers from the community.`,
    call: `The granthi at their gurdwara.`,
    keys: `Sikh, gurdwara, Waheguru, Japji, kirpan, turban` },
  bahai: { name: `Bahá'í`,
    words: `God, Bahá'u'lláh, the progress of the soul.`,
    comfort: `Bahá'í prayers for healing and for the departed.`,
    after: `Burial, not cremation, traditionally within an hour's travel of the place of death. A special prayer for the dead is said at the funeral.`,
    call: `The local Spiritual Assembly.`,
    keys: `Bahai, Baha'i, Bahá'u'lláh, Spiritual Assembly` },
  uu: { name: `Unitarian Universalist`,
    words: `Whatever the person uses. UUs hold many beliefs, from Christian to humanist to earth-centered.`,
    comfort: `Their own chosen readings, music, and covenant community.`,
    after: `A memorial service shaped by the person's own values.`,
    call: `Their minister or congregation.`,
    keys: `Unitarian, UU, UUA` },
  hmong: { name: `Hmong`,
    ask: `Traditional (animist) or Christian? Animist elders emphasize shamanic rituals like soul calling and spiritual offerings, while Christian Hmong elders lean on prayer, and both believe family should provide care at the end of life.`,
    note: `Decisions are made by the family and community, not the patient alone. Care is often at home, mixing medicine and traditional healing. Ask who the family's decision-makers are, often male elders or clan leaders.`,
    words: `Some families avoid speaking of death directly, fearing it invites it. Speak gently and indirectly at first. Ask permission before naming what's coming.`,
    comfort: `Being home, family gathered, soul-calling ceremonies, a shaman (txiv neeb) welcomed into care. For Christian Hmong families, prayer and their pastor.`,
    after: `Traditional funerals last several days, with the qeej (a reed pipe) and chanting to guide the soul back to the ancestors. Burial clothing is chosen with great care. Completing these rituals so the soul reaches the afterlife is central.`,
    care: `Frame hospice as support for the family to care for their own at home. Honoring Choices Minnesota has health care directive forms in Hmong.`,
    call: `The family's clan leader, shaman, or Hmong pastor.`,
    keys: `Hmong, shaman, txiv neeb, soul calling, qeej, clan leader, Hmong pastor` },
  indigenous: { name: `Native and Indigenous ways`,
    ask: `"Are there ways of your people you'd like followed?" In Minnesota, that may be Ojibwe (Anishinaabe), Dakota, or another nation. Never generalize across nations.`,
    note: `Many Native families are also Christian, often Catholic or Episcopal. Some carry deep wounds from churches and boarding schools. A chaplain arrives humbly and lets the family set the pace.`,
    comfort: `Tobacco offerings, smudging with sage, sweetgrass, or cedar, the drum, songs, a spiritual leader or elder. Plan smudging with the hospice team for oxygen and fire safety.`,
    after: `Some families keep teachings about the spirit's journey over several days, and may keep a fire or sit with the body. Ask, and follow.`,
    call: `The family's elder or spiritual leader, or tribal health services.`,
    keys: `Native, Ojibwe, Anishinaabe, Dakota, tobacco, smudge, sage, sweetgrass, drum, elder` },
  nature: { name: `Nature, earth-centered, and Pagan`,
    words: `The earth, the seasons, the cycle, the circle, Spirit, the Goddess or the gods if they use them.`,
    comfort: `A window, plants, stones, water, the season outside named out loud. For Pagan and Wiccan families, a small circle of friends, candles (battery ones near oxygen), and their own rituals. Frame death as they do: part of the cycle, a return to the earth.`,
    after: `Many are drawn to green burial or a natural memorial.`,
    call: `Their circle, coven, or community, if they have one.`,
    keys: `nature, earth, Pagan, Wiccan, Heathen, green burial, circle` },
  sbnr: { name: `Spiritual but not religious`,
    words: `Spirit, energy, the universe, love, something bigger, presence. Use theirs.`,
    comfort: `Nature, music, breath, meditation, gratitude, the people they love, legacy work.`,
    avoid: `"So you don't have a faith." Many SBNR people pray, and many have a rich inner life.`,
    note: `Often underneath: a history with religion. The "It hurt me" door is worth offering gently.`,
    keys: `spiritual not religious, universe, energy, meditation` },
  agnostic: { name: `Agnostic`,
    words: `"I don't know" is honest. Willow honors it rather than trying to resolve it.`,
    comfort: `Wonder, love, honesty, the people and moments that mattered.`,
    hard: `"What if there's nothing?" Meet it with presence and meaning: what they gave, who they loved, what continues in other people.`,
    keys: `agnostic, not sure, nothing after` },
  atheist: { name: `Atheist`,
    words: `Meaning, love, legacy, nature, science, the universe, the people here. No God-language unless they bring it.`,
    avoid: `"I'll pray for you" (unless asked), a suggestion of a deathbed conversion, or treating their worldview as a problem to solve.`,
    comfort: `Awe at the natural world, the science of being made of old stardust, legacy work, the Four Things, humor, plain honesty about dying.`,
    care: `Protect their integrity. Some fear family will claim a conversion after they die. A clear note in What matters to me helps.`,
    after: `A celebration of life, a humanist celebrant, body donation.`,
    keys: `atheist, no religion, not religious, no God` },
  humanist: { name: `Humanist`,
    words: `Reason, compassion, human dignity, the good we do here.`,
    comfort: `Values reflection, legacy letters, a humanist celebrant or chaplain.`,
    call: `A humanist celebrant, if they want one.`,
    keys: `humanist, celebrant, secular` }
};

// When faith has changed.
const CHANGED = [
  [`"The church hurt me."`, `Interpersonal struggle`, `"Being hurt by a church is not the same as being far from God." The church is the people, not the building or the brand.`],
  [`"I'm not sure I believe anymore."`, `Doubt`, `Doubt is welcome here. Questions are not a failure of faith. Many saints had more questions than answers.`],
  [`"God left me." "God is punishing me."`, `Divine struggle`, `Listen first. Don't defend God. The Psalms are full of people yelling at God, and God stayed.`],
  [`"Life doesn't feel like it means anything."`, `Ultimate meaning`, `Meaning-centered prompts: what you gave, how you face this, what you still love.`],
  [`"I've done things I can't take back."`, `Moral struggle`, `Guilt points to repair (the Four Things). Shame gets met with worth and company. Not the mistake. The recovery.`]
];
const HOME = `Some people want to return to the faith they left. Welcome them with no "I told you so" from anyone. Find their kind of clergy fast. A Catholic who left 40 years ago may want Confession today, and that is a gift, not a failure.`;
const WOUNDS = `Rejection over divorce, sexuality, or a pregnancy. Clergy abuse. Being shamed from a pulpit. Boarding schools for Native families. Never ask for details. Believe them, and protect them from anyone who'd add to it.`;
const MIXED = [
  [`The dying person's own wishes come first.`, `If they can't speak, follow their health care agent and what they said before.`],
  [`Each helper gets their own words.`, `Willow speaks to each person in their own language.`],
  [`When a family member pushes faith at the bedside,`, `the chaplain's job is to protect the dying person's own faith, or their lack of one. "Let's keep this room about what your dad wants."`],
  [`Rituals can stack.`, `A priest at 2:00 and the grandkids' favorite song at 3:00. Both are love.`]
];
const KIDS = `Tell children the truth about death, in simple words, using the word "died." Then let the family's faith answer "where did Grandma go" in its own way. "Different people believe different things. In our family, we believe..." is honest and kind.`;
const CHANGED_KEYS = `left the church, church hurt, lost my faith, angry at God, God punishing, doubt, coming back, prodigal`;

window.WILLOW_FAITH = { intake: INTAKE, rules: RULES, end: END, cards: CARDS, changed: CHANGED, home: HOME, wounds: WOUNDS, mixed: MIXED, kids: KIDS, changedKeys: CHANGED_KEYS };
})();
